-- GENERATED by scripts/genprogress.py -- do not hand-edit.
-- Per-room door->target flag requirements + flag grants, used by
-- the in-game Progress menu (test mode) and offline validators.
return {
  start = { room = "camp_awake", door = "A" },
  derived = {
    coredoor = { room = "camp_main", req = { "corekey1", "corekey2", "corekey3" } },
  },
  rooms = {
    ["camp_awake"] = {
      doors = {
        A = {},
        B = { "camp_main", "D" },
      },
      gives = {
        ["ent:9"] = { flags = { "ch_shelf" }, req = {  }, kind = "chest" },
        ["ent:j"] = { flags = { "telenet" }, req = { "boss_tideengine" }, kind = "npc" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:9", reqs = { { "driftvanes" } } },
        { from = "door:A", to = "ent:j", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:9", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "ent:j", reqs = { {  } } },
      },
    },
    ["camp_hut"] = {
      doors = {
        A = { "camp_main", "E" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
      },
    },
    ["camp_main"] = {
      doors = {
        A = { "camp_tele", "B" },
        B = { "stair_junction", "A" },
        D = { "camp_awake", "B" },
        E = { "camp_hut", "A" },
      },
      gives = {
        ["ent:3"] = { flags = { "cap_camp" }, req = {  }, kind = "capsule" },
        ["ent:e"] = { flags = { "linkblast", "met_elder" }, req = {  }, kind = "npc" },
        ["ent:f"] = { flags = { "ferro_rescued" }, req = {  }, kind = "npc" },
        ["ent:f*2"] = { flags = { "ferro_stage1" }, req = { "ferro_rescued", "ferrocoil" }, kind = "npc" },
        ["ent:k"] = { flags = { "camp_barricade" }, req = { "linkblast" }, kind = "linkcore" },
        ["ent:u"] = { flags = { "telenet" }, req = { "boss_tideengine" }, kind = "npc" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "camp_barricade" } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { {  } } },
        { from = "door:A", to = "ent:3", reqs = { {  } } },
        { from = "door:A", to = "ent:e", reqs = { {  } } },
        { from = "door:A", to = "ent:f", reqs = { {  } } },
        { from = "door:A", to = "ent:f*2", reqs = { {  } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
        { from = "door:A", to = "ent:u", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "door:E", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:3", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:e", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:f", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:f*2", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:k", reqs = { { "camp_barricade" } } },
        { from = "door:B", to = "ent:u", reqs = { { "camp_barricade" } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { { "camp_barricade" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:E", reqs = { {  } } },
        { from = "door:D", to = "ent:3", reqs = { {  } } },
        { from = "door:D", to = "ent:e", reqs = { {  } } },
        { from = "door:D", to = "ent:f", reqs = { {  } } },
        { from = "door:D", to = "ent:f*2", reqs = { {  } } },
        { from = "door:D", to = "ent:k", reqs = { {  } } },
        { from = "door:D", to = "ent:u", reqs = { {  } } },
        { from = "door:E", to = "door:A", reqs = { {  } } },
        { from = "door:E", to = "door:B", reqs = { { "camp_barricade" } } },
        { from = "door:E", to = "door:D", reqs = { {  } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:3", reqs = { {  } } },
        { from = "door:E", to = "ent:e", reqs = { {  } } },
        { from = "door:E", to = "ent:f", reqs = { {  } } },
        { from = "door:E", to = "ent:f*2", reqs = { {  } } },
        { from = "door:E", to = "ent:k", reqs = { {  } } },
        { from = "door:E", to = "ent:u", reqs = { {  } } },
      },
    },
    ["camp_tele"] = {
      doors = {
        B = { "camp_main", "A" },
      },
      gives = {
        ["ent:2"] = { flags = { "chest_camptele" }, req = {  }, kind = "chest" },
        ["ent:j"] = { flags = { "telenet" }, req = { "boss_tideengine" }, kind = "npc" },
        ["ent:t"] = { flags = { "tp_camp" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:2", reqs = { {  } } },
        { from = "door:B", to = "ent:j", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["cold_1"] = {
      doors = {
        A = { "ug_secret", "B" },
        B = { "cold_2", "A" },
      },
      gives = {
        ["ent:9"] = { flags = { "ch_cold_high" }, req = {  }, kind = "chest" },
        ["ent:b"] = { flags = { "brazier_hearth" }, req = {  }, kind = "brazier" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:9", reqs = { { "cryocoils", "driftvanes" }, { "cryocoils", "sparkjump" } } },
        { from = "door:A", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:9", reqs = { { "sparkjump" }, { "cryocoils", "driftvanes" } } },
        { from = "door:B", to = "ent:b", reqs = { {  } } },
      },
    },
    ["cold_2"] = {
      doors = {
        A = { "cold_1", "B" },
        B = { "cold_3", "A" },
        E = { "cold_secret", "A" },
      },
      gives = {
        ["ent:b"] = { flags = { "brazier_c2a" }, req = {  }, kind = "brazier" },
        ["ent:r"] = { flags = { "brazier_c2b" }, req = {  }, kind = "brazier" },
        ["ent:t"] = { flags = { "tp_coldstore" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "door:E", reqs = { { "cryocoils", "driftvanes" }, { "cryocoils", "sparkjump" } } },
        { from = "door:A", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:r", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:t", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:E", reqs = { { "cryocoils", "driftvanes" }, { "cryocoils", "sparkjump" } } },
        { from = "door:B", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:r", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:t", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "door:E", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "ent:r", reqs = { { "cryocoils" } } },
        { from = "door:E", to = "ent:t", reqs = { { "cryocoils" } } },
      },
    },
    ["cold_3"] = {
      doors = {
        A = { "cold_2", "B" },
        B = { "cold_4", "A" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_cold" }, req = {  }, kind = "capsule" },
        ["ent:b"] = { flags = { "brazier_c3a" }, req = {  }, kind = "brazier" },
        ["ent:r"] = { flags = { "brazier_c3b" }, req = {  }, kind = "brazier" },
        ["ent:w"] = { flags = { "thaw_cold3" }, req = {  }, kind = "thawplate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "door:B", reqs = { { "cryocoils", "thaw_cold3" } } },
        { from = "door:A", to = "ent:5", reqs = { { "cryocoils", "thaw_cold3" } } },
        { from = "door:A", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:r", reqs = { { "cryocoils", "thaw_cold3" } } },
        { from = "door:A", to = "ent:w", reqs = { { "cryocoils", "sparkjump" }, { "cryocoils", "driftvanes", "thaw_cold3" } } },
        { from = "door:B", to = "door:A", reqs = { { "cryocoils", "thaw_cold3" } } },
        { from = "door:B", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:5", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:b", reqs = { { "cryocoils", "thaw_cold3" } } },
        { from = "door:B", to = "ent:r", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:w", reqs = { { "cryocoils", "driftvanes", "thaw_cold3" }, { "cryocoils", "sparkjump", "thaw_cold3" } } },
      },
    },
    ["cold_4"] = {
      doors = {
        A = { "cold_3", "B" },
        B = { "cold_5", "A" },
      },
      gives = {
        ["ent:b"] = { flags = { "brazier_c4a" }, req = {  }, kind = "brazier" },
        ["ent:r"] = { flags = { "brazier_c4b" }, req = {  }, kind = "brazier" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:b", reqs = { {  } } },
        { from = "door:A", to = "ent:r", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:b", reqs = { {  } } },
        { from = "door:B", to = "ent:r", reqs = { {  } } },
      },
    },
    ["cold_5"] = {
      doors = {
        A = { "cold_4", "B" },
        B = { "cold_boss", "A" },
      },
      gives = {
        ["ent:T"] = { flags = { "tank_cold" }, req = {  }, kind = "tank" },
        ["ent:b"] = { flags = { "brazier_c5a" }, req = {  }, kind = "brazier" },
        ["ent:r"] = { flags = { "brazier_c5b" }, req = {  }, kind = "brazier" },
        ["ent:w"] = { flags = { "thaw_cold5" }, req = {  }, kind = "thawplate" },
        ["gate:cradle_found"] = { flags = { "cradle_found" }, req = { "brazier_c5a", "brazier_c5b" }, kind = "braziergate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "door:B", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
        { from = "door:A", to = "ent:T", reqs = { { "cryocoils", "thaw_cold5" } } },
        { from = "door:A", to = "ent:b", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:r", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:w", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "gate:cradle_found", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "door:A", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
        { from = "door:B", to = "door:B", reqs = { { "cryocoils" } } },
        { from = "door:B", to = "ent:T", reqs = { { "cradle_found", "cryocoils" } } },
        { from = "door:B", to = "ent:b", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
        { from = "door:B", to = "ent:r", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
        { from = "door:B", to = "ent:w", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
        { from = "door:B", to = "gate:cradle_found", reqs = { { "cradle_found", "cryocoils", "thaw_cold5" } } },
      },
    },
    ["cold_boss"] = {
      doors = {
        A = { "cold_5", "B" },
        B = { "cradle_1", "A" },
        C = { "deep_stair_2", "E" },
      },
      gives = {
        ["ent:a"] = { flags = { "boss_archivist", "weapon_magnetmortar" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "boss_archivist" } } },
        { from = "door:A", to = "door:C", reqs = { { "boss_archivist" } } },
        { from = "door:A", to = "ent:a", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "boss_archivist" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { { "boss_archivist" } } },
        { from = "door:B", to = "ent:a", reqs = { { "boss_archivist" } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { { "boss_archivist" } } },
        { from = "door:C", to = "door:C", reqs = { { "boss_archivist" } } },
        { from = "door:C", to = "ent:a", reqs = { {  } } },
      },
    },
    ["cold_secret"] = {
      doors = {
        A = { "cold_2", "E" },
      },
      gives = {
        ["ent:3"] = { flags = { "ch_cold1" }, req = {  }, kind = "chest" },
        ["ent:4"] = { flags = { "ch_cold2" }, req = {  }, kind = "chest" },
        ["ent:b"] = { flags = { "brazier_csa" }, req = {  }, kind = "brazier" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:3", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:4", reqs = { { "cryocoils" } } },
        { from = "door:A", to = "ent:b", reqs = { { "cryocoils" } } },
      },
    },
    ["core_1"] = {
      doors = {
        A = { "deep_stair_2", "C" },
        B = { "core_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "coredoor" } } },
        { from = "door:B", to = "door:A", reqs = { { "coredoor" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["core_2"] = {
      doors = {
        A = { "core_1", "B" },
        B = { "core_3", "A" },
        D = { "core_boss", "B" },
      },
      gives = {
        ["ent:k"] = { flags = { "linkcore_c2" }, req = { "linkblast" }, kind = "linkcore" },
        ["ent:t"] = { flags = { "tp_core" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "linkcore_c2" } } },
        { from = "door:A", to = "door:D", reqs = { { "linkcore_c2" } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "linkcore_c2" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "ent:k", reqs = { { "linkcore_c2" } } },
        { from = "door:B", to = "ent:t", reqs = { { "linkcore_c2" } } },
        { from = "door:D", to = "door:A", reqs = { { "linkcore_c2" } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:k", reqs = { { "linkcore_c2" } } },
        { from = "door:D", to = "ent:t", reqs = { { "linkcore_c2" } } },
      },
    },
    ["core_3"] = {
      doors = {
        A = { "core_2", "B" },
        B = { "core_4", "A" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_core" }, req = {  }, kind = "capsule" },
        ["ent:x"] = { flags = { "plate_core3a" }, req = {  }, kind = "plate" },
        ["ent:y"] = { flags = { "plate_core3b" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "plate_core3a", "plate_core3b" } } },
        { from = "door:A", to = "ent:5", reqs = { { "plate_core3a", "plate_core3b" } } },
        { from = "door:A", to = "ent:x", reqs = { {  } } },
        { from = "door:A", to = "ent:y", reqs = { { "plate_core3a" } } },
        { from = "door:B", to = "door:A", reqs = { { "plate_core3a", "plate_core3b" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:5", reqs = { {  } } },
        { from = "door:B", to = "ent:x", reqs = { { "plate_core3a", "plate_core3b" } } },
        { from = "door:B", to = "ent:y", reqs = { { "plate_core3b" } } },
      },
    },
    ["core_4"] = {
      doors = {
        A = { "core_3", "B" },
        B = { "core_boss", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["core_boss"] = {
      doors = {
        A = { "core_4", "B" },
        B = { "core_2", "D" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_motherengine", "ending" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["cradle_1"] = {
      doors = {
        A = { "cold_boss", "B" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
      },
    },
    ["crys_1"] = {
      doors = {
        A = { "deep_stair_1", "D" },
        B = { "crys_2", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "arcplate4", "ch_ap4" }, req = {  }, kind = "chest" },
        ["ent:o"] = { flags = { "crys_bus1" }, req = {  }, kind = "node" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "boss_tideengine", "crys_bus1" } } },
        { from = "door:A", to = "ent:4", reqs = { { "boss_tideengine" } } },
        { from = "door:A", to = "ent:o", reqs = { { "boss_tideengine", "driftvanes" } } },
        { from = "door:B", to = "door:A", reqs = { { "crys_bus1", "grapple" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { { "crys_bus1" } } },
        { from = "door:B", to = "ent:o", reqs = { { "crys_bus1", "driftvanes" } } },
      },
    },
    ["crys_2"] = {
      doors = {
        A = { "crys_1", "B" },
        B = { "crys_3", "A" },
        E = { "crys_secret", "A" },
      },
      gives = {
        ["ent:o"] = { flags = { "crys_bus2" }, req = {  }, kind = "node" },
        ["ent:t"] = { flags = { "tp_crystal" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "crys_bus2" } } },
        { from = "door:A", to = "door:E", reqs = { { "crys_bus2" } } },
        { from = "door:A", to = "ent:o", reqs = { { "crys_bus2" }, { "sparkjump" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "crys_bus2" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:E", reqs = { {  } } },
        { from = "door:B", to = "ent:o", reqs = { { "crys_bus2" } } },
        { from = "door:B", to = "ent:t", reqs = { { "crys_bus2" } } },
        { from = "door:E", to = "door:A", reqs = { { "crys_bus2" } } },
        { from = "door:E", to = "door:B", reqs = { {  } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:o", reqs = { { "crys_bus2" } } },
        { from = "door:E", to = "ent:t", reqs = { { "crys_bus2" } } },
      },
    },
    ["crys_3"] = {
      doors = {
        A = { "crys_2", "B" },
        B = { "crys_4", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_crys" }, req = {  }, kind = "tank" },
        ["ent:o"] = { flags = { "crys_bus3" }, req = { "bulwark" }, kind = "node" },
        ["ent:x"] = { flags = { "bridge_c3" }, req = {  }, kind = "plate" },
        ["ent:y"] = { flags = { "bridge_c3" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "bridge_c3", "crys_bus3" } } },
        { from = "door:A", to = "ent:4", reqs = { { "bridge_c3" } } },
        { from = "door:A", to = "ent:o", reqs = { { "bridge_c3" } } },
        { from = "door:A", to = "ent:x", reqs = { {  } } },
        { from = "door:A", to = "ent:y", reqs = { { "bridge_c3" } } },
        { from = "door:B", to = "door:A", reqs = { { "bridge_c3", "crys_bus3" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { { "crys_bus3" } } },
        { from = "door:B", to = "ent:o", reqs = { { "crys_bus3" } } },
        { from = "door:B", to = "ent:x", reqs = { { "bridge_c3", "crys_bus3" } } },
        { from = "door:B", to = "ent:y", reqs = { { "crys_bus3" } } },
      },
    },
    ["crys_4"] = {
      doors = {
        A = { "crys_3", "B" },
        B = { "crys_5", "A" },
      },
      gives = {
        ["ent:9"] = { flags = { "chest_lance", "weapon_arclance" }, req = {  }, kind = "chest" },
        ["ent:o"] = { flags = { "crys_bus4" }, req = {  }, kind = "node" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "crys_bus4" } } },
        { from = "door:A", to = "ent:9", reqs = { {  } } },
        { from = "door:A", to = "ent:o", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:9", reqs = { {  } } },
        { from = "door:B", to = "ent:o", reqs = { {  } } },
      },
    },
    ["crys_5"] = {
      doors = {
        A = { "crys_4", "B" },
        B = { "crys_boss", "A" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_crys" }, req = {  }, kind = "capsule" },
        ["ent:8"] = { flags = { "chest_crys5b" }, req = {  }, kind = "chest" },
        ["ent:o"] = { flags = { "crys_bus5" }, req = { "bulwark" }, kind = "node" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "crys_bus5", "driftvanes" } } },
        { from = "door:A", to = "ent:5", reqs = { { "sparkjump" }, { "crys_bus5", "driftvanes" } } },
        { from = "door:A", to = "ent:8", reqs = { { "crys_bus5" } } },
        { from = "door:A", to = "ent:o", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "crys_bus5", "driftvanes" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:5", reqs = { { "crys_bus5", "driftvanes" } } },
        { from = "door:B", to = "ent:8", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "ent:o", reqs = { { "crys_bus5", "driftvanes" } } },
      },
    },
    ["crys_boss"] = {
      doors = {
        A = { "crys_5", "B" },
        B = { "deep_stair_1", "F" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_prismtyrant", "corekey2" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "boss_prismtyrant" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { { "boss_prismtyrant" } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["crys_secret"] = {
      doors = {
        A = { "crys_2", "E" },
      },
      gives = {
        ["ent:1"] = { flags = { "chest_crys1" }, req = {  }, kind = "chest" },
        ["ent:2"] = { flags = { "chest_crys2" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { {  } } },
        { from = "door:A", to = "ent:2", reqs = { {  } } },
      },
    },
    ["deep_stair_1"] = {
      doors = {
        A = { "stair_junction", "C" },
        B = { "deep_stair_2", "A" },
        C = { "furn_1", "A" },
        D = { "crys_1", "A" },
        E = { "furn_boss", "B" },
        F = { "crys_boss", "B" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { {  } } },
        { from = "door:A", to = "door:F", reqs = { { "boss_prismtyrant" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "door:E", reqs = { {  } } },
        { from = "door:B", to = "door:F", reqs = { { "boss_prismtyrant" } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { {  } } },
        { from = "door:C", to = "door:E", reqs = { {  } } },
        { from = "door:C", to = "door:F", reqs = { { "boss_prismtyrant" } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:E", reqs = { {  } } },
        { from = "door:D", to = "door:F", reqs = { { "boss_prismtyrant" } } },
        { from = "door:E", to = "door:A", reqs = { { "boss_crucible" } } },
        { from = "door:E", to = "door:B", reqs = { { "boss_crucible" } } },
        { from = "door:E", to = "door:C", reqs = { { "boss_crucible" } } },
        { from = "door:E", to = "door:D", reqs = { { "boss_crucible" } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "door:F", reqs = { { "boss_crucible", "boss_prismtyrant" } } },
        { from = "door:F", to = "door:A", reqs = { { "boss_prismtyrant" } } },
        { from = "door:F", to = "door:B", reqs = { { "boss_prismtyrant" } } },
        { from = "door:F", to = "door:C", reqs = { { "boss_prismtyrant" } } },
        { from = "door:F", to = "door:D", reqs = { { "boss_prismtyrant" } } },
        { from = "door:F", to = "door:E", reqs = { { "boss_prismtyrant" } } },
        { from = "door:F", to = "door:F", reqs = { {  } } },
      },
    },
    ["deep_stair_2"] = {
      doors = {
        A = { "deep_stair_1", "B" },
        C = { "core_1", "A" },
        D = { "flood_boss", "F" },
        E = { "cold_boss", "C" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { { "boss_tideengine" } } },
        { from = "door:A", to = "door:E", reqs = { { "boss_archivist" } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { { "boss_tideengine" } } },
        { from = "door:C", to = "door:E", reqs = { { "boss_archivist" } } },
        { from = "door:D", to = "door:A", reqs = { { "boss_tideengine" } } },
        { from = "door:D", to = "door:C", reqs = { { "boss_tideengine" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:E", reqs = { { "boss_archivist", "boss_tideengine" } } },
        { from = "door:E", to = "door:A", reqs = { { "boss_archivist" } } },
        { from = "door:E", to = "door:C", reqs = { { "boss_archivist" } } },
        { from = "door:E", to = "door:D", reqs = { { "boss_archivist", "boss_tideengine" } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
      },
    },
    ["flood_1"] = {
      doors = {
        A = { "moss_boss", "B" },
        B = { "flood_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["flood_2"] = {
      doors = {
        A = { "flood_1", "B" },
        B = { "flood_3", "A" },
        D = { "flood_deep1", "A" },
      },
      gives = {
        ["ent:8"] = { flags = { "chest_flood2b" }, req = {  }, kind = "chest" },
        ["ent:9"] = { flags = { "chest_scatter", "weapon_scatterhex" }, req = {  }, kind = "chest" },
        ["ent:T"] = { flags = { "tank_flood" }, req = {  }, kind = "tank" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { { "hydroseals" } } },
        { from = "door:A", to = "ent:8", reqs = { {  } } },
        { from = "door:A", to = "ent:9", reqs = { {  } } },
        { from = "door:A", to = "ent:T", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { { "hydroseals" } } },
        { from = "door:B", to = "ent:8", reqs = { {  } } },
        { from = "door:B", to = "ent:9", reqs = { {  } } },
        { from = "door:B", to = "ent:T", reqs = { { "driftvanes" } } },
        { from = "door:D", to = "door:A", reqs = { { "hydroseals" } } },
        { from = "door:D", to = "door:B", reqs = { { "hydroseals" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:8", reqs = { { "hydroseals" } } },
        { from = "door:D", to = "ent:9", reqs = { { "hydroseals" } } },
        { from = "door:D", to = "ent:T", reqs = { { "driftvanes", "hydroseals" } } },
      },
    },
    ["flood_3"] = {
      doors = {
        A = { "flood_2", "B" },
        B = { "flood_warden", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["flood_4"] = {
      doors = {
        A = { "flood_warden", "B" },
        B = { "flood_5", "A" },
        C = { "flood_hub", "A" },
      },
      gives = {
        ["ent:2"] = { flags = { "brassa_hammer" }, req = {  }, kind = "chest" },
        ["ent:3"] = { flags = { "chest_grapple", "grapple" }, req = {  }, kind = "chest" },
        ["ent:4"] = { flags = { "arcplate2", "ch_ap2" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "ent:2", reqs = { {  } } },
        { from = "door:A", to = "ent:3", reqs = { {  } } },
        { from = "door:A", to = "ent:4", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { {  } } },
        { from = "door:B", to = "ent:2", reqs = { {  } } },
        { from = "door:B", to = "ent:3", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { {  } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "ent:2", reqs = { {  } } },
        { from = "door:C", to = "ent:3", reqs = { {  } } },
        { from = "door:C", to = "ent:4", reqs = { {  } } },
      },
    },
    ["flood_5"] = {
      doors = {
        A = { "flood_4", "B" },
        B = { "flood_boss", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_flood" }, req = {  }, kind = "tank" },
        ["ent:8"] = { flags = { "chest_flood5b" }, req = {  }, kind = "chest" },
        ["ent:x"] = { flags = { "plate_f5" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:4", reqs = { { "plate_f5" } } },
        { from = "door:A", to = "ent:8", reqs = { {  } } },
        { from = "door:A", to = "ent:x", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { { "plate_f5" } } },
        { from = "door:B", to = "ent:8", reqs = { {  } } },
        { from = "door:B", to = "ent:x", reqs = { {  } } },
      },
    },
    ["flood_boss"] = {
      doors = {
        A = { "flood_5", "B" },
        F = { "deep_stair_2", "D" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_tideengine", "resonator" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:F", reqs = { { "boss_tideengine" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:F", to = "door:A", reqs = { {  } } },
        { from = "door:F", to = "door:F", reqs = { { "boss_tideengine" } } },
        { from = "door:F", to = "ent:t", reqs = { {  } } },
      },
    },
    ["flood_deep1"] = {
      doors = {
        A = { "flood_2", "D" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_flood" }, req = {  }, kind = "capsule" },
        ["ent:7"] = { flags = { "chest_lumecore", "lumecore" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:5", reqs = { {  } } },
        { from = "door:A", to = "ent:7", reqs = { {  } } },
      },
    },
    ["flood_hub"] = {
      doors = {
        A = { "flood_4", "C" },
      },
      gives = {
        ["ent:t"] = { flags = { "tp_flooded" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
      },
    },
    ["flood_warden"] = {
      doors = {
        A = { "flood_3", "B" },
        B = { "flood_4", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_rustwarden", "hydroseals" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["furn_1"] = {
      doors = {
        A = { "deep_stair_1", "C" },
        B = { "furn_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "grapple" } } },
        { from = "door:B", to = "door:A", reqs = { { "grapple" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["furn_2"] = {
      doors = {
        A = { "furn_1", "B" },
        B = { "furn_3", "A" },
        C = { "furn_cache", "A" },
        D = { "scrap_1", "A" },
        E = { "scrap_boss", "E" },
      },
      gives = {
        ["ent:4"] = { flags = { "arcplate3", "ch_ap3" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { { "boss_vessel8" } } },
        { from = "door:A", to = "ent:4", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "door:E", reqs = { { "boss_vessel8" } } },
        { from = "door:B", to = "ent:4", reqs = { {  } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { {  } } },
        { from = "door:C", to = "door:E", reqs = { { "boss_vessel8" } } },
        { from = "door:C", to = "ent:4", reqs = { {  } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:E", reqs = { { "boss_vessel8" } } },
        { from = "door:D", to = "ent:4", reqs = { {  } } },
        { from = "door:E", to = "door:A", reqs = { { "boss_vessel8" } } },
        { from = "door:E", to = "door:B", reqs = { { "boss_vessel8" } } },
        { from = "door:E", to = "door:C", reqs = { { "boss_vessel8" } } },
        { from = "door:E", to = "door:D", reqs = { { "boss_vessel8" } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:4", reqs = { { "boss_vessel8" } } },
      },
    },
    ["furn_3"] = {
      doors = {
        A = { "furn_2", "B" },
        B = { "furn_golem", "A" },
      },
      gives = {
        ["ent:8"] = { flags = { "chest_furn3b" }, req = {  }, kind = "chest" },
        ["ent:t"] = { flags = { "tp_furnace" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:8", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:8", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["furn_4"] = {
      doors = {
        A = { "furn_golem", "B" },
        B = { "furn_5", "A" },
      },
      gives = {
        ["ent:3"] = { flags = { "chest_heatplate", "heatplating" }, req = {  }, kind = "chest" },
        ["ent:9"] = { flags = { "ch_furn_high" }, req = {  }, kind = "chest" },
        ["ent:M"] = { flags = { "furnvault" }, req = {  }, kind = "machine" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "furnvault", "heatplating" } } },
        { from = "door:A", to = "ent:3", reqs = { { "furnvault" } } },
        { from = "door:A", to = "ent:9", reqs = { { "furnvault" } } },
        { from = "door:A", to = "ent:M", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "heatplating" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:3", reqs = { { "heatplating" } } },
        { from = "door:B", to = "ent:9", reqs = { { "heatplating" } } },
        { from = "door:B", to = "ent:M", reqs = { { "heatplating" } } },
      },
    },
    ["furn_5"] = {
      doors = {
        A = { "furn_4", "B" },
        B = { "furn_6", "A" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_furn" }, req = {  }, kind = "capsule" },
        ["ent:q"] = { flags = { "ch_cryo", "cryocoils" }, req = {  }, kind = "chest" },
        ["ent:x"] = { flags = { "plate_furn5" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "heatplating" } } },
        { from = "door:A", to = "door:B", reqs = { { "heatplating" } } },
        { from = "door:A", to = "ent:5", reqs = { { "heatplating", "plate_furn5" } } },
        { from = "door:A", to = "ent:q", reqs = { { "driftvanes", "heatplating" }, { "heatplating", "sparkjump" } } },
        { from = "door:A", to = "ent:x", reqs = { { "heatplating" } } },
        { from = "door:B", to = "door:A", reqs = { { "heatplating" } } },
        { from = "door:B", to = "door:B", reqs = { { "heatplating" } } },
        { from = "door:B", to = "ent:5", reqs = { { "heatplating", "plate_furn5" } } },
        { from = "door:B", to = "ent:q", reqs = { { "driftvanes", "heatplating" }, { "heatplating", "sparkjump" } } },
        { from = "door:B", to = "ent:x", reqs = { { "heatplating" } } },
      },
    },
    ["furn_6"] = {
      doors = {
        A = { "furn_5", "B" },
        B = { "furn_boss", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_furn" }, req = {  }, kind = "tank" },
        ["ent:x"] = { flags = { "plate_furn6" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { { "heatplating" } } },
        { from = "door:A", to = "door:B", reqs = { { "heatplating" } } },
        { from = "door:A", to = "ent:4", reqs = { { "heatplating", "plate_furn6" } } },
        { from = "door:A", to = "ent:x", reqs = { { "heatplating" } } },
        { from = "door:B", to = "door:A", reqs = { { "heatplating" } } },
        { from = "door:B", to = "door:B", reqs = { { "heatplating" } } },
        { from = "door:B", to = "ent:4", reqs = { { "heatplating", "plate_furn6" } } },
        { from = "door:B", to = "ent:x", reqs = { { "heatplating" } } },
      },
    },
    ["furn_boss"] = {
      doors = {
        A = { "furn_6", "B" },
        B = { "deep_stair_1", "E" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_crucible", "corekey1" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "boss_crucible" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { { "boss_crucible" } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["furn_cache"] = {
      doors = {
        A = { "furn_2", "C" },
      },
      gives = {
        ["ent:3"] = { flags = { "ch_fc1" }, req = {  }, kind = "chest" },
        ["ent:4"] = { flags = { "ch_fc2" }, req = {  }, kind = "chest" },
        ["ent:k"] = { flags = { "linkcore_fc" }, req = { "linkblast" }, kind = "linkcore" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:3", reqs = { { "linkcore_fc" } } },
        { from = "door:A", to = "ent:4", reqs = { { "linkcore_fc" } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
      },
    },
    ["furn_golem"] = {
      doors = {
        A = { "furn_3", "B" },
        B = { "furn_4", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_slaggolem" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["gal_1"] = {
      doors = {
        A = { "sky_2", "C" },
        B = { "gal_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "driftvanes" }, { "sparkjump" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["gal_2"] = {
      doors = {
        A = { "gal_1", "B" },
        B = { "gal_3", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["gal_3"] = {
      doors = {
        A = { "gal_2", "B" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_gallery" }, req = {  }, kind = "tank" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:4", reqs = { {  } } },
      },
    },
    ["moss_1"] = {
      doors = {
        A = { "stair_junction", "B" },
        B = { "moss_2", "A" },
        E = { "moss_secret", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "door:A", reqs = { {  } } },
        { from = "door:E", to = "door:B", reqs = { {  } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
      },
    },
    ["moss_2"] = {
      doors = {
        A = { "moss_1", "B" },
        B = { "moss_3", "B" },
        D = { "moss_well", "A" },
      },
      gives = {
        ["ent:3"] = { flags = { "chest_moss2" }, req = {  }, kind = "chest" },
        ["ent:4"] = { flags = { "arcplate1", "ch_ap1" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "ent:3", reqs = { { "sparkjump" } } },
        { from = "door:A", to = "ent:4", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "ent:3", reqs = { { "sparkjump" } } },
        { from = "door:B", to = "ent:4", reqs = { {  } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:3", reqs = { { "sparkjump" } } },
        { from = "door:D", to = "ent:4", reqs = { {  } } },
      },
    },
    ["moss_3"] = {
      doors = {
        A = { "moss_4", "A" },
        B = { "moss_2", "B" },
        C = { "sky_1", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { { "sparkjump" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { { "sparkjump" } } },
        { from = "door:C", to = "door:A", reqs = { { "sparkjump" } } },
        { from = "door:C", to = "door:B", reqs = { { "sparkjump" } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
      },
    },
    ["moss_4"] = {
      doors = {
        A = { "moss_3", "A" },
        B = { "moss_5", "A" },
      },
      gives = {
        ["ent:3"] = { flags = { "chest_sparkjump", "sparkjump" }, req = {  }, kind = "chest" },
        ["ent:x"] = { flags = { "plate_m4a" }, req = {  }, kind = "plate" },
        ["ent:y"] = { flags = { "plate_m4b" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "sparkjump" }, { "plate_m4a", "plate_m4b" } } },
        { from = "door:A", to = "ent:3", reqs = { { "plate_m4a" }, { "plate_m4b", "sparkjump" } } },
        { from = "door:A", to = "ent:x", reqs = { {  } } },
        { from = "door:A", to = "ent:y", reqs = { { "sparkjump" }, { "plate_m4a", "plate_m4b" } } },
        { from = "door:B", to = "door:A", reqs = { { "sparkjump" }, { "plate_m4a", "plate_m4b" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:3", reqs = { { "plate_m4b" }, { "plate_m4a", "sparkjump" } } },
        { from = "door:B", to = "ent:x", reqs = { { "sparkjump" }, { "plate_m4a", "plate_m4b" } } },
        { from = "door:B", to = "ent:y", reqs = { {  } } },
      },
    },
    ["moss_5"] = {
      doors = {
        A = { "moss_4", "B" },
        B = { "moss_boss", "A" },
        E = { "moss_grotto", "A" },
      },
      gives = {
        ["ent:1"] = { flags = { "chest_moss5" }, req = {  }, kind = "chest" },
        ["ent:9"] = { flags = { "ch_moss_high" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { { "sparkjump" } } },
        { from = "door:A", to = "ent:9", reqs = { { "sparkjump" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:E", reqs = { {  } } },
        { from = "door:B", to = "ent:1", reqs = { { "sparkjump" } } },
        { from = "door:B", to = "ent:9", reqs = { { "sparkjump" } } },
        { from = "door:E", to = "door:A", reqs = { {  } } },
        { from = "door:E", to = "door:B", reqs = { {  } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:1", reqs = { { "sparkjump" } } },
        { from = "door:E", to = "ent:9", reqs = { { "sparkjump" } } },
      },
    },
    ["moss_boss"] = {
      doors = {
        A = { "moss_5", "B" },
        B = { "flood_1", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_bramblemaw" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
      },
    },
    ["moss_grotto"] = {
      doors = {
        A = { "moss_5", "E" },
      },
      gives = {
        ["ent:1"] = { flags = { "chest_grotto" }, req = {  }, kind = "chest" },
        ["ent:2"] = { flags = { "chest_moldcap", "moldcap" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { {  } } },
        { from = "door:A", to = "ent:2", reqs = { {  } } },
      },
    },
    ["moss_secret"] = {
      doors = {
        A = { "moss_1", "E" },
      },
      gives = {
        ["ent:1"] = { flags = { "cap_moss" }, req = {  }, kind = "capsule" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { { "driftvanes" }, { "sparkjump" } } },
      },
    },
    ["moss_well"] = {
      doors = {
        A = { "moss_2", "D" },
        D = { "ug_1", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_1"] = {
      doors = {
        A = { "furn_2", "D" },
        B = { "scrap_2", "C" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["scrap_2"] = {
      doors = {
        C = { "scrap_1", "B" },
        D = { "scrap_3", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_3"] = {
      doors = {
        B = { "scrap_4", "A" },
        D = { "scrap_2", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_4"] = {
      doors = {
        A = { "scrap_3", "B" },
        C = { "scrap_secret", "A" },
        D = { "scrap_bay", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_5"] = {
      doors = {
        C = { "scrap_bay", "B" },
        D = { "scrap_6", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_6"] = {
      doors = {
        B = { "scrap_boss", "A" },
        D = { "scrap_5", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { { "bulwark" } } },
        { from = "door:D", to = "door:B", reqs = { { "bulwark" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["scrap_bay"] = {
      doors = {
        B = { "scrap_5", "C" },
        D = { "scrap_4", "D" },
      },
      gives = {
        ["ent:b"] = { flags = { "bulwark", "ch_bulwark" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "ent:b", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:b", reqs = { {  } } },
      },
    },
    ["scrap_boss"] = {
      doors = {
        A = { "scrap_6", "B" },
        E = { "furn_2", "E" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_vessel8", "cinderram" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:E", reqs = { { "boss_vessel8" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:E", to = "door:A", reqs = { { "boss_vessel8" } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:t", reqs = { { "boss_vessel8" } } },
      },
    },
    ["scrap_secret"] = {
      doors = {
        A = { "scrap_4", "C" },
      },
      gives = {
        ["ent:9"] = { flags = { "ch_scrap1" }, req = {  }, kind = "chest" },
        ["ent:k"] = { flags = { "cap_scrap" }, req = {  }, kind = "capsule" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:9", reqs = { {  } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
      },
    },
    ["sky_1"] = {
      doors = {
        A = { "moss_3", "C" },
        B = { "sky_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["sky_2"] = {
      doors = {
        A = { "sky_1", "B" },
        B = { "sky_3", "A" },
        C = { "gal_1", "A" },
        E = { "sky_secret", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "tp_skyroot" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { { "driftvanes" } } },
        { from = "door:A", to = "door:E", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:E", reqs = { {  } } },
        { from = "door:B", to = "ent:t", reqs = { {  } } },
        { from = "door:C", to = "door:A", reqs = { { "driftvanes" } } },
        { from = "door:C", to = "door:B", reqs = { { "driftvanes" } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "door:E", reqs = { { "driftvanes" } } },
        { from = "door:C", to = "ent:t", reqs = { { "driftvanes" } } },
        { from = "door:E", to = "door:A", reqs = { {  } } },
        { from = "door:E", to = "door:B", reqs = { {  } } },
        { from = "door:E", to = "door:C", reqs = { { "driftvanes" } } },
        { from = "door:E", to = "door:E", reqs = { {  } } },
        { from = "door:E", to = "ent:t", reqs = { {  } } },
      },
    },
    ["sky_3"] = {
      doors = {
        A = { "sky_2", "B" },
        B = { "sky_4", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_sky" }, req = {  }, kind = "tank" },
        ["ent:x"] = { flags = { "plate_s3" }, req = {  }, kind = "plate" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "driftvanes" }, { "grapple" } } },
        { from = "door:A", to = "ent:4", reqs = { { "driftvanes", "plate_s3" }, { "grapple", "plate_s3" } } },
        { from = "door:A", to = "ent:x", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "driftvanes" }, { "grapple" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { { "plate_s3" } } },
        { from = "door:B", to = "ent:x", reqs = { { "driftvanes" }, { "grapple" } } },
      },
    },
    ["sky_4"] = {
      doors = {
        A = { "sky_3", "B" },
        B = { "sky_boss", "A" },
        C = { "sky_nest", "A" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_sky" }, req = {  }, kind = "capsule" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { {  } } },
        { from = "door:A", to = "ent:5", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { {  } } },
        { from = "door:B", to = "ent:5", reqs = { {  } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { {  } } },
        { from = "door:C", to = "ent:5", reqs = { {  } } },
      },
    },
    ["sky_boss"] = {
      doors = {
        A = { "sky_4", "B" },
        B = { "upper_stair", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_aeriesentinel", "corekey3" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "boss_aeriesentinel", "driftvanes" } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:B", reqs = { { "boss_aeriesentinel" } } },
        { from = "door:B", to = "ent:t", reqs = { { "driftvanes" } } },
      },
    },
    ["sky_nest"] = {
      doors = {
        A = { "sky_4", "C" },
      },
      gives = {
        ["ent:3"] = { flags = { "chest_driftvanes", "driftvanes" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:3", reqs = { {  } } },
      },
    },
    ["sky_secret"] = {
      doors = {
        A = { "sky_2", "E" },
      },
      gives = {
        ["ent:1"] = { flags = { "chest_sky1" }, req = {  }, kind = "chest" },
        ["ent:2"] = { flags = { "chest_sky2" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { {  } } },
        { from = "door:A", to = "ent:2", reqs = { {  } } },
      },
    },
    ["stair_junction"] = {
      doors = {
        A = { "camp_main", "B" },
        B = { "moss_1", "A" },
        C = { "deep_stair_1", "A" },
        D = { "upper_stair", "B" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:C", reqs = { { "boss_bramblemaw" } } },
        { from = "door:A", to = "door:D", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:C", reqs = { { "boss_bramblemaw" } } },
        { from = "door:B", to = "door:D", reqs = { { "driftvanes" } } },
        { from = "door:C", to = "door:A", reqs = { {  } } },
        { from = "door:C", to = "door:B", reqs = { {  } } },
        { from = "door:C", to = "door:C", reqs = { { "boss_bramblemaw" } } },
        { from = "door:C", to = "door:D", reqs = { { "driftvanes" } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:C", reqs = { { "boss_bramblemaw" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
      },
    },
    ["ug_1"] = {
      doors = {
        A = { "moss_well", "D" },
        B = { "ug_2", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["ug_2"] = {
      doors = {
        A = { "ug_1", "B" },
        B = { "ug_3", "A" },
      },
      gives = {
        ["ent:k"] = { flags = { "glowmite1" }, req = {  }, kind = "mitehusk" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:k", reqs = { {  } } },
      },
    },
    ["ug_3"] = {
      doors = {
        A = { "ug_2", "B" },
        B = { "ug_4", "A" },
        D = { "ug_rescue", "A" },
      },
      gives = {
        ["ent:t"] = { flags = { "tp_undergrove" }, req = {  }, kind = "teleporter" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { { "lumecore" } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "lumecore" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { { "lumecore" } } },
        { from = "door:B", to = "ent:t", reqs = { { "lumecore" } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { { "lumecore" } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:t", reqs = { {  } } },
      },
    },
    ["ug_4"] = {
      doors = {
        A = { "ug_3", "B" },
        B = { "ug_5", "A" },
      },
      gives = {
        ["ent:k"] = { flags = { "glowmite2" }, req = {  }, kind = "mitehusk" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:k", reqs = { { "driftvanes" }, { "sparkjump" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:k", reqs = { { "driftvanes" }, { "sparkjump" } } },
      },
    },
    ["ug_5"] = {
      doors = {
        A = { "ug_4", "B" },
        B = { "ug_6", "A" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
    ["ug_6"] = {
      doors = {
        A = { "ug_5", "B" },
        B = { "ug_7", "A" },
        D = { "ug_secret", "A" },
      },
      gives = {
        ["ent:4"] = { flags = { "tank_ug" }, req = {  }, kind = "tank" },
        ["ent:k"] = { flags = { "glowmite3" }, req = {  }, kind = "mitehusk" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "door:D", reqs = { {  } } },
        { from = "door:A", to = "ent:4", reqs = { {  } } },
        { from = "door:A", to = "ent:k", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:D", reqs = { {  } } },
        { from = "door:B", to = "ent:4", reqs = { {  } } },
        { from = "door:B", to = "ent:k", reqs = { {  } } },
        { from = "door:D", to = "door:A", reqs = { {  } } },
        { from = "door:D", to = "door:B", reqs = { {  } } },
        { from = "door:D", to = "door:D", reqs = { {  } } },
        { from = "door:D", to = "ent:4", reqs = { {  } } },
        { from = "door:D", to = "ent:k", reqs = { {  } } },
      },
    },
    ["ug_7"] = {
      doors = {
        A = { "ug_6", "B" },
        B = { "ug_boss", "A" },
      },
      gives = {
        ["ent:7"] = { flags = { "chest_ferrocoil", "ferrocoil" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:7", reqs = { { "sparkjump" } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:7", reqs = { { "sparkjump" } } },
      },
    },
    ["ug_boss"] = {
      doors = {
        A = { "ug_7", "B" },
      },
      gives = {
        ["ent:t"] = { flags = { "boss_mycelchoir", "weapon_pulsebloom" }, req = {  }, kind = "boss" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:t", reqs = { {  } } },
      },
    },
    ["ug_rescue"] = {
      doors = {
        A = { "ug_3", "D" },
      },
      gives = {
        ["ent:5"] = { flags = { "cap_ug" }, req = {  }, kind = "capsule" },
        ["ent:e"] = { flags = { "ferro_rescued" }, req = {  }, kind = "npc" },
        ["ent:e*2"] = { flags = { "ferro_stage1" }, req = { "ferro_rescued", "ferrocoil" }, kind = "npc" },
        ["ent:o"] = { flags = { "mote_done" }, req = { "glowmite1", "glowmite2", "glowmite3" }, kind = "npc" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "ent:5", reqs = { { "mote_done" } } },
        { from = "door:A", to = "ent:e", reqs = { {  } } },
        { from = "door:A", to = "ent:e*2", reqs = { {  } } },
        { from = "door:A", to = "ent:o", reqs = { {  } } },
      },
    },
    ["ug_secret"] = {
      doors = {
        A = { "ug_6", "D" },
        B = { "cold_1", "A" },
      },
      gives = {
        ["ent:1"] = { flags = { "musicbox", "musicbox_chest" }, req = {  }, kind = "chest" },
        ["ent:8"] = { flags = { "chest_ugsec" }, req = {  }, kind = "chest" },
        ["ent:9"] = { flags = { "chest_ugsec2" }, req = {  }, kind = "chest" },
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:A", to = "ent:1", reqs = { {  } } },
        { from = "door:A", to = "ent:8", reqs = { {  } } },
        { from = "door:A", to = "ent:9", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { {  } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "ent:1", reqs = { {  } } },
        { from = "door:B", to = "ent:8", reqs = { {  } } },
        { from = "door:B", to = "ent:9", reqs = { {  } } },
      },
    },
    ["upper_stair"] = {
      doors = {
        A = { "sky_boss", "B" },
        B = { "stair_junction", "D" },
      },
      gives = {
      },
      edges = {
        { from = "door:A", to = "door:A", reqs = { {  } } },
        { from = "door:A", to = "door:B", reqs = { {  } } },
        { from = "door:B", to = "door:A", reqs = { { "driftvanes" } } },
        { from = "door:B", to = "door:B", reqs = { {  } } },
      },
    },
  },
}
