-- generated by scripts/gen_coldstore.py (v4.0 Phase B)
return {
  zone = "coldstore", music = "coldstore",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "ice", a = 0.06, a2 = 0.3, py = 0.05 },
    { kind = "column", x = -10, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 45, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 90, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 149, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 204, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 259, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 306, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 359, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 407, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 463, y = 109, w = 9, h = 163, col = "navy", a = 0.32, py = 0.26, step = 32, acc = "ice" },
    { kind = "column", x = 9, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 73, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 137, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 209, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 272, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 339, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 399, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "column", x = 466, y = 71, w = 9, h = 201, col = "navy", a = 0.18, py = 0.14, step = 44, acc = "ice" },
    { kind = "rail", x = -12, y = 87, w = 504, h = 4, col = "navy", a = 0.26, py = 0.26 },
    { kind = "rail", x = -12, y = 141, w = 504, h = 4, col = "navy", a = 0.26, py = 0.26 },
    { kind = "rail", x = -12, y = 195, w = 504, h = 4, col = "navy", a = 0.26, py = 0.26 },
    { kind = "shaft", x = 162, y = 0, w = 58, h = 223, col = "ice", a = 0.15, py = 0.16, skew = 13, ph = 5.03 },
    { kind = "shaft", x = 370, y = 0, w = 50, h = 223, col = "ice", a = 0.15, py = 0.16, skew = -9, ph = 6.15 },
    { kind = "hang", x = 166, y = 30, w = 2, h = 25, col = "ice", a = 0.34, py = 0.2, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 288, y = 79, w = 2, h = 13, col = "ice", a = 0.34, py = 0.2, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 24, y = 20, w = 2, h = 18, col = "ice", a = 0.34, py = 0.2, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 51, y = 79, w = 2, h = 26, col = "ice", a = 0.34, py = 0.2, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 292, y = 26, w = 2, h = 10, col = "ice", a = 0.34, py = 0.2, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 334, y = 83, w = 2, h = 16, col = "ice", a = 0.34, py = 0.2, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 225, y = 53, w = 2, h = 14, col = "ice", a = 0.34, py = 0.2, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 294, y = 74, w = 2, h = 23, col = "ice", a = 0.34, py = 0.2, lw = 2, sway = 0, rate = 0.1 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 220, y = 69, w = 2, h = 20, col = "ice", a = 0.61, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 226, y = 69, w = 2, h = 26, col = "ice", a = 0.79, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 232, y = 69, w = 2, h = 21, col = "ice", a = 0.81, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 238, y = 69, w = 2, h = 11, col = "ice", a = 0.62, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 299, y = 84, w = 2, h = 9, col = "ice", a = 0.71, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 302, y = 84, w = 2, h = 25, col = "ice", a = 0.61, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 305, y = 84, w = 2, h = 26, col = "ice", a = 0.7, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 308, y = 84, w = 2, h = 13, col = "ice", a = 0.58, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 128, y = 32, w = 2, h = 10, col = "ice", a = 0.65, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 134, y = 32, w = 2, h = 21, col = "ice", a = 0.7, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 136, y = 32, w = 2, h = 15, col = "ice", a = 0.59, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 140, y = 32, w = 2, h = 24, col = "ice", a = 0.78, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 143, y = 78, w = 2, h = 23, col = "ice", a = 0.71, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 147, y = 78, w = 2, h = 12, col = "ice", a = 0.61, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 153, y = 78, w = 2, h = 16, col = "ice", a = 0.57, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 155, y = 78, w = 2, h = 15, col = "ice", a = 0.66, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 381, y = 43, w = 2, h = 16, col = "ice", a = 0.8, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 385, y = 43, w = 2, h = 21, col = "ice", a = 0.74, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 400, y = 45, w = 2, h = 15, col = "ice", a = 0.67, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 405, y = 45, w = 2, h = 24, col = "ice", a = 0.78, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 412, y = 45, w = 2, h = 11, col = "ice", a = 0.76, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 412, y = 45, w = 2, h = 22, col = "ice", a = 0.82, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 375, y = 78, w = 2, h = 18, col = "ice", a = 0.66, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 380, y = 78, w = 2, h = 7, col = "ice", a = 0.74, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 283, y = 151, w = 2, h = 25, col = "ice", a = 0.61, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 288, y = 151, w = 2, h = 23, col = "ice", a = 0.79, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 289, y = 151, w = 2, h = 15, col = "ice", a = 0.66, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 198, y = 35, w = 2, h = 25, col = "ice", a = 0.59, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 203, y = 35, w = 2, h = 21, col = "ice", a = 0.64, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 210, y = 35, w = 2, h = 22, col = "ice", a = 0.68, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 207, y = 35, w = 2, h = 23, col = "ice", a = 0.59, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 140, y = 88, w = 2, h = 8, col = "ice", a = 0.64, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 145, y = 88, w = 2, h = 10, col = "ice", a = 0.66, lw = 3, sway = 0, rate = 0.1 },
    { kind = "hang", x = 146, y = 88, w = 2, h = 8, col = "ice", a = 0.72, lw = 2, sway = 0, rate = 0.1 },
    { kind = "hang", x = 359, y = 146, w = 1, h = 26, col = "water", a = 0.32, lw = 1, sway = 1, rate = 0.35, bob = true },
    { kind = "hang", x = 61, y = 89, w = 1, h = 24, col = "water", a = 0.35, lw = 1, sway = 1, rate = 0.26, bob = true },
    { kind = "hang", x = 162, y = 33, w = 1, h = 25, col = "water", a = 0.49, lw = 1, sway = 1, rate = 0.34, bob = true },
    { kind = "hang", x = 60, y = 76, w = 1, h = 37, col = "water", a = 0.43, lw = 1, sway = 1, rate = 0.19, bob = true },
    { kind = "hang", x = 408, y = 106, w = 1, h = 24, col = "water", a = 0.41, lw = 1, sway = 1, rate = 0.37, bob = true },
    { kind = "band", x = 57, y = 115, w = 33, h = 10, col = "ice", a = 0.37, a2 = 0.04 },
    { kind = "band", x = 177, y = 167, w = 58, h = 12, col = "ice", a = 0.35, a2 = 0.04 },
    { kind = "band", x = 415, y = 216, w = 42, h = 12, col = "ice", a = 0.25, a2 = 0.04 },
    { kind = "band", x = 131, y = 168, w = 28, h = 21, col = "ice", a = 0.3, a2 = 0.04 },
    { kind = "band", x = 218, y = 169, w = 34, h = 11, col = "ice", a = 0.38, a2 = 0.04 },
    { kind = "band", x = 67, y = 53, w = 30, h = 9, col = "ice", a = 0.32, a2 = 0.04 },
    { kind = "band", x = 103, y = 51, w = 35, h = 8, col = "ice", a = 0.35, a2 = 0.04 },
    { kind = "band", x = 234, y = 156, w = 67, h = 9, col = "ice", a = 0.3, a2 = 0.04 },
    { kind = "rect", x = 281, y = 218, w = 13, h = 3, col = "cream", a = 0.14 },
    { kind = "rect", x = 317, y = 212, w = 12, h = 3, col = "cream", a = 0.15 },
    { kind = "rect", x = 306, y = 147, w = 13, h = 3, col = "cream", a = 0.15 },
    { kind = "rect", x = 112, y = 80, w = 10, h = 2, col = "cream", a = 0.18 },
    { kind = "rect", x = 364, y = 200, w = 12, h = 2, col = "cream", a = 0.21 },
    { kind = "rect", x = 469, y = 158, w = 7, h = 3, col = "cream", a = 0.21 },
    { kind = "rect", x = 56, y = 37, w = 8, h = 2, col = "cream", a = 0.21 },
    { kind = "rect", x = 287, y = 79, w = 8, h = 2, col = "cream", a = 0.21 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "column", x = 81, y = 0, w = 13, h = 272, col = "black", a = 0.7, py = -0.14, step = 26, acc = "navy" },
    { kind = "column", x = 360, y = 0, w = 13, h = 272, col = "black", a = 0.7, py = -0.14, step = 26, acc = "navy" },
    { kind = "hang", x = 139, y = 0, w = 3, h = 51, col = "ice", a = 0.8, py = -0.16, lw = 4, sway = 0, rate = 0.1 },
    { kind = "hang", x = 229, y = 0, w = 3, h = 33, col = "ice", a = 0.8, py = -0.16, lw = 4, sway = 0, rate = 0.1 },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "ice", a = 0.22, a2 = 0.22, py = -0.05 },
    { kind = "band", x = 456, y = 0, w = 24, h = 272, col = "ice", a = 0.22, a2 = 0.22, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 43, col = { 0.60, 0.80, 1.00 }, r = 82, flicker = 1.2 },
    { x = 360, y = 43, col = { 0.60, 0.80, 1.00 }, r = 81, flicker = 1.11 },
  },
  mapPos = { x = 6, y = 0, w = 1, h = 1 },
  cold = true,
  map = [[
##############################
##############################
################......########
##.#.....##..#...........#####
##................#########.##
##..........v.....#########.##
##..................f..v....##
##.............========.....##
##.........y................##
##....========..............##
AA.......................##.##
AA.....................####.##
#######_..ccccccc....######=##
##...................######.##
##......=====........#########
#####..1.b....3...4..#########
#####__#_####^#^^^############
]],
  key = {
    ["y"] = "glowmite",
    ["b"] = "brazier:csa",
    ["3"] = "chest:ch_cold1:scrap:30",
    ["4"] = "chest:ch_cold2:bigshard:6",
    ["1"] = "sign:sign_coldsecret",
    ["f"] = "frostwisp",
  },
  links = {
    A = { "cold_2", "E" },
  },
}
