-- generated by scripts/gen_coldstore.py (v4.0 Phase B)
return {
  zone = "coldstore", music = "coldstore",
  arena = "archivist",
  -- the air is Coldstore air, and row 16 is the floor the ice eats
  cold = true,
  frostRow = 16,
  mapPos = { x = 16, y = 0, w = 3, h = 1 },
  map = [[
###############################################################
###############################################################
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##..........................................................###
##........................=========.........................###
##..........................................................###
##..........................................................###
##............=========...............=========.............###
AA...........................................................BB
AA.................b..........k..........e...................BB
##################################################....C...#####
####################################################..C..######
###############################################################
###############################################################
###############################################################
]],
  key = {
    -- THE FIRE IT KEPT. Lit from the moment the room loads, so the
    -- Threshold always has heat in it however you arrived -- the front
    -- door, the stair, or the Test Chamber, which drops you straight in
    -- and starts the fight. Waking it is what starts the fight.
    --
    -- The ARCHIVIST can still take it. Nothing else can. A fight whose
    -- whole argument is "I will put your lights out" cannot have one
    -- light it is not allowed to touch.
    --
    -- There is deliberately NO CHECKPOINT and NO SAVE in here. Dying to
    -- the boss has to send you back to the room before it, not onto its
    -- floor with the fight re-armed.
    ["k"] = "brazier:cb2:kept:archivist",
    -- The other two, further out. Extending the safe ground is
    -- something you do DURING the fight, carrying a spark, with no gun
    -- and no shield.
    ["b"] = "brazier:cb1",
    ["e"] = "brazier:cb3",
  },
  links = {
    C = { "deep_stair_2", "E", req = "boss_archivist" },
    A = { "cold_5", "B" },
    B = { "cradle_1", "A", req = "boss_archivist" },
  },
}
