-- generated by scripts/genrooms.py
return {
  zone = "core", music = "core",
  arena = "motherengine",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 1280, h = 352, col = "black", a = 0.42, a2 = 0.12, py = 0.05 },
    { kind = "rail", x = -12, y = 49, w = 1304, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 112, w = 1304, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 176, w = 1304, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 239, w = 1304, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 302, w = 1304, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "column", x = -10, y = 0, w = 15, h = 352, col = "black", a = 0.4, py = 0.22, step = 27, acc = "cyan" },
    { kind = "column", x = 40, y = 0, w = 25, h = 352, col = "black", a = 0.4, py = 0.27, step = 19, acc = "cyan" },
    { kind = "column", x = 112, y = 0, w = 23, h = 352, col = "black", a = 0.4, py = 0.25, step = 27, acc = "cyan" },
    { kind = "column", x = 162, y = 0, w = 28, h = 352, col = "black", a = 0.4, py = 0.28, step = 18, acc = "cyan" },
    { kind = "column", x = 219, y = 0, w = 30, h = 352, col = "black", a = 0.4, py = 0.29, step = 21, acc = "cyan" },
    { kind = "column", x = 283, y = 0, w = 25, h = 352, col = "black", a = 0.4, py = 0.28, step = 29, acc = "cyan" },
    { kind = "column", x = 341, y = 0, w = 25, h = 352, col = "black", a = 0.4, py = 0.17, step = 27, acc = "cyan" },
    { kind = "column", x = 420, y = 0, w = 22, h = 352, col = "black", a = 0.4, py = 0.17, step = 24, acc = "cyan" },
    { kind = "column", x = 500, y = 0, w = 17, h = 352, col = "black", a = 0.4, py = 0.2, step = 26, acc = "cyan" },
    { kind = "column", x = 572, y = 0, w = 27, h = 352, col = "black", a = 0.4, py = 0.24, step = 20, acc = "cyan" },
    { kind = "column", x = 665, y = 0, w = 17, h = 352, col = "black", a = 0.4, py = 0.22, step = 18, acc = "cyan" },
    { kind = "column", x = 754, y = 0, w = 26, h = 352, col = "black", a = 0.4, py = 0.18, step = 22, acc = "cyan" },
    { kind = "column", x = 843, y = 0, w = 22, h = 352, col = "black", a = 0.4, py = 0.19, step = 23, acc = "cyan" },
    { kind = "column", x = 920, y = 0, w = 16, h = 352, col = "black", a = 0.4, py = 0.25, step = 25, acc = "cyan" },
    { kind = "column", x = 998, y = 0, w = 20, h = 352, col = "black", a = 0.4, py = 0.3, step = 25, acc = "cyan" },
    { kind = "column", x = 1057, y = 0, w = 17, h = 352, col = "black", a = 0.4, py = 0.26, step = 30, acc = "cyan" },
    { kind = "column", x = 1135, y = 0, w = 29, h = 352, col = "black", a = 0.4, py = 0.26, step = 21, acc = "cyan" },
    { kind = "column", x = 1212, y = 0, w = 24, h = 352, col = "black", a = 0.4, py = 0.21, step = 29, acc = "cyan" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 579, y = 99, w = 20, h = 2, col = "cyan", a = 0.53 },
    { kind = "rect", x = 605, y = 130, w = 23, h = 2, col = "cyan", a = 0.28 },
    { kind = "rect", x = 293, y = 143, w = 20, h = 2, col = "cyan", a = 0.54 },
    { kind = "rect", x = 759, y = 138, w = 9, h = 2, col = "cyan", a = 0.54 },
    { kind = "rect", x = 50, y = 127, w = 14, h = 2, col = "cyan", a = 0.25 },
    { kind = "rect", x = 840, y = 80, w = 15, h = 2, col = "cyan", a = 0.48 },
    { kind = "rect", x = 270, y = 100, w = 20, h = 2, col = "cyan", a = 0.47 },
    { kind = "rect", x = 32, y = 147, w = 12, h = 2, col = "cyan", a = 0.46 },
    { kind = "rect", x = 604, y = 205, w = 20, h = 2, col = "cyan", a = 0.4 },
    { kind = "rect", x = 253, y = 250, w = 25, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 681, y = 217, w = 25, h = 2, col = "cyan", a = 0.3 },
    { kind = "rect", x = 333, y = 303, w = 16, h = 2, col = "cyan", a = 0.43 },
    { kind = "rect", x = 1227, y = 167, w = 13, h = 2, col = "cyan", a = 0.52 },
    { kind = "rect", x = 1244, y = 245, w = 16, h = 2, col = "cyan", a = 0.31 },
    { kind = "rect", x = 587, y = 167, w = 8, h = 2, col = "cyan", a = 0.52 },
    { kind = "rect", x = 932, y = 312, w = 15, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 979, y = 210, w = 10, h = 2, col = "cyan", a = 0.52 },
    { kind = "rect", x = 719, y = 93, w = 22, h = 2, col = "cyan", a = 0.41 },
    { kind = "rect", x = 1201, y = 148, w = 22, h = 2, col = "cyan", a = 0.46 },
    { kind = "rect", x = 616, y = 180, w = 23, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 8, y = 37, w = 20, h = 2, col = "cyan", a = 0.27 },
    { kind = "rect", x = 414, y = 120, w = 3, h = 3, col = "teal", a = 0.67 },
    { kind = "rect", x = 699, y = 267, w = 3, h = 3, col = "teal", a = 0.77 },
    { kind = "rect", x = 595, y = 290, w = 3, h = 3, col = "teal", a = 0.81 },
    { kind = "rect", x = 1083, y = 192, w = 3, h = 3, col = "teal", a = 0.54 },
    { kind = "rect", x = 536, y = 40, w = 3, h = 3, col = "teal", a = 0.85 },
    { kind = "rect", x = 858, y = 207, w = 3, h = 3, col = "teal", a = 0.51 },
    { kind = "rect", x = 130, y = 148, w = 3, h = 3, col = "teal", a = 0.7 },
    { kind = "rect", x = 1096, y = 53, w = 3, h = 3, col = "teal", a = 0.69 },
    { kind = "rect", x = 1227, y = 157, w = 3, h = 3, col = "teal", a = 0.71 },
    { kind = "rect", x = 388, y = 93, w = 3, h = 3, col = "teal", a = 0.63 },
    { kind = "rect", x = 366, y = 94, w = 3, h = 3, col = "teal", a = 0.57 },
    { kind = "rect", x = 716, y = 78, w = 3, h = 3, col = "teal", a = 0.76 },
    { kind = "rect", x = 620, y = 93, w = 3, h = 3, col = "teal", a = 0.54 },
    { kind = "rect", x = 883, y = 71, w = 3, h = 3, col = "teal", a = 0.62 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 14, w = 1328, h = 14, col = "black", a = 0.88, py = -0.14, step = 26 },
    { kind = "band", x = 0, y = 0, w = 24, h = 352, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
    { kind = "band", x = 1256, y = 0, w = 24, h = 352, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 128, y = 126, col = { 0.36, 0.94, 0.90 }, r = 59, flicker = 7.25 },
    { x = 384, y = 208, col = { 0.36, 0.94, 0.90 }, r = 57, flicker = 6.86 },
    { x = 640, y = 159, col = { 0.36, 0.94, 0.90 }, r = 69, flicker = 10.34 },
    { x = 896, y = 135, col = { 0.36, 0.94, 0.90 }, r = 77, flicker = 7.11 },
    { x = 1152, y = 169, col = { 0.36, 0.94, 0.90 }, r = 69, flicker = 8.75 },
  },
  mapPos = { x = 6, y = 2, w = 4, h = 1 },
  map = [[
######AAA#######################################################################
######AAA#######################################################################
##............................................................................##
##............................................................................##
##............................................................................##
##..=====.....................................................................##
##............................................................................##
##............................................................................##
##..=====........................==============...............................##
##............................................................................##
##............................................................................##
##..=====.....................................................................##
##............===========..............................===========............##
##............................................................................##
##..=====.....................................................................##
##..........................................................................BB##
##............................t.....S.......................................BB##
################################################################################
################################################################################
################################################################################
################################################################################
################################################################################
]],
  key = {
    ["t"] = "boss:motherengine",
    ["S"] = "seat",
  },
  links = {
    A = { "core_4", "B" },
    B = { "core_2", "D" },
  },
}
