-- generated by scripts/genrooms.py
return {
  zone = "core", music = "core",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "black", a = 0.42, a2 = 0.12, py = 0.05 },
    { kind = "rail", x = -12, y = 38, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 87, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 136, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 184, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 233, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "column", x = -10, y = 0, w = 26, h = 272, col = "black", a = 0.4, py = 0.23, step = 20, acc = "cyan" },
    { kind = "column", x = 43, y = 0, w = 14, h = 272, col = "black", a = 0.4, py = 0.22, step = 30, acc = "cyan" },
    { kind = "column", x = 102, y = 0, w = 17, h = 272, col = "black", a = 0.4, py = 0.19, step = 18, acc = "cyan" },
    { kind = "column", x = 149, y = 0, w = 16, h = 272, col = "black", a = 0.4, py = 0.22, step = 22, acc = "cyan" },
    { kind = "column", x = 201, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.27, step = 18, acc = "cyan" },
    { kind = "column", x = 286, y = 0, w = 14, h = 272, col = "black", a = 0.4, py = 0.24, step = 19, acc = "cyan" },
    { kind = "column", x = 347, y = 0, w = 21, h = 272, col = "black", a = 0.4, py = 0.25, step = 22, acc = "cyan" },
    { kind = "column", x = 429, y = 0, w = 18, h = 272, col = "black", a = 0.4, py = 0.2, step = 22, acc = "cyan" },
    { kind = "column", x = 476, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.29, step = 26, acc = "cyan" },
    { kind = "column", x = 562, y = 0, w = 30, h = 272, col = "black", a = 0.4, py = 0.27, step = 27, acc = "cyan" },
    { kind = "column", x = 627, y = 0, w = 17, h = 272, col = "black", a = 0.4, py = 0.19, step = 29, acc = "cyan" },
    { kind = "column", x = 700, y = 0, w = 17, h = 272, col = "black", a = 0.4, py = 0.24, step = 22, acc = "cyan" },
    { kind = "column", x = 787, y = 0, w = 27, h = 272, col = "black", a = 0.4, py = 0.21, step = 21, acc = "cyan" },
    { kind = "column", x = 873, y = 0, w = 21, h = 272, col = "black", a = 0.4, py = 0.27, step = 19, acc = "cyan" },
    { kind = "column", x = 952, y = 0, w = 30, h = 272, col = "black", a = 0.4, py = 0.23, step = 26, acc = "cyan" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 220, y = 104, w = 10, h = 2, col = "cyan", a = 0.52 },
    { kind = "rect", x = 47, y = 148, w = 25, h = 2, col = "cyan", a = 0.41 },
    { kind = "rect", x = 547, y = 238, w = 16, h = 2, col = "cyan", a = 0.44 },
    { kind = "rect", x = 815, y = 115, w = 20, h = 2, col = "cyan", a = 0.27 },
    { kind = "rect", x = 173, y = 30, w = 21, h = 2, col = "cyan", a = 0.41 },
    { kind = "rect", x = 739, y = 84, w = 20, h = 2, col = "cyan", a = 0.42 },
    { kind = "rect", x = 822, y = 69, w = 26, h = 2, col = "cyan", a = 0.49 },
    { kind = "rect", x = 828, y = 142, w = 20, h = 2, col = "cyan", a = 0.29 },
    { kind = "rect", x = 641, y = 242, w = 13, h = 2, col = "cyan", a = 0.4 },
    { kind = "rect", x = 109, y = 171, w = 22, h = 2, col = "cyan", a = 0.52 },
    { kind = "rect", x = 527, y = 123, w = 23, h = 2, col = "cyan", a = 0.32 },
    { kind = "rect", x = 531, y = 93, w = 18, h = 2, col = "cyan", a = 0.4 },
    { kind = "rect", x = 324, y = 183, w = 22, h = 2, col = "cyan", a = 0.48 },
    { kind = "rect", x = 756, y = 231, w = 14, h = 2, col = "cyan", a = 0.54 },
    { kind = "rect", x = 54, y = 216, w = 8, h = 2, col = "cyan", a = 0.49 },
    { kind = "rect", x = 488, y = 130, w = 21, h = 2, col = "cyan", a = 0.27 },
    { kind = "rect", x = 935, y = 220, w = 3, h = 3, col = "teal", a = 0.58 },
    { kind = "rect", x = 709, y = 146, w = 3, h = 3, col = "teal", a = 0.78 },
    { kind = "rect", x = 771, y = 72, w = 3, h = 3, col = "teal", a = 0.86 },
    { kind = "rect", x = 313, y = 185, w = 3, h = 3, col = "teal", a = 0.66 },
    { kind = "rect", x = 770, y = 195, w = 3, h = 3, col = "teal", a = 0.58 },
    { kind = "rect", x = 254, y = 73, w = 3, h = 3, col = "teal", a = 0.58 },
    { kind = "rect", x = 688, y = 75, w = 3, h = 3, col = "teal", a = 0.53 },
    { kind = "rect", x = 273, y = 49, w = 3, h = 3, col = "teal", a = 0.53 },
    { kind = "rect", x = 741, y = 50, w = 3, h = 3, col = "teal", a = 0.54 },
    { kind = "rect", x = 341, y = 145, w = 3, h = 3, col = "teal", a = 0.62 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 1008, h = 14, col = "black", a = 0.88, py = -0.14, step = 26 },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 72, col = { 0.36, 0.94, 0.90 }, r = 73, flicker = 8.84 },
    { x = 360, y = 146, col = { 0.36, 0.94, 0.90 }, r = 74, flicker = 7.05 },
    { x = 600, y = 126, col = { 0.36, 0.94, 0.90 }, r = 72, flicker = 8.56 },
    { x = 840, y = 71, col = { 0.36, 0.94, 0.90 }, r = 57, flicker = 9.64 },
  },
  mapPos = { x = 0, y = 1, w = 3, h = 1 },
  gates = { G = "coredoor" },
  map = [[
############################################################
############################################################
##........G...........V.........V.........V...............##
##........G...............................................##
##........G...............................................##
##........G...............................................##
##........G...............................................##
##........G...............................................##
##........G...........................S...................##
##........G.......................=========...............##
##..AA....G...............................................BB
##..AA1...G..2..z.......S...........S.............q.......BB
############################################################
############################################################
############################################################
############################################################
############################################################
]],
  key = {
    ["V"] = "vent:d",
    ["1"] = "sign:sign_core",
    ["2"] = "sign:log_core1",
    ["z"] = "checkpoint",
    ["S"] = "sentinel",
    ["q"] = "eliteguard",
  },
  links = {
    A = { "deep_stair_2", "C" },
    B = { "core_2", "A" },
  },
}
