-- generated by scripts/genrooms.py
return {
  zone = "core", music = "core",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "black", a = 0.42, a2 = 0.12, py = 0.05 },
    { kind = "rail", x = -12, y = 38, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 87, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 136, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 184, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 233, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "column", x = -10, y = 0, w = 17, h = 272, col = "black", a = 0.4, py = 0.19, step = 23, acc = "cyan" },
    { kind = "column", x = 63, y = 0, w = 28, h = 272, col = "black", a = 0.4, py = 0.26, step = 26, acc = "cyan" },
    { kind = "column", x = 133, y = 0, w = 28, h = 272, col = "black", a = 0.4, py = 0.19, step = 29, acc = "cyan" },
    { kind = "column", x = 213, y = 0, w = 22, h = 272, col = "black", a = 0.4, py = 0.17, step = 20, acc = "cyan" },
    { kind = "column", x = 261, y = 0, w = 28, h = 272, col = "black", a = 0.4, py = 0.19, step = 25, acc = "cyan" },
    { kind = "column", x = 355, y = 0, w = 25, h = 272, col = "black", a = 0.4, py = 0.22, step = 28, acc = "cyan" },
    { kind = "column", x = 436, y = 0, w = 21, h = 272, col = "black", a = 0.4, py = 0.24, step = 22, acc = "cyan" },
    { kind = "column", x = 511, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.27, step = 20, acc = "cyan" },
    { kind = "column", x = 569, y = 0, w = 23, h = 272, col = "black", a = 0.4, py = 0.18, step = 27, acc = "cyan" },
    { kind = "column", x = 618, y = 0, w = 27, h = 272, col = "black", a = 0.4, py = 0.23, step = 25, acc = "cyan" },
    { kind = "column", x = 701, y = 0, w = 16, h = 272, col = "black", a = 0.4, py = 0.27, step = 18, acc = "cyan" },
    { kind = "column", x = 776, y = 0, w = 27, h = 272, col = "black", a = 0.4, py = 0.21, step = 28, acc = "cyan" },
    { kind = "column", x = 842, y = 0, w = 24, h = 272, col = "black", a = 0.4, py = 0.21, step = 20, acc = "cyan" },
    { kind = "column", x = 899, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.25, step = 26, acc = "cyan" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 545, y = 86, w = 19, h = 2, col = "cyan", a = 0.26 },
    { kind = "rect", x = 640, y = 98, w = 22, h = 2, col = "cyan", a = 0.46 },
    { kind = "rect", x = 902, y = 152, w = 13, h = 2, col = "cyan", a = 0.36 },
    { kind = "rect", x = 515, y = 90, w = 23, h = 2, col = "cyan", a = 0.36 },
    { kind = "rect", x = 919, y = 121, w = 10, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 14, y = 155, w = 11, h = 2, col = "cyan", a = 0.32 },
    { kind = "rect", x = 475, y = 161, w = 22, h = 2, col = "cyan", a = 0.31 },
    { kind = "rect", x = 153, y = 175, w = 22, h = 2, col = "cyan", a = 0.39 },
    { kind = "rect", x = 808, y = 200, w = 16, h = 2, col = "cyan", a = 0.43 },
    { kind = "rect", x = 378, y = 188, w = 24, h = 2, col = "cyan", a = 0.51 },
    { kind = "rect", x = 758, y = 140, w = 21, h = 2, col = "cyan", a = 0.32 },
    { kind = "rect", x = 607, y = 221, w = 12, h = 2, col = "cyan", a = 0.35 },
    { kind = "rect", x = 347, y = 49, w = 20, h = 2, col = "cyan", a = 0.48 },
    { kind = "rect", x = 18, y = 134, w = 15, h = 2, col = "cyan", a = 0.32 },
    { kind = "rect", x = 764, y = 216, w = 18, h = 2, col = "cyan", a = 0.28 },
    { kind = "rect", x = 246, y = 46, w = 24, h = 2, col = "cyan", a = 0.55 },
    { kind = "rect", x = 526, y = 221, w = 3, h = 3, col = "teal", a = 0.8 },
    { kind = "rect", x = 133, y = 195, w = 3, h = 3, col = "teal", a = 0.75 },
    { kind = "rect", x = 928, y = 49, w = 3, h = 3, col = "teal", a = 0.67 },
    { kind = "rect", x = 175, y = 105, w = 3, h = 3, col = "teal", a = 0.68 },
    { kind = "rect", x = 401, y = 132, w = 3, h = 3, col = "teal", a = 0.63 },
    { kind = "rect", x = 144, y = 84, w = 3, h = 3, col = "teal", a = 0.81 },
    { kind = "rect", x = 798, y = 166, w = 3, h = 3, col = "teal", a = 0.57 },
    { kind = "rect", x = 810, y = 185, w = 3, h = 3, col = "teal", a = 0.86 },
    { kind = "rect", x = 463, y = 37, w = 3, h = 3, col = "teal", a = 0.65 },
    { kind = "rect", x = 756, y = 150, w = 3, h = 3, col = "teal", a = 0.63 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 1008, h = 14, col = "black", a = 0.88, py = -0.14, step = 26 },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 58, col = { 0.36, 0.94, 0.90 }, r = 66, flicker = 10.37 },
    { x = 360, y = 81, col = { 0.36, 0.94, 0.90 }, r = 70, flicker = 9.17 },
    { x = 600, y = 69, col = { 0.36, 0.94, 0.90 }, r = 82, flicker = 9.32 },
    { x = 840, y = 139, col = { 0.36, 0.94, 0.90 }, r = 66, flicker = 8.71 },
  },
  mapPos = { x = 3, y = 1, w = 3, h = 1 },
  hasTeleporter = true,
  map = [[
############################################################
############################################################
##.................................................G......##
##.................................................G......##
##.................................................G......##
##.................................................G......##
##............................................S....G......##
##........................................=========G......##
##.................................................G......##
##.................................................G......##
AA.................................................GDD....BB
AA....1...s..3..t.............m.........q...2..k...GDD....BB
############################################################
############################################################
############################################################
############################################################
############################################################
]],
  gates = { G = "linkcore_c2" },
  key = {
    ["k"] = "linkcore:linkcore_c2",
    ["2"] = "sign:sign_linkcore",
    ["3"] = "sign:log_core2",
    ["s"] = "checkpoint",
    ["t"] = "teleporter:core",
    ["m"] = "screamer",
    ["q"] = "eliteguard",
    ["S"] = "sentinel",
    ["1"] = "sign:sign_core2",
  },
  links = {
    A = { "core_1", "B" },
    B = { "core_3", "A" },
    D = { "core_boss", "B" },
  },
}
