-- generated by scripts/genrooms.py
return {
  zone = "core", music = "core",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "black", a = 0.42, a2 = 0.12, py = 0.05 },
    { kind = "rail", x = -12, y = 38, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 87, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 136, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 184, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 233, w = 984, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "column", x = -10, y = 0, w = 23, h = 272, col = "black", a = 0.4, py = 0.29, step = 30, acc = "cyan" },
    { kind = "column", x = 83, y = 0, w = 30, h = 272, col = "black", a = 0.4, py = 0.28, step = 25, acc = "cyan" },
    { kind = "column", x = 182, y = 0, w = 18, h = 272, col = "black", a = 0.4, py = 0.23, step = 21, acc = "cyan" },
    { kind = "column", x = 271, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.24, step = 30, acc = "cyan" },
    { kind = "column", x = 334, y = 0, w = 27, h = 272, col = "black", a = 0.4, py = 0.23, step = 25, acc = "cyan" },
    { kind = "column", x = 422, y = 0, w = 16, h = 272, col = "black", a = 0.4, py = 0.27, step = 29, acc = "cyan" },
    { kind = "column", x = 484, y = 0, w = 22, h = 272, col = "black", a = 0.4, py = 0.26, step = 27, acc = "cyan" },
    { kind = "column", x = 563, y = 0, w = 20, h = 272, col = "black", a = 0.4, py = 0.19, step = 29, acc = "cyan" },
    { kind = "column", x = 630, y = 0, w = 19, h = 272, col = "black", a = 0.4, py = 0.27, step = 25, acc = "cyan" },
    { kind = "column", x = 714, y = 0, w = 19, h = 272, col = "black", a = 0.4, py = 0.25, step = 29, acc = "cyan" },
    { kind = "column", x = 805, y = 0, w = 17, h = 272, col = "black", a = 0.4, py = 0.2, step = 19, acc = "cyan" },
    { kind = "column", x = 863, y = 0, w = 18, h = 272, col = "black", a = 0.4, py = 0.26, step = 24, acc = "cyan" },
    { kind = "column", x = 941, y = 0, w = 22, h = 272, col = "black", a = 0.4, py = 0.26, step = 29, acc = "cyan" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 255, y = 133, w = 20, h = 2, col = "cyan", a = 0.3 },
    { kind = "rect", x = 329, y = 123, w = 19, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 120, y = 58, w = 19, h = 2, col = "cyan", a = 0.5 },
    { kind = "rect", x = 10, y = 156, w = 18, h = 2, col = "cyan", a = 0.54 },
    { kind = "rect", x = 346, y = 85, w = 17, h = 2, col = "cyan", a = 0.26 },
    { kind = "rect", x = 769, y = 100, w = 20, h = 2, col = "cyan", a = 0.28 },
    { kind = "rect", x = 202, y = 62, w = 15, h = 2, col = "cyan", a = 0.48 },
    { kind = "rect", x = 156, y = 207, w = 25, h = 2, col = "cyan", a = 0.46 },
    { kind = "rect", x = 124, y = 167, w = 15, h = 2, col = "cyan", a = 0.35 },
    { kind = "rect", x = 316, y = 234, w = 25, h = 2, col = "cyan", a = 0.38 },
    { kind = "rect", x = 814, y = 96, w = 15, h = 2, col = "cyan", a = 0.44 },
    { kind = "rect", x = 194, y = 172, w = 20, h = 2, col = "cyan", a = 0.37 },
    { kind = "rect", x = 33, y = 196, w = 11, h = 2, col = "cyan", a = 0.47 },
    { kind = "rect", x = 763, y = 193, w = 24, h = 2, col = "cyan", a = 0.51 },
    { kind = "rect", x = 815, y = 180, w = 25, h = 2, col = "cyan", a = 0.35 },
    { kind = "rect", x = 106, y = 41, w = 9, h = 2, col = "cyan", a = 0.33 },
    { kind = "rect", x = 541, y = 183, w = 3, h = 3, col = "teal", a = 0.7 },
    { kind = "rect", x = 937, y = 123, w = 3, h = 3, col = "teal", a = 0.57 },
    { kind = "rect", x = 918, y = 154, w = 3, h = 3, col = "teal", a = 0.84 },
    { kind = "rect", x = 523, y = 76, w = 3, h = 3, col = "teal", a = 0.77 },
    { kind = "rect", x = 313, y = 238, w = 3, h = 3, col = "teal", a = 0.86 },
    { kind = "rect", x = 112, y = 129, w = 3, h = 3, col = "teal", a = 0.78 },
    { kind = "rect", x = 234, y = 123, w = 3, h = 3, col = "teal", a = 0.88 },
    { kind = "rect", x = 903, y = 147, w = 3, h = 3, col = "teal", a = 0.81 },
    { kind = "rect", x = 23, y = 43, w = 3, h = 3, col = "teal", a = 0.79 },
    { kind = "rect", x = 786, y = 235, w = 3, h = 3, col = "teal", a = 0.59 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 1008, h = 14, col = "black", a = 0.88, py = -0.14, step = 26 },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 140, col = { 0.36, 0.94, 0.90 }, r = 59, flicker = 8.07 },
    { x = 360, y = 152, col = { 0.36, 0.94, 0.90 }, r = 76, flicker = 8.58 },
    { x = 600, y = 83, col = { 0.36, 0.94, 0.90 }, r = 64, flicker = 6.44 },
    { x = 840, y = 83, col = { 0.36, 0.94, 0.90 }, r = 79, flicker = 9.24 },
  },
  mapPos = { x = 6, y = 1, w = 3, h = 1 },
  gates = { G = "plate_core3a", H = "plate_core3b" },
  map = [[
############################################################
############################################################
##....................G.................H.................##
##....................G.................H.................##
##....................G.................H.................##
##....................G.................H.................##
##....................G.....S...........H.................##
##....................G.=========.......H.................##
##.........x..........G.......y.........H.................##
##........====........G......====.......H.................##
AA....................G.................H.................BB
AA...1..........q.....G...........m.....H.......5.........BB
############################################################
############################################################
############################################################
############################################################
############################################################
]],
  key = {
    ["1"] = "sign:log_core3",
    ["x"] = "plate:plate_core3a",
    ["y"] = "plate:plate_core3b",
    ["q"] = "eliteguard",
    ["m"] = "screamer",
    ["S"] = "sentinel",
    ["5"] = "capsule:cap_core",
  },
  links = {
    A = { "core_2", "B" },
    B = { "core_4", "A" },
  },
}
