-- generated by scripts/genrooms.py
return {
  zone = "core", music = "core",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 512, col = "black", a = 0.42, a2 = 0.12, py = 0.05 },
    { kind = "rail", x = -12, y = 71, w = 504, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 163, w = 504, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 256, w = 504, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 348, w = 504, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "rail", x = -12, y = 440, w = 504, h = 3, col = "cyan", a = 0.16, py = 0.24 },
    { kind = "column", x = -10, y = 0, w = 14, h = 512, col = "black", a = 0.4, py = 0.21, step = 23, acc = "cyan" },
    { kind = "column", x = 60, y = 0, w = 29, h = 512, col = "black", a = 0.4, py = 0.2, step = 18, acc = "cyan" },
    { kind = "column", x = 152, y = 0, w = 30, h = 512, col = "black", a = 0.4, py = 0.2, step = 28, acc = "cyan" },
    { kind = "column", x = 249, y = 0, w = 22, h = 512, col = "black", a = 0.4, py = 0.17, step = 18, acc = "cyan" },
    { kind = "column", x = 306, y = 0, w = 29, h = 512, col = "black", a = 0.4, py = 0.25, step = 18, acc = "cyan" },
    { kind = "column", x = 363, y = 0, w = 16, h = 512, col = "black", a = 0.4, py = 0.19, step = 20, acc = "cyan" },
    { kind = "column", x = 422, y = 0, w = 25, h = 512, col = "black", a = 0.4, py = 0.23, step = 22, acc = "cyan" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 256, y = 81, w = 9, h = 2, col = "cyan", a = 0.27 },
    { kind = "rect", x = 463, y = 98, w = 11, h = 2, col = "cyan", a = 0.28 },
    { kind = "rect", x = 215, y = 438, w = 18, h = 2, col = "cyan", a = 0.48 },
    { kind = "rect", x = 5, y = 284, w = 24, h = 2, col = "cyan", a = 0.36 },
    { kind = "rect", x = 309, y = 397, w = 20, h = 2, col = "cyan", a = 0.45 },
    { kind = "rect", x = 160, y = 201, w = 19, h = 2, col = "cyan", a = 0.31 },
    { kind = "rect", x = 350, y = 178, w = 18, h = 2, col = "cyan", a = 0.3 },
    { kind = "rect", x = 357, y = 364, w = 22, h = 2, col = "cyan", a = 0.37 },
    { kind = "rect", x = 210, y = 290, w = 3, h = 3, col = "teal", a = 0.69 },
    { kind = "rect", x = 180, y = 372, w = 3, h = 3, col = "teal", a = 0.7 },
    { kind = "rect", x = 132, y = 318, w = 3, h = 3, col = "teal", a = 0.59 },
    { kind = "rect", x = 243, y = 314, w = 3, h = 3, col = "teal", a = 0.74 },
    { kind = "rect", x = 161, y = 102, w = 3, h = 3, col = "teal", a = 0.65 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 20, w = 528, h = 14, col = "black", a = 0.88, py = -0.14, step = 26 },
    { kind = "band", x = 0, y = 0, w = 24, h = 512, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
    { kind = "band", x = 456, y = 0, w = 24, h = 512, col = "black", a = 0.52, a2 = 0.52, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 160, col = { 0.36, 0.94, 0.90 }, r = 57, flicker = 6.47 },
    { x = 360, y = 109, col = { 0.36, 0.94, 0.90 }, r = 62, flicker = 10.51 },
  },
  mapPos = { x = 9, y = 0, w = 1, h = 2 },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##..........................##
AA..........................##
AA..........................##
#########...................##
##.......===................##
##..........................##
##............S.............##
##..........#######.........##
##.................===......##
##..........................##
##....................m.....##
##..................##########
##...............===........##
##..........................##
##........q...q.............##
##......#########...........##
##..===.....................##
##..........................##
##..........................##
#######.....................##
##......===.................##
##...........1...z..........##
##.........a##...##.........##
##############...#############
##############...#############
##############BBB#############
##############BBB#############
]],
  key = {
    ["a"] = "cell",
    ["1"] = "sign:log_core4",
    ["S"] = "sentinel",
    ["q"] = "eliteguard",
    ["m"] = "screamer",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "core_3", "B" },
    B = { "core_boss", "A" },
  },
}
