-- generated by scripts/gen_coldstore.py (v4.0 Phase B)
return {
  zone = "cradle", music = "cradle",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "black", a = 0.5, a2 = 0.16, py = 0.05 },
    { kind = "column", x = -14, y = 0, w = 22, h = 272, col = "black", a = 0.44, py = 0.29, step = 44, acc = "violet" },
    { kind = "column", x = 93, y = 0, w = 35, h = 272, col = "black", a = 0.44, py = 0.2, step = 27, acc = "violet" },
    { kind = "column", x = 196, y = 0, w = 18, h = 272, col = "black", a = 0.44, py = 0.2, step = 32, acc = "violet" },
    { kind = "column", x = 259, y = 0, w = 24, h = 272, col = "black", a = 0.44, py = 0.21, step = 41, acc = "violet" },
    { kind = "column", x = 321, y = 0, w = 25, h = 272, col = "black", a = 0.44, py = 0.17, step = 34, acc = "violet" },
    { kind = "column", x = 401, y = 0, w = 37, h = 272, col = "black", a = 0.44, py = 0.23, step = 28, acc = "violet" },
    { kind = "column", x = 505, y = 0, w = 18, h = 272, col = "black", a = 0.44, py = 0.27, step = 30, acc = "violet" },
    { kind = "column", x = 589, y = 0, w = 23, h = 272, col = "black", a = 0.44, py = 0.24, step = 29, acc = "violet" },
    { kind = "column", x = 682, y = 0, w = 33, h = 272, col = "black", a = 0.44, py = 0.19, step = 37, acc = "violet" },
    { kind = "column", x = 762, y = 0, w = 28, h = 272, col = "black", a = 0.44, py = 0.3, step = 24, acc = "violet" },
    { kind = "column", x = 861, y = 0, w = 23, h = 272, col = "black", a = 0.44, py = 0.27, step = 44, acc = "violet" },
    { kind = "column", x = 934, y = 0, w = 31, h = 272, col = "black", a = 0.44, py = 0.18, step = 33, acc = "violet" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 314, y = 224, w = 5, h = 5, col = "orchid", a = 0.76 },
    { kind = "rect", x = 698, y = 48, w = 5, h = 2, col = "orchid", a = 0.83 },
    { kind = "rect", x = 568, y = 131, w = 5, h = 4, col = "orchid", a = 0.68 },
    { kind = "rect", x = 94, y = 219, w = 5, h = 3, col = "orchid", a = 0.6 },
    { kind = "rect", x = 680, y = 239, w = 3, h = 4, col = "lime", a = 0.76 },
    { kind = "rect", x = 887, y = 100, w = 2, h = 5, col = "violet", a = 0.67 },
    { kind = "rect", x = 26, y = 101, w = 4, h = 5, col = "orchid", a = 0.44 },
    { kind = "rect", x = 886, y = 231, w = 5, h = 3, col = "violet", a = 0.8 },
    { kind = "rect", x = 902, y = 182, w = 3, h = 4, col = "violet", a = 0.69 },
    { kind = "rect", x = 445, y = 68, w = 2, h = 3, col = "lime", a = 0.82 },
    { kind = "rect", x = 257, y = 221, w = 3, h = 4, col = "violet", a = 0.62 },
    { kind = "rect", x = 243, y = 146, w = 5, h = 4, col = "violet", a = 0.49 },
    { kind = "rect", x = 320, y = 197, w = 2, h = 3, col = "violet", a = 0.52 },
    { kind = "rect", x = 522, y = 77, w = 3, h = 5, col = "orchid", a = 0.51 },
    { kind = "rect", x = 665, y = 164, w = 3, h = 2, col = "violet", a = 0.66 },
    { kind = "rect", x = 609, y = 67, w = 4, h = 2, col = "violet", a = 0.6 },
    { kind = "rect", x = 443, y = 108, w = 4, h = 3, col = "violet", a = 0.72 },
    { kind = "rect", x = 88, y = 32, w = 2, h = 5, col = "orchid", a = 0.6 },
    { kind = "rect", x = 740, y = 185, w = 4, h = 3, col = "lime", a = 0.69 },
    { kind = "rect", x = 205, y = 71, w = 4, h = 2, col = "lime", a = 0.54 },
    { kind = "rect", x = 341, y = 48, w = 3, h = 5, col = "orchid", a = 0.83 },
    { kind = "rect", x = 53, y = 32, w = 3, h = 5, col = "violet", a = 0.69 },
    { kind = "rect", x = 780, y = 188, w = 4, h = 4, col = "orchid", a = 0.46 },
    { kind = "rect", x = 442, y = 154, w = 5, h = 4, col = "orchid", a = 0.8 },
    { kind = "hang", x = 167, y = 19, w = 2, h = 30, col = "plum", a = 0.39, lw = 2, sway = 2, rate = 0.4, bob = true },
    { kind = "hang", x = 481, y = 36, w = 2, h = 22, col = "plum", a = 0.47, lw = 2, sway = 3, rate = 0.31, bob = true },
    { kind = "hang", x = 845, y = 0, w = 2, h = 33, col = "plum", a = 0.38, lw = 2, sway = 5, rate = 0.49, bob = true },
    { kind = "hang", x = 705, y = 89, w = 2, h = 35, col = "plum", a = 0.31, lw = 2, sway = 2, rate = 0.48, bob = true },
    { kind = "hang", x = 347, y = 95, w = 2, h = 20, col = "plum", a = 0.41, lw = 2, sway = 5, rate = 0.3, bob = true },
    { kind = "hang", x = 925, y = 48, w = 2, h = 40, col = "plum", a = 0.49, lw = 2, sway = 3, rate = 0.27, bob = true },
    { kind = "hang", x = 795, y = 89, w = 2, h = 39, col = "plum", a = 0.56, lw = 2, sway = 4, rate = 0.35, bob = true },
    { kind = "hang", x = 945, y = 118, w = 2, h = 15, col = "plum", a = 0.39, lw = 2, sway = 4, rate = 0.43, bob = true },
    { kind = "hang", x = 70, y = 70, w = 2, h = 38, col = "plum", a = 0.53, lw = 2, sway = 4, rate = 0.48, bob = true },
    { kind = "hang", x = 400, y = 21, w = 2, h = 20, col = "plum", a = 0.3, lw = 2, sway = 4, rate = 0.44, bob = true },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "band", x = 0, y = 0, w = 30, h = 272, col = "black", a = 0.66, a2 = 0.66, py = -0.05 },
    { kind = "band", x = 930, y = 0, w = 30, h = 272, col = "black", a = 0.66, a2 = 0.66, py = -0.05 },
    { kind = "column", x = 238, y = 0, w = 14, h = 272, col = "black", a = 0.8, py = -0.14, step = 28, acc = "plum" },
    { kind = "column", x = 329, y = 0, w = 15, h = 272, col = "black", a = 0.8, py = -0.14, step = 28, acc = "plum" },
    { kind = "column", x = 526, y = 0, w = 15, h = 272, col = "black", a = 0.8, py = -0.14, step = 28, acc = "plum" },
    { kind = "column", x = 617, y = 0, w = 15, h = 272, col = "black", a = 0.8, py = -0.14, step = 28, acc = "plum" },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 36, y = 150, col = { 0.70, 0.45, 1.00 }, r = 56, flicker = 2.71 },
    { x = 500, y = 118, col = { 0.70, 0.45, 1.00 }, r = 41, flicker = 2.68 },
    { x = 555, y = 99, col = { 0.70, 0.45, 1.00 }, r = 40, flicker = 3.19 },
    { x = 937, y = 106, col = { 0.70, 0.45, 1.00 }, r = 58, flicker = 2.56 },
  },
  mapPos = { x = 0, y = 0, w = 3, h = 1 },
  dark = 0.55,
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##..............p.......p.......p.......p.......p.N.......##
##..........=======================================.......##
##........................................................##
##====....................................................##
AA........................................................##
AA...s....p...p...p...p...p...r...p...p...p...p...p...k.y.##
############################################################
############################################################
############################################################
############################################################
############################################################
]],
  key = {
    -- CURATOR LOCK, where he fell. Not an NPC, not a dialogue tree: a
    -- body at his post and one line. You have met him across a hundred
    -- years of handwriting by the time you get here, and then you meet
    -- him.
    ["k"] = "frozenkeeper:lock",
    -- ...and the thing he died in front of.
    ["y"] = "terminal:log_cradle",
    ["N"] = "sign:sign_sleepers",
    ["s"] = "checkpoint",
    ["p"] = "pod",
    ["r"] = "sign:cradle_record",
  },
  links = {
    A = { "cold_boss", "B" },
  },
}
