-- generated by scripts/genrooms.py
return {
  zone = "crystal", music = "crystal",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "plum", a = 0.34, a2 = 0.08, py = 0.05 },
    { kind = "column", x = -14, y = 94, w = 11, h = 178, col = "black", a = 0.4, py = 0.24, step = 22, acc = "orchid" },
    { kind = "column", x = 30, y = 109, w = 11, h = 163, col = "black", a = 0.4, py = 0.24, step = 29, acc = "orchid" },
    { kind = "column", x = 76, y = 82, w = 11, h = 190, col = "black", a = 0.4, py = 0.24, step = 22, acc = "orchid" },
    { kind = "column", x = 104, y = 115, w = 11, h = 157, col = "black", a = 0.4, py = 0.24, step = 28, acc = "orchid" },
    { kind = "column", x = 130, y = 151, w = 11, h = 121, col = "black", a = 0.4, py = 0.24, step = 37, acc = "orchid" },
    { kind = "column", x = 175, y = 155, w = 11, h = 117, col = "black", a = 0.4, py = 0.24, step = 23, acc = "orchid" },
    { kind = "column", x = 204, y = 107, w = 11, h = 165, col = "black", a = 0.4, py = 0.24, step = 23, acc = "orchid" },
    { kind = "column", x = 229, y = 80, w = 11, h = 192, col = "black", a = 0.4, py = 0.24, step = 37, acc = "orchid" },
    { kind = "column", x = 271, y = 92, w = 11, h = 180, col = "black", a = 0.4, py = 0.24, step = 22, acc = "orchid" },
    { kind = "column", x = 303, y = 56, w = 11, h = 216, col = "black", a = 0.4, py = 0.24, step = 40, acc = "orchid" },
    { kind = "column", x = 351, y = 43, w = 11, h = 229, col = "black", a = 0.4, py = 0.24, step = 28, acc = "orchid" },
    { kind = "column", x = 392, y = 90, w = 11, h = 182, col = "black", a = 0.4, py = 0.24, step = 35, acc = "orchid" },
    { kind = "column", x = 441, y = 122, w = 11, h = 150, col = "black", a = 0.4, py = 0.24, step = 31, acc = "orchid" },
    { kind = "column", x = 468, y = 121, w = 11, h = 151, col = "black", a = 0.4, py = 0.24, step = 40, acc = "orchid" },
    { kind = "column", x = 7, y = 111, w = 17, h = 161, col = "black", a = 0.24, py = 0.13, step = 35, acc = "orchid" },
    { kind = "column", x = 47, y = 145, w = 17, h = 127, col = "black", a = 0.24, py = 0.13, step = 33, acc = "orchid" },
    { kind = "column", x = 87, y = 52, w = 17, h = 220, col = "black", a = 0.24, py = 0.13, step = 22, acc = "orchid" },
    { kind = "column", x = 146, y = 158, w = 17, h = 114, col = "black", a = 0.24, py = 0.13, step = 29, acc = "orchid" },
    { kind = "column", x = 182, y = 68, w = 17, h = 204, col = "black", a = 0.24, py = 0.13, step = 37, acc = "orchid" },
    { kind = "column", x = 242, y = 68, w = 17, h = 204, col = "black", a = 0.24, py = 0.13, step = 33, acc = "orchid" },
    { kind = "column", x = 283, y = 119, w = 17, h = 153, col = "black", a = 0.24, py = 0.13, step = 36, acc = "orchid" },
    { kind = "column", x = 325, y = 108, w = 17, h = 164, col = "black", a = 0.24, py = 0.13, step = 25, acc = "orchid" },
    { kind = "column", x = 363, y = 119, w = 17, h = 153, col = "black", a = 0.24, py = 0.13, step = 26, acc = "orchid" },
    { kind = "column", x = 422, y = 142, w = 17, h = 130, col = "black", a = 0.24, py = 0.13, step = 23, acc = "orchid" },
    { kind = "column", x = 473, y = 168, w = 17, h = 104, col = "black", a = 0.24, py = 0.13, step = 32, acc = "orchid" },
    { kind = "shaft", x = 100, y = 0, w = 51, h = 244, col = "orchid", a = 0.16, py = 0.2, skew = 33, ph = 3.91 },
    { kind = "shaft", x = 203, y = 0, w = 46, h = 244, col = "orchid", a = 0.16, py = 0.2, skew = 21, ph = 3.16 },
    { kind = "shaft", x = 273, y = 0, w = 46, h = 244, col = "orchid", a = 0.16, py = 0.2, skew = -18, ph = 5.32 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 231, y = 78, w = 3, h = 18, col = "orchid", a = 0.58 },
    { kind = "rect", x = 234, y = 78, w = 2, h = 9, col = "violet", a = 0.49 },
    { kind = "rect", x = 237, y = 78, w = 4, h = 15, col = "orchid", a = 0.67 },
    { kind = "rect", x = 240, y = 78, w = 4, h = 17, col = "violet", a = 0.66 },
    { kind = "rect", x = 120, y = 72, w = 2, h = 8, col = "violet", a = 0.57 },
    { kind = "rect", x = 123, y = 72, w = 2, h = 6, col = "violet", a = 0.57 },
    { kind = "rect", x = 288, y = 173, w = 4, h = 17, col = "plum", a = 0.58 },
    { kind = "rect", x = 291, y = 173, w = 2, h = 6, col = "orchid", a = 0.52 },
    { kind = "rect", x = 298, y = 173, w = 3, h = 18, col = "violet", a = 0.69 },
    { kind = "rect", x = 392, y = 78, w = 2, h = 20, col = "violet", a = 0.5 },
    { kind = "rect", x = 394, y = 78, w = 2, h = 16, col = "orchid", a = 0.67 },
    { kind = "rect", x = 208, y = 150, w = 4, h = 15, col = "orchid", a = 0.7 },
    { kind = "rect", x = 213, y = 150, w = 2, h = 13, col = "orchid", a = 0.7 },
    { kind = "rect", x = 214, y = 150, w = 2, h = 6, col = "violet", a = 0.39 },
    { kind = "rect", x = 214, y = 150, w = 4, h = 8, col = "plum", a = 0.68 },
    { kind = "rect", x = 182, y = 206, w = 3, h = 20, col = "plum", a = 0.71 },
    { kind = "rect", x = 185, y = 206, w = 3, h = 6, col = "plum", a = 0.73 },
    { kind = "rect", x = 321, y = 170, w = 3, h = 17, col = "plum", a = 0.4 },
    { kind = "rect", x = 326, y = 170, w = 2, h = 7, col = "orchid", a = 0.54 },
    { kind = "rect", x = 315, y = 182, w = 3, h = 13, col = "orchid", a = 0.7 },
    { kind = "rect", x = 319, y = 182, w = 4, h = 18, col = "violet", a = 0.65 },
    { kind = "rect", x = 113, y = 205, w = 4, h = 18, col = "violet", a = 0.39 },
    { kind = "rect", x = 115, y = 205, w = 2, h = 8, col = "orchid", a = 0.43 },
    { kind = "rect", x = 119, y = 205, w = 4, h = 8, col = "violet", a = 0.4 },
    { kind = "rect", x = 281, y = 148, w = 4, h = 17, col = "plum", a = 0.54 },
    { kind = "rect", x = 286, y = 148, w = 4, h = 13, col = "plum", a = 0.4 },
    { kind = "rect", x = 291, y = 148, w = 2, h = 8, col = "violet", a = 0.4 },
    { kind = "rect", x = 290, y = 148, w = 3, h = 17, col = "violet", a = 0.37 },
    { kind = "rect", x = 218, y = 182, w = 3, h = 6, col = "plum", a = 0.39 },
    { kind = "rect", x = 223, y = 182, w = 2, h = 15, col = "orchid", a = 0.51 },
    { kind = "rect", x = 228, y = 182, w = 4, h = 10, col = "violet", a = 0.5 },
    { kind = "rect", x = 265, y = 65, w = 2, h = 19, col = "plum", a = 0.54 },
    { kind = "rect", x = 268, y = 65, w = 2, h = 10, col = "plum", a = 0.64 },
    { kind = "rect", x = 273, y = 65, w = 2, h = 7, col = "orchid", a = 0.64 },
    { kind = "rect", x = 368, y = 185, w = 5, h = 5, col = "cream", a = 0.45 },
    { kind = "rect", x = 207, y = 187, w = 3, h = 6, col = "cream", a = 0.54 },
    { kind = "rect", x = 462, y = 86, w = 3, h = 5, col = "cream", a = 0.41 },
    { kind = "rect", x = 11, y = 213, w = 6, h = 4, col = "cream", a = 0.48 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "column", x = 264, y = 0, w = 17, h = 272, col = "black", a = 0.8, py = -0.15, step = 30, acc = "violet" },
    { kind = "column", x = 197, y = 0, w = 12, h = 272, col = "black", a = 0.8, py = -0.15, step = 30, acc = "violet" },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "plum", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 456, y = 0, w = 24, h = 272, col = "plum", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 120, y = 161, col = { 0.78, 0.48, 1.00 }, r = 83, flicker = 2.92 },
    { x = 360, y = 103, col = { 0.78, 0.48, 1.00 }, r = 52, flicker = 2.93 },
  },
  mapPos = { x = 4, y = 0, w = 1, h = 1 },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..AA......................##
##..AA....1........a........##
##############################
##############################
##############################
##############################
##############################
]],
  key = {
    ["1"] = "chest:chest_crys1:scrap:20",
    ["a"] = "cell",
  },
  links = {
    A = { "crys_2", "E" },
  },
}
