-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 54, w = 512, h = 13, col = "black", a = 0.36, py = 0.28, step = 38 },
    { kind = "girder", x = -16, y = 119, w = 512, h = 13, col = "black", a = 0.28, py = 0.2, step = 34 },
    { kind = "girder", x = -16, y = 184, w = 512, h = 13, col = "black", a = 0.2, py = 0.13, step = 38 },
    { kind = "column", x = -12, y = 54, w = 21, h = 217, col = "navy", a = 0.26, py = 0.17, step = 35, acc = "teal" },
    { kind = "column", x = 68, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 32, acc = "teal" },
    { kind = "column", x = 139, y = 54, w = 14, h = 217, col = "navy", a = 0.26, py = 0.17, step = 40, acc = "teal" },
    { kind = "column", x = 232, y = 54, w = 13, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 309, y = 54, w = 20, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 384, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 25, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 106, y = 236, w = 1, h = 54, col = "sky", a = 0.25, lw = 1, sway = 2, rate = 0.76, bob = true },
    { kind = "hang", x = 49, y = 242, w = 1, h = 42, col = "sky", a = 0.25, lw = 1, sway = 2, rate = 0.84, bob = true },
    { kind = "hang", x = 185, y = 143, w = 1, h = 49, col = "sky", a = 0.38, lw = 1, sway = 3, rate = 1.05, bob = true },
    { kind = "hang", x = 384, y = 83, w = 1, h = 36, col = "sky", a = 0.26, lw = 1, sway = 2, rate = 0.6, bob = true },
    { kind = "hang", x = 23, y = 221, w = 1, h = 31, col = "sky", a = 0.4, lw = 1, sway = 5, rate = 0.83, bob = true },
    { kind = "hang", x = 77, y = 177, w = 1, h = 54, col = "sky", a = 0.22, lw = 1, sway = 2, rate = 1.09, bob = true },
    { kind = "hang", x = 381, y = 121, w = 1, h = 43, col = "sky", a = 0.29, lw = 1, sway = 3, rate = 0.86, bob = true },
    { kind = "hang", x = 12, y = 163, w = 1, h = 52, col = "sky", a = 0.2, lw = 1, sway = 2, rate = 0.8, bob = true },
    { kind = "rect", x = 166, y = 155, w = 8, h = 2, col = "rust", a = 0.3 },
    { kind = "rect", x = 421, y = 191, w = 7, h = 4, col = "teal", a = 0.38 },
    { kind = "rect", x = 197, y = 140, w = 8, h = 4, col = "rust", a = 0.22 },
    { kind = "rect", x = 95, y = 83, w = 16, h = 4, col = "teal", a = 0.27 },
    { kind = "rect", x = 314, y = 48, w = 6, h = 3, col = "rust", a = 0.32 },
    { kind = "rect", x = 213, y = 188, w = 7, h = 2, col = "rust", a = 0.4 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 8, w = 528, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 454, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 38, col = { 0.50, 0.90, 0.92 }, r = 79, flicker = 1.34 },
  },
  mapPos = { x = 12, y = 0, w = 1, h = 1 },
  hasTeleporter = true,
  map = [[
##############################
##############################
###############......#...#####
#############...............##
###########................##.
########..................###.
########..................##.#
#######..................##..#
######.................###...#
####..................###...##
###..................#####.###
###.1...t...........###.#.####
##############...#############
##############...#############
##############...#############
##############AAA#############
##############AAA#############
]],
  key = {
    ["t"] = "teleporter:flooded",
    ["1"] = "sign:sign_hub",
  },
  links = {
    A = { "flood_4", "C" },
  },
}
