-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 54, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 40 },
    { kind = "girder", x = -16, y = 119, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 26 },
    { kind = "girder", x = -16, y = 184, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 28 },
    { kind = "column", x = -12, y = 54, w = 26, h = 217, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 59, y = 54, w = 17, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 145, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 30, acc = "teal" },
    { kind = "column", x = 243, y = 54, w = 20, h = 217, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 320, y = 54, w = 25, h = 217, col = "navy", a = 0.26, py = 0.17, step = 26, acc = "teal" },
    { kind = "column", x = 439, y = 54, w = 22, h = 217, col = "navy", a = 0.26, py = 0.17, step = 36, acc = "teal" },
    { kind = "column", x = 509, y = 54, w = 24, h = 217, col = "navy", a = 0.26, py = 0.17, step = 25, acc = "teal" },
    { kind = "column", x = 575, y = 54, w = 17, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 655, y = 54, w = 15, h = 217, col = "navy", a = 0.26, py = 0.17, step = 29, acc = "teal" },
    { kind = "column", x = 745, y = 54, w = 21, h = 217, col = "navy", a = 0.26, py = 0.17, step = 35, acc = "teal" },
    { kind = "column", x = 856, y = 54, w = 14, h = 217, col = "navy", a = 0.26, py = 0.17, step = 35, acc = "teal" },
    { kind = "column", x = 915, y = 54, w = 20, h = 217, col = "navy", a = 0.26, py = 0.17, step = 36, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 25, y = 104, w = 1, h = 42, col = "sky", a = 0.32, lw = 1, sway = 4, rate = 1.06, bob = true },
    { kind = "hang", x = 598, y = 100, w = 1, h = 21, col = "sky", a = 0.21, lw = 1, sway = 4, rate = 1.06, bob = true },
    { kind = "hang", x = 133, y = 109, w = 1, h = 49, col = "sky", a = 0.22, lw = 1, sway = 5, rate = 0.67, bob = true },
    { kind = "hang", x = 578, y = 152, w = 1, h = 50, col = "sky", a = 0.25, lw = 1, sway = 2, rate = 0.94, bob = true },
    { kind = "hang", x = 274, y = 180, w = 1, h = 50, col = "sky", a = 0.32, lw = 1, sway = 2, rate = 0.85, bob = true },
    { kind = "hang", x = 211, y = 115, w = 1, h = 38, col = "sky", a = 0.35, lw = 1, sway = 4, rate = 0.55, bob = true },
    { kind = "hang", x = 520, y = 167, w = 1, h = 25, col = "sky", a = 0.4, lw = 1, sway = 5, rate = 0.98, bob = true },
    { kind = "hang", x = 176, y = 104, w = 1, h = 34, col = "sky", a = 0.25, lw = 1, sway = 4, rate = 0.91, bob = true },
    { kind = "hang", x = 573, y = 204, w = 1, h = 29, col = "sky", a = 0.39, lw = 1, sway = 5, rate = 0.68, bob = true },
    { kind = "hang", x = 862, y = 194, w = 1, h = 49, col = "sky", a = 0.27, lw = 1, sway = 2, rate = 0.55, bob = true },
    { kind = "hang", x = 830, y = 195, w = 1, h = 36, col = "sky", a = 0.41, lw = 1, sway = 4, rate = 0.63, bob = true },
    { kind = "hang", x = 747, y = 200, w = 1, h = 29, col = "sky", a = 0.41, lw = 1, sway = 4, rate = 0.63, bob = true },
    { kind = "hang", x = 671, y = 154, w = 1, h = 21, col = "sky", a = 0.34, lw = 1, sway = 3, rate = 0.71, bob = true },
    { kind = "hang", x = 805, y = 189, w = 1, h = 22, col = "sky", a = 0.22, lw = 1, sway = 4, rate = 0.98, bob = true },
    { kind = "hang", x = 368, y = 212, w = 1, h = 35, col = "sky", a = 0.24, lw = 1, sway = 5, rate = 0.62, bob = true },
    { kind = "hang", x = 45, y = 128, w = 1, h = 32, col = "sky", a = 0.28, lw = 1, sway = 3, rate = 0.58, bob = true },
    { kind = "rect", x = 381, y = 186, w = 9, h = 2, col = "teal", a = 0.24 },
    { kind = "rect", x = 701, y = 40, w = 11, h = 4, col = "rust", a = 0.33 },
    { kind = "rect", x = 935, y = 176, w = 12, h = 2, col = "rust", a = 0.23 },
    { kind = "rect", x = 450, y = 195, w = 11, h = 4, col = "teal", a = 0.43 },
    { kind = "rect", x = 334, y = 129, w = 13, h = 4, col = "teal", a = 0.22 },
    { kind = "rect", x = 166, y = 129, w = 14, h = 2, col = "rust", a = 0.35 },
    { kind = "rect", x = 540, y = 227, w = 13, h = 4, col = "rust", a = 0.37 },
    { kind = "rect", x = 736, y = 218, w = 13, h = 3, col = "teal", a = 0.3 },
    { kind = "rect", x = 385, y = 229, w = 9, h = 4, col = "teal", a = 0.35 },
    { kind = "rect", x = 820, y = 48, w = 7, h = 3, col = "rust", a = 0.25 },
    { kind = "rect", x = 295, y = 242, w = 16, h = 4, col = "rust", a = 0.22 },
    { kind = "rect", x = 262, y = 243, w = 9, h = 3, col = "teal", a = 0.28 },
    { kind = "rect", x = 370, y = 152, w = 8, h = 3, col = "rust", a = 0.37 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 8, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 38, col = { 0.50, 0.90, 0.92 }, r = 97, flicker = 1.18 },
    { x = 480, y = 38, col = { 0.50, 0.90, 0.92 }, r = 103, flicker = 1.41 },
    { x = 800, y = 38, col = { 0.50, 0.90, 0.92 }, r = 87, flicker = 0.92 },
  },
  mapPos = { x = 6, y = 1, w = 3, h = 1 },
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##..................b.....................................##
##................======............======................##
##........................................................##
AA..........................m.............................BB
AA......s...1...............................R.............BB
########################~~~~~~~~~~~#########################
########################~~~~~~~~~~~#########################
########################~~~~~~~~~~~#########################
############################################################
############################################################
]],
  key = {
    ["s"] = "checkpoint",
    ["1"] = "sign:sign_warden",
    ["m"] = "depthmine",
    ["R"] = "crab",
    ["b"] = "bubbler",
  },
  links = {
    A = { "flood_2", "B" },
    B = { "flood_warden", "A" },
  },
}
