-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 54, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 26 },
    { kind = "girder", x = -16, y = 119, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 36 },
    { kind = "girder", x = -16, y = 184, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 28 },
    { kind = "column", x = -12, y = 54, w = 17, h = 217, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 51, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 36, acc = "teal" },
    { kind = "column", x = 111, y = 54, w = 21, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 188, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 288, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
    { kind = "column", x = 342, y = 54, w = 18, h = 217, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 411, y = 54, w = 17, h = 217, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 482, y = 54, w = 20, h = 217, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 594, y = 54, w = 16, h = 217, col = "navy", a = 0.26, py = 0.17, step = 39, acc = "teal" },
    { kind = "column", x = 655, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 747, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 826, y = 54, w = 26, h = 217, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 906, y = 54, w = 12, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 126, y = 122, w = 1, h = 41, col = "sky", a = 0.41, lw = 1, sway = 3, rate = 1.02, bob = true },
    { kind = "hang", x = 874, y = 228, w = 1, h = 30, col = "sky", a = 0.32, lw = 1, sway = 4, rate = 0.7, bob = true },
    { kind = "hang", x = 861, y = 222, w = 1, h = 60, col = "sky", a = 0.41, lw = 1, sway = 3, rate = 0.8, bob = true },
    { kind = "hang", x = 856, y = 156, w = 1, h = 44, col = "sky", a = 0.35, lw = 1, sway = 3, rate = 0.75, bob = true },
    { kind = "hang", x = 723, y = 127, w = 1, h = 59, col = "sky", a = 0.22, lw = 1, sway = 4, rate = 0.67, bob = true },
    { kind = "hang", x = 672, y = 98, w = 1, h = 57, col = "sky", a = 0.39, lw = 1, sway = 3, rate = 1.07, bob = true },
    { kind = "hang", x = 880, y = 144, w = 1, h = 55, col = "sky", a = 0.36, lw = 1, sway = 4, rate = 0.79, bob = true },
    { kind = "hang", x = 750, y = 157, w = 1, h = 25, col = "sky", a = 0.35, lw = 1, sway = 5, rate = 1.1, bob = true },
    { kind = "hang", x = 511, y = 228, w = 1, h = 52, col = "sky", a = 0.41, lw = 1, sway = 3, rate = 0.78, bob = true },
    { kind = "hang", x = 866, y = 88, w = 1, h = 49, col = "sky", a = 0.36, lw = 1, sway = 2, rate = 0.87, bob = true },
    { kind = "hang", x = 43, y = 240, w = 1, h = 47, col = "sky", a = 0.27, lw = 1, sway = 5, rate = 0.76, bob = true },
    { kind = "hang", x = 268, y = 204, w = 1, h = 37, col = "sky", a = 0.3, lw = 1, sway = 3, rate = 0.6, bob = true },
    { kind = "hang", x = 521, y = 128, w = 1, h = 59, col = "sky", a = 0.2, lw = 1, sway = 3, rate = 0.86, bob = true },
    { kind = "hang", x = 950, y = 101, w = 1, h = 21, col = "sky", a = 0.34, lw = 1, sway = 4, rate = 0.92, bob = true },
    { kind = "hang", x = 238, y = 215, w = 1, h = 31, col = "sky", a = 0.2, lw = 1, sway = 2, rate = 0.74, bob = true },
    { kind = "hang", x = 153, y = 178, w = 1, h = 33, col = "sky", a = 0.41, lw = 1, sway = 5, rate = 0.93, bob = true },
    { kind = "rect", x = 126, y = 179, w = 13, h = 4, col = "teal", a = 0.37 },
    { kind = "rect", x = 916, y = 102, w = 6, h = 3, col = "teal", a = 0.32 },
    { kind = "rect", x = 315, y = 164, w = 5, h = 4, col = "rust", a = 0.32 },
    { kind = "rect", x = 887, y = 141, w = 7, h = 2, col = "rust", a = 0.31 },
    { kind = "rect", x = 807, y = 100, w = 8, h = 2, col = "teal", a = 0.45 },
    { kind = "rect", x = 321, y = 131, w = 11, h = 3, col = "rust", a = 0.21 },
    { kind = "rect", x = 793, y = 229, w = 12, h = 2, col = "rust", a = 0.22 },
    { kind = "rect", x = 179, y = 216, w = 16, h = 4, col = "rust", a = 0.24 },
    { kind = "rect", x = 38, y = 53, w = 14, h = 2, col = "rust", a = 0.21 },
    { kind = "rect", x = 671, y = 176, w = 14, h = 2, col = "rust", a = 0.24 },
    { kind = "rect", x = 600, y = 139, w = 15, h = 2, col = "teal", a = 0.37 },
    { kind = "rect", x = 919, y = 240, w = 6, h = 2, col = "rust", a = 0.43 },
    { kind = "rect", x = 458, y = 47, w = 9, h = 4, col = "teal", a = 0.3 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 8, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 38, col = { 0.50, 0.90, 0.92 }, r = 102, flicker = 1.83 },
    { x = 480, y = 38, col = { 0.50, 0.90, 0.92 }, r = 88, flicker = 1.35 },
    { x = 800, y = 38, col = { 0.50, 0.90, 0.92 }, r = 90, flicker = 1.18 },
  },
  mapPos = { x = 14, y = 1, w = 3, h = 1 },
  gates = { G = "plate_f5" },
  map = [[
#############################################.##############
###########################################.#.............##
##.....####.............#########.......###########.########
##.....G.#..............%%%....%#.........###############.BB
##.....G................%%.....%%................########.BB
##..4..G.......R........%%.R.R.%%..................#####....
########......====......#########...................###....#
######................................................#...##
##.##....................................................a##
###................................#.....................###
AA..............b..................#.....b...............###
AA...................k........R...###...............R...##..
######%#######~~~~~~~#################~~~~~~~###...#########
####.....#####~~~~~~~#################~~~~~~~###############
####..8..#####~~~~~~~#################~~~x~~~###############
############################################################
############################################################
]],
  key = {
    -- TWELVE CLEAR TILES INTO A WALL -- the best run in the zone, and the
    -- last thing between you and the Tide Engine.
    ["k"] = "spineshell",
    ["a"] = "cell",
    ["8"] = "chest:chest_flood5b:scrap:20",

    -- ITS OWN FLAG, and that is the whole bug.
    --
    -- This tank and the one in flood_2 both read "tank:tank_flood", and a
    -- tank IS its flag: Entity.register("tank") returns nothing at all
    -- when G.run.flags[flag] is already set. So taking the flood_2 cell
    -- deleted this one -- it never spawned, in a room that still showed
    -- it on the map, and the run was quietly one energy tier poorer for
    -- the rest of the game (the forge gates tier N behind N+1 tanks).
    --
    -- Named for the room, like chest_flood5b above it, because "the
    -- Flooded tank" is already taken and this is the second one. Nothing
    -- else in the game shares a pickup flag -- these two were the only
    -- pair, out of seven tank flags and ten capsule flags.
    ["4"] = "tank:tank_flood5",
    ["b"] = "bubbler",
    ["R"] = "crab",
    ["x"] = "plate:plate_f5:latch",
  },
  links = {
    A = { "flood_4", "B" },
    B = { "flood_boss", "A" },
  },
}
