-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 992, h = 480, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 96, w = 1024, h = 13, col = "black", a = 0.36, py = 0.28, step = 26 },
    { kind = "girder", x = -16, y = 211, w = 1024, h = 13, col = "black", a = 0.28, py = 0.2, step = 38 },
    { kind = "girder", x = -16, y = 326, w = 1024, h = 13, col = "black", a = 0.2, py = 0.13, step = 38 },
    { kind = "column", x = -12, y = 96, w = 14, h = 384, col = "navy", a = 0.26, py = 0.17, step = 29, acc = "teal" },
    { kind = "column", x = 78, y = 96, w = 12, h = 384, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 156, y = 96, w = 18, h = 384, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 256, y = 96, w = 20, h = 384, col = "navy", a = 0.26, py = 0.17, step = 35, acc = "teal" },
    { kind = "column", x = 345, y = 96, w = 16, h = 384, col = "navy", a = 0.26, py = 0.17, step = 30, acc = "teal" },
    { kind = "column", x = 427, y = 96, w = 19, h = 384, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 529, y = 96, w = 13, h = 384, col = "navy", a = 0.26, py = 0.17, step = 32, acc = "teal" },
    { kind = "column", x = 585, y = 96, w = 26, h = 384, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 666, y = 96, w = 13, h = 384, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
    { kind = "column", x = 752, y = 96, w = 23, h = 384, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 851, y = 96, w = 18, h = 384, col = "navy", a = 0.26, py = 0.17, step = 40, acc = "teal" },
    { kind = "column", x = 917, y = 96, w = 19, h = 384, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 73, y = 224, w = 1, h = 45, col = "sky", a = 0.28, lw = 1, sway = 4, rate = 0.94, bob = true },
    { kind = "hang", x = 681, y = 333, w = 1, h = 31, col = "sky", a = 0.3, lw = 1, sway = 2, rate = 0.65, bob = true },
    { kind = "hang", x = 785, y = 235, w = 1, h = 24, col = "sky", a = 0.41, lw = 1, sway = 5, rate = 0.52, bob = true },
    { kind = "hang", x = 634, y = 172, w = 1, h = 59, col = "sky", a = 0.22, lw = 1, sway = 5, rate = 0.94, bob = true },
    { kind = "hang", x = 826, y = 293, w = 1, h = 33, col = "sky", a = 0.41, lw = 1, sway = 3, rate = 0.9, bob = true },
    { kind = "hang", x = 146, y = 214, w = 1, h = 43, col = "sky", a = 0.32, lw = 1, sway = 4, rate = 0.61, bob = true },
    { kind = "hang", x = 436, y = 369, w = 1, h = 48, col = "sky", a = 0.26, lw = 1, sway = 5, rate = 1.08, bob = true },
    { kind = "hang", x = 607, y = 393, w = 1, h = 34, col = "sky", a = 0.24, lw = 1, sway = 5, rate = 0.52, bob = true },
    { kind = "hang", x = 51, y = 309, w = 1, h = 27, col = "sky", a = 0.39, lw = 1, sway = 4, rate = 0.67, bob = true },
    { kind = "hang", x = 742, y = 358, w = 1, h = 32, col = "sky", a = 0.36, lw = 1, sway = 5, rate = 0.53, bob = true },
    { kind = "hang", x = 414, y = 267, w = 1, h = 33, col = "sky", a = 0.3, lw = 1, sway = 2, rate = 1.09, bob = true },
    { kind = "hang", x = 833, y = 259, w = 1, h = 56, col = "sky", a = 0.23, lw = 1, sway = 2, rate = 1.08, bob = true },
    { kind = "hang", x = 761, y = 270, w = 1, h = 35, col = "sky", a = 0.29, lw = 1, sway = 3, rate = 0.9, bob = true },
    { kind = "hang", x = 464, y = 242, w = 1, h = 47, col = "sky", a = 0.36, lw = 1, sway = 4, rate = 0.57, bob = true },
    { kind = "hang", x = 628, y = 177, w = 1, h = 53, col = "sky", a = 0.42, lw = 1, sway = 2, rate = 1.03, bob = true },
    { kind = "hang", x = 377, y = 417, w = 1, h = 47, col = "sky", a = 0.29, lw = 1, sway = 2, rate = 0.77, bob = true },
    { kind = "rect", x = 879, y = 393, w = 14, h = 4, col = "teal", a = 0.3 },
    { kind = "rect", x = 565, y = 399, w = 10, h = 2, col = "rust", a = 0.27 },
    { kind = "rect", x = 290, y = 369, w = 14, h = 3, col = "rust", a = 0.21 },
    { kind = "rect", x = 317, y = 364, w = 5, h = 2, col = "teal", a = 0.28 },
    { kind = "rect", x = 837, y = 197, w = 15, h = 4, col = "rust", a = 0.34 },
    { kind = "rect", x = 573, y = 306, w = 14, h = 4, col = "rust", a = 0.25 },
    { kind = "rect", x = 567, y = 381, w = 13, h = 3, col = "rust", a = 0.33 },
    { kind = "rect", x = 727, y = 240, w = 14, h = 2, col = "rust", a = 0.39 },
    { kind = "rect", x = 779, y = 414, w = 15, h = 2, col = "teal", a = 0.35 },
    { kind = "rect", x = 513, y = 189, w = 16, h = 4, col = "rust", a = 0.28 },
    { kind = "rect", x = 795, y = 285, w = 8, h = 3, col = "teal", a = 0.33 },
    { kind = "rect", x = 480, y = 138, w = 5, h = 2, col = "teal", a = 0.22 },
    { kind = "rect", x = 742, y = 413, w = 7, h = 4, col = "rust", a = 0.38 },
    { kind = "rect", x = 917, y = 123, w = 15, h = 3, col = "teal", a = 0.2 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 14, w = 1040, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 480, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 966, y = 0, w = 26, h = 480, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 165, y = 67, col = { 0.50, 0.90, 0.92 }, r = 94, flicker = 1.83 },
    { x = 496, y = 67, col = { 0.50, 0.90, 0.92 }, r = 92, flicker = 1.47 },
    { x = 826, y = 67, col = { 0.50, 0.90, 0.92 }, r = 72, flicker = 1.17 },
  },
  mapPos = { x = 11, y = 1, w = 3, h = 2 },
  map = [[
############################CCC###############################
############################..############....################
###########################..#############.4......############
###########################..#################....############
###########################...###################%############
############################...##################.%###########
##.#.#..####.####................#..#....###...###%#####..####
####..###..#.###.....................########..#.#%.###...####
###....######.............=====........####..#...##.......####
##.....#####............................###...#####=......####
##......####............................##......#..==.....####
##.........................=====........##.................###
AA.......##.............................#............##.....BB
AA...az........................................k....####....BB
#############......========.....=======........###############
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~########
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~f~~~~~~~~#######
##~~~~~~~~~~~~~~~~~~~~m~.~m~~~~~~~2~~~~~~~~~~~~~f~~~f~~~######
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###########~~~~~f~~~f~~~~~~#####
#~~~~~~~~~###########~~~~~~~~~###~~~~~~~~~~~~~~~~~~~~~~~~#####
#~~~~~~~~~~######~~~~~~~~~~~~~#~~~~~~~~~~~~~####%####~~~~#####
#~~~~~~~~~~~####~~~~~~~~~~~~~~~~~~~~~~~~~~~###~~~~~###~~######
#~~~~#~~~~~~~~~~~~#########~~~~~~~~~~~~~~~~##~~~~~~~##~~######
#~~~~##~~~~~~~f~~~~~~~~~~~~~~~~~~~~~~~~~~~~#~~~3~~~~~#~#######
##~~###~#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#######
##############################################################
##############################################################
##############################################################
##############################################################
##############################################################
]],
  key = {
    -- FIRST ONE AFTER THE WARDEN, and the first with a wall four tiles off
    -- its shoulder: bait it right and it brains itself. You have just
    -- done this to something with a health bar.
    ["k"] = "spineshell",
    ["a"] = "cell",
    ["4"] = "chest:ch_ap2:module:arcplate2",
    ["2"] = "chest:brassa_hammer:scrap:5",
    ["3"] = "chest:chest_grapple:module:grapple",
    ["f"] = "finfish",
    ["m"] = "depthmine",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "flood_warden", "B" },
    B = { "flood_5", "A" },
    C = { "flood_hub", "A" },
  },
}
