-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 416, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 83, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 30 },
    { kind = "girder", x = -16, y = 183, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 37 },
    { kind = "girder", x = -16, y = 282, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 29 },
    { kind = "column", x = -12, y = 83, w = 23, h = 332, col = "navy", a = 0.26, py = 0.17, step = 40, acc = "teal" },
    { kind = "column", x = 62, y = 83, w = 12, h = 332, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 149, y = 83, w = 24, h = 332, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 266, y = 83, w = 14, h = 332, col = "navy", a = 0.26, py = 0.17, step = 40, acc = "teal" },
    { kind = "column", x = 324, y = 83, w = 13, h = 332, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 425, y = 83, w = 23, h = 332, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 530, y = 83, w = 18, h = 332, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
    { kind = "column", x = 603, y = 83, w = 25, h = 332, col = "navy", a = 0.26, py = 0.17, step = 33, acc = "teal" },
    { kind = "column", x = 689, y = 83, w = 19, h = 332, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 783, y = 83, w = 17, h = 332, col = "navy", a = 0.26, py = 0.17, step = 26, acc = "teal" },
    { kind = "column", x = 883, y = 83, w = 20, h = 332, col = "navy", a = 0.26, py = 0.17, step = 36, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 283, y = 337, w = 1, h = 49, col = "sky", a = 0.23, lw = 1, sway = 3, rate = 1.04, bob = true },
    { kind = "hang", x = 904, y = 166, w = 1, h = 31, col = "sky", a = 0.41, lw = 1, sway = 5, rate = 0.73, bob = true },
    { kind = "hang", x = 950, y = 179, w = 1, h = 36, col = "sky", a = 0.22, lw = 1, sway = 2, rate = 0.51, bob = true },
    { kind = "hang", x = 422, y = 260, w = 1, h = 58, col = "sky", a = 0.38, lw = 1, sway = 5, rate = 0.88, bob = true },
    { kind = "hang", x = 946, y = 233, w = 1, h = 57, col = "sky", a = 0.21, lw = 1, sway = 5, rate = 0.56, bob = true },
    { kind = "hang", x = 131, y = 178, w = 1, h = 58, col = "sky", a = 0.27, lw = 1, sway = 3, rate = 0.99, bob = true },
    { kind = "hang", x = 91, y = 144, w = 1, h = 27, col = "sky", a = 0.4, lw = 1, sway = 2, rate = 0.81, bob = true },
    { kind = "hang", x = 680, y = 158, w = 1, h = 50, col = "sky", a = 0.34, lw = 1, sway = 5, rate = 0.52, bob = true },
    { kind = "hang", x = 874, y = 151, w = 1, h = 56, col = "sky", a = 0.29, lw = 1, sway = 3, rate = 0.69, bob = true },
    { kind = "hang", x = 614, y = 153, w = 1, h = 40, col = "sky", a = 0.34, lw = 1, sway = 3, rate = 0.88, bob = true },
    { kind = "hang", x = 504, y = 288, w = 1, h = 55, col = "sky", a = 0.37, lw = 1, sway = 4, rate = 0.69, bob = true },
    { kind = "hang", x = 334, y = 239, w = 1, h = 22, col = "sky", a = 0.4, lw = 1, sway = 2, rate = 0.67, bob = true },
    { kind = "hang", x = 375, y = 161, w = 1, h = 54, col = "sky", a = 0.23, lw = 1, sway = 3, rate = 1.05, bob = true },
    { kind = "hang", x = 421, y = 249, w = 1, h = 32, col = "sky", a = 0.33, lw = 1, sway = 4, rate = 0.55, bob = true },
    { kind = "hang", x = 347, y = 172, w = 1, h = 22, col = "sky", a = 0.29, lw = 1, sway = 4, rate = 0.61, bob = true },
    { kind = "hang", x = 576, y = 353, w = 1, h = 22, col = "sky", a = 0.34, lw = 1, sway = 5, rate = 0.53, bob = true },
    { kind = "rect", x = 838, y = 328, w = 10, h = 4, col = "teal", a = 0.25 },
    { kind = "rect", x = 614, y = 257, w = 6, h = 3, col = "rust", a = 0.32 },
    { kind = "rect", x = 268, y = 205, w = 16, h = 3, col = "teal", a = 0.28 },
    { kind = "rect", x = 794, y = 297, w = 9, h = 4, col = "rust", a = 0.2 },
    { kind = "rect", x = 180, y = 347, w = 16, h = 4, col = "teal", a = 0.35 },
    { kind = "rect", x = 119, y = 187, w = 12, h = 4, col = "rust", a = 0.3 },
    { kind = "rect", x = 278, y = 326, w = 11, h = 3, col = "teal", a = 0.34 },
    { kind = "rect", x = 913, y = 144, w = 9, h = 2, col = "teal", a = 0.37 },
    { kind = "rect", x = 736, y = 104, w = 14, h = 2, col = "teal", a = 0.27 },
    { kind = "rect", x = 655, y = 309, w = 12, h = 3, col = "rust", a = 0.41 },
    { kind = "rect", x = 524, y = 284, w = 9, h = 3, col = "teal", a = 0.31 },
    { kind = "rect", x = 272, y = 205, w = 12, h = 2, col = "rust", a = 0.44 },
    { kind = "rect", x = 435, y = 68, w = 13, h = 3, col = "rust", a = 0.28 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 12, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 416, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 416, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 58, col = { 0.50, 0.90, 0.92 }, r = 75, flicker = 1.85 },
    { x = 480, y = 58, col = { 0.50, 0.90, 0.92 }, r = 84, flicker = 1.58 },
    { x = 800, y = 58, col = { 0.50, 0.90, 0.92 }, r = 82, flicker = 1.95 },
  },
  mapPos = { x = 3, y = 0, w = 3, h = 2 },
  gates = { G = "hydroseals" },
  map = [[
############################################################
############################################################
##########.##########.######.....###########################
############..##....#####.........##.#######################
###.####.......#...................######.########.#########
######.........#.T.R................####............########
######.........######................###.................###
######..........####.................##...................##
##.##...........###......R...........##...................BB
#####...........###.....=====........#............R...8...BB
###..............#............................==############
##...............#..............................############
AA......b.....R..#..................k...R........###########
AA....=========..................==========.......######.###
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~####~~##
##~~~~~~~~~~~~~~~f~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#######
##~~~~~~~~~f~~~~~~~~f~~~~~~~~~~~~~~f~~~~~~~~~~~~~~~~~~~~####
##~~~~~~~~~~~~~~~~~~~~~~~~~f~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
###~~~~~~~~~f~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
######~~~~f~~~~~##~~~~~~~~~~~~f~~~~~~~~~m~~~~~~~~~~~~~~~~~##
########~~~~~~~######%%%%##~~~~~~~~~~~~~~~~#~~~~~~~~~~~~~~##
#####################~mmm###~~~~~~m~~~############GGG##~####
#####################~9~m#######~~~~##############DDD#######
##################################################DDD#######
]],
  key = {
    -- FIRST SIGHT. It is on the shelf over the lake with the crab, on the
    -- way to the Warden, and it is here to be SHOT AT and to shrug it
    -- off. There is no wall in reach to bait it into: the lesson of the
    -- first one is only that small arms do not work on it, and the
    -- answers -- the dome, and the belly -- are taught by the next
    -- three. You can also swim under this shelf and fire up through the
    -- one-ways at it, which is the other answer, found rather than
    -- taught.
    ["k"] = "spineshell",
    ["T"] = "tank:tank_flood",
    ["8"] = "chest:chest_flood2b:scrap:20",
    ["9"] = "chest:chest_scatter:weapon:scatterhex",
    ["f"] = "finfish",
    ["b"] = "bubbler",
    ["R"] = "crab",
    ["m"] = "depthmine",
  },
  links = {
    A = { "flood_1", "B" },
    B = { "flood_3", "A" },
    D = { "flood_deep1", "A" },
  },
}
