-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 416, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 83, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 38 },
    { kind = "girder", x = -16, y = 183, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 31 },
    { kind = "girder", x = -16, y = 282, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 33 },
    { kind = "column", x = -12, y = 83, w = 15, h = 332, col = "navy", a = 0.26, py = 0.17, step = 25, acc = "teal" },
    { kind = "column", x = 58, y = 83, w = 20, h = 332, col = "navy", a = 0.26, py = 0.17, step = 26, acc = "teal" },
    { kind = "column", x = 135, y = 83, w = 16, h = 332, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 225, y = 83, w = 23, h = 332, col = "navy", a = 0.26, py = 0.17, step = 30, acc = "teal" },
    { kind = "column", x = 317, y = 83, w = 19, h = 332, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 377, y = 83, w = 21, h = 332, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 467, y = 83, w = 26, h = 332, col = "navy", a = 0.26, py = 0.17, step = 28, acc = "teal" },
    { kind = "column", x = 582, y = 83, w = 25, h = 332, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 695, y = 83, w = 17, h = 332, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
    { kind = "column", x = 776, y = 83, w = 15, h = 332, col = "navy", a = 0.26, py = 0.17, step = 40, acc = "teal" },
    { kind = "column", x = 833, y = 83, w = 19, h = 332, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 912, y = 83, w = 20, h = 332, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 503, y = 350, w = 1, h = 31, col = "sky", a = 0.24, lw = 1, sway = 3, rate = 0.61, bob = true },
    { kind = "hang", x = 792, y = 132, w = 1, h = 58, col = "sky", a = 0.34, lw = 1, sway = 5, rate = 0.53, bob = true },
    { kind = "hang", x = 941, y = 334, w = 1, h = 22, col = "sky", a = 0.38, lw = 1, sway = 3, rate = 1.03, bob = true },
    { kind = "hang", x = 523, y = 124, w = 1, h = 57, col = "sky", a = 0.26, lw = 1, sway = 5, rate = 0.75, bob = true },
    { kind = "hang", x = 271, y = 362, w = 1, h = 21, col = "sky", a = 0.24, lw = 1, sway = 5, rate = 0.72, bob = true },
    { kind = "hang", x = 206, y = 297, w = 1, h = 48, col = "sky", a = 0.2, lw = 1, sway = 5, rate = 0.63, bob = true },
    { kind = "hang", x = 26, y = 161, w = 1, h = 20, col = "sky", a = 0.25, lw = 1, sway = 3, rate = 0.63, bob = true },
    { kind = "hang", x = 669, y = 131, w = 1, h = 32, col = "sky", a = 0.29, lw = 1, sway = 2, rate = 0.85, bob = true },
    { kind = "hang", x = 728, y = 367, w = 1, h = 23, col = "sky", a = 0.21, lw = 1, sway = 2, rate = 0.69, bob = true },
    { kind = "hang", x = 838, y = 204, w = 1, h = 43, col = "sky", a = 0.21, lw = 1, sway = 5, rate = 0.78, bob = true },
    { kind = "hang", x = 936, y = 311, w = 1, h = 43, col = "sky", a = 0.41, lw = 1, sway = 5, rate = 0.71, bob = true },
    { kind = "hang", x = 564, y = 156, w = 1, h = 43, col = "sky", a = 0.37, lw = 1, sway = 3, rate = 0.75, bob = true },
    { kind = "hang", x = 27, y = 175, w = 1, h = 53, col = "sky", a = 0.4, lw = 1, sway = 2, rate = 0.83, bob = true },
    { kind = "hang", x = 841, y = 231, w = 1, h = 25, col = "sky", a = 0.41, lw = 1, sway = 4, rate = 0.59, bob = true },
    { kind = "hang", x = 812, y = 133, w = 1, h = 40, col = "sky", a = 0.41, lw = 1, sway = 2, rate = 0.64, bob = true },
    { kind = "hang", x = 428, y = 290, w = 1, h = 27, col = "sky", a = 0.31, lw = 1, sway = 2, rate = 0.62, bob = true },
    { kind = "rect", x = 144, y = 304, w = 15, h = 3, col = "teal", a = 0.4 },
    { kind = "rect", x = 653, y = 276, w = 12, h = 2, col = "teal", a = 0.38 },
    { kind = "rect", x = 84, y = 80, w = 14, h = 2, col = "teal", a = 0.36 },
    { kind = "rect", x = 62, y = 129, w = 8, h = 4, col = "teal", a = 0.29 },
    { kind = "rect", x = 304, y = 65, w = 15, h = 2, col = "rust", a = 0.45 },
    { kind = "rect", x = 149, y = 229, w = 5, h = 2, col = "teal", a = 0.21 },
    { kind = "rect", x = 133, y = 260, w = 14, h = 2, col = "rust", a = 0.25 },
    { kind = "rect", x = 501, y = 198, w = 16, h = 3, col = "rust", a = 0.25 },
    { kind = "rect", x = 944, y = 86, w = 5, h = 3, col = "rust", a = 0.26 },
    { kind = "rect", x = 410, y = 358, w = 9, h = 3, col = "teal", a = 0.33 },
    { kind = "rect", x = 27, y = 209, w = 14, h = 4, col = "teal", a = 0.22 },
    { kind = "rect", x = 779, y = 81, w = 5, h = 4, col = "teal", a = 0.32 },
    { kind = "rect", x = 642, y = 133, w = 10, h = 4, col = "teal", a = 0.36 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 12, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 416, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 416, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 58, col = { 0.50, 0.90, 0.92 }, r = 83, flicker = 0.8 },
    { x = 480, y = 58, col = { 0.50, 0.90, 0.92 }, r = 82, flicker = 1.3 },
    { x = 800, y = 58, col = { 0.50, 0.90, 0.92 }, r = 76, flicker = 1.42 },
  },
  mapPos = { x = 5, y = 2, w = 2, h = 2 },
  map = [[
########AAA#################################################
########AAA#################################################
##...............................................###########
##..................................................##.#####
##......###..........................................#######
##.....................................................#####
##~~~###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~####
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
###~~~~~~~~~~~m~~~~~~~~~~~~~~~~~~~~~~f~~~~f~~~f~~~~~~~~~~~##
###~~~~~~~~~###########~~~~~~~~~~~f~~~~f~~~~~f~~~~~~~~~~~~##
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~f~~~f~~~f~~~~~~~~~~f~~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~f~~~~~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~m..~7~~~~~~f~~~~~~~~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~#############~~~~~~~~~~~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
####~~~~#########~~~f~~~~~~~~~~~~~~~~~~~~~~~f~~~~~~~f~~~~~##
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##################################################~~~#######
##################################################~~~#######
##################################################~5~#######
############################################################
############################################################
]],
  key = {
    ["m"] = "depthmine",
    ["f"] = "finfish",
    ["5"] = "capsule:cap_flood",
    ["7"] = "chest:chest_lumecore:module:lumecore",
  },
  links = {
    A = { "flood_2", "D" },
  },
}
