-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 54, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 33 },
    { kind = "girder", x = -16, y = 119, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 38 },
    { kind = "girder", x = -16, y = 184, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 39 },
    { kind = "column", x = -12, y = 54, w = 13, h = 217, col = "navy", a = 0.26, py = 0.17, step = 28, acc = "teal" },
    { kind = "column", x = 98, y = 54, w = 26, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 165, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 252, y = 54, w = 13, h = 217, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 326, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 432, y = 54, w = 21, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 521, y = 54, w = 15, h = 217, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 596, y = 54, w = 19, h = 217, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 690, y = 54, w = 21, h = 217, col = "navy", a = 0.26, py = 0.17, step = 30, acc = "teal" },
    { kind = "column", x = 771, y = 54, w = 22, h = 217, col = "navy", a = 0.26, py = 0.17, step = 31, acc = "teal" },
    { kind = "column", x = 861, y = 54, w = 26, h = 217, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 66, y = 198, w = 1, h = 24, col = "sky", a = 0.29, lw = 1, sway = 3, rate = 0.72, bob = true },
    { kind = "hang", x = 155, y = 195, w = 1, h = 29, col = "sky", a = 0.33, lw = 1, sway = 2, rate = 0.99, bob = true },
    { kind = "hang", x = 765, y = 164, w = 1, h = 58, col = "sky", a = 0.25, lw = 1, sway = 5, rate = 0.54, bob = true },
    { kind = "hang", x = 343, y = 124, w = 1, h = 38, col = "sky", a = 0.41, lw = 1, sway = 3, rate = 0.56, bob = true },
    { kind = "hang", x = 587, y = 190, w = 1, h = 32, col = "sky", a = 0.36, lw = 1, sway = 4, rate = 0.52, bob = true },
    { kind = "hang", x = 778, y = 166, w = 1, h = 25, col = "sky", a = 0.32, lw = 1, sway = 4, rate = 0.56, bob = true },
    { kind = "hang", x = 523, y = 169, w = 1, h = 33, col = "sky", a = 0.31, lw = 1, sway = 3, rate = 0.78, bob = true },
    { kind = "hang", x = 773, y = 134, w = 1, h = 43, col = "sky", a = 0.22, lw = 1, sway = 3, rate = 0.67, bob = true },
    { kind = "hang", x = 859, y = 102, w = 1, h = 36, col = "sky", a = 0.38, lw = 1, sway = 3, rate = 0.76, bob = true },
    { kind = "hang", x = 378, y = 117, w = 1, h = 49, col = "sky", a = 0.26, lw = 1, sway = 5, rate = 0.81, bob = true },
    { kind = "hang", x = 534, y = 170, w = 1, h = 40, col = "sky", a = 0.36, lw = 1, sway = 4, rate = 0.74, bob = true },
    { kind = "hang", x = 390, y = 184, w = 1, h = 46, col = "sky", a = 0.22, lw = 1, sway = 3, rate = 1, bob = true },
    { kind = "hang", x = 334, y = 101, w = 1, h = 36, col = "sky", a = 0.27, lw = 1, sway = 3, rate = 0.74, bob = true },
    { kind = "hang", x = 480, y = 100, w = 1, h = 54, col = "sky", a = 0.27, lw = 1, sway = 4, rate = 0.92, bob = true },
    { kind = "hang", x = 630, y = 186, w = 1, h = 41, col = "sky", a = 0.38, lw = 1, sway = 5, rate = 0.93, bob = true },
    { kind = "hang", x = 154, y = 130, w = 1, h = 28, col = "sky", a = 0.24, lw = 1, sway = 4, rate = 1.08, bob = true },
    { kind = "rect", x = 460, y = 101, w = 12, h = 4, col = "teal", a = 0.32 },
    { kind = "rect", x = 353, y = 104, w = 8, h = 3, col = "teal", a = 0.44 },
    { kind = "rect", x = 428, y = 69, w = 7, h = 4, col = "rust", a = 0.21 },
    { kind = "rect", x = 90, y = 53, w = 14, h = 2, col = "rust", a = 0.38 },
    { kind = "rect", x = 793, y = 158, w = 14, h = 2, col = "teal", a = 0.24 },
    { kind = "rect", x = 836, y = 59, w = 9, h = 2, col = "teal", a = 0.4 },
    { kind = "rect", x = 60, y = 107, w = 5, h = 3, col = "rust", a = 0.42 },
    { kind = "rect", x = 419, y = 137, w = 14, h = 4, col = "rust", a = 0.27 },
    { kind = "rect", x = 852, y = 134, w = 10, h = 3, col = "teal", a = 0.37 },
    { kind = "rect", x = 601, y = 218, w = 16, h = 2, col = "teal", a = 0.34 },
    { kind = "rect", x = 187, y = 200, w = 9, h = 4, col = "rust", a = 0.42 },
    { kind = "rect", x = 914, y = 205, w = 13, h = 4, col = "teal", a = 0.41 },
    { kind = "rect", x = 204, y = 158, w = 8, h = 3, col = "rust", a = 0.28 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 8, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 38, col = { 0.50, 0.90, 0.92 }, r = 93, flicker = 1.97 },
    { x = 480, y = 38, col = { 0.50, 0.90, 0.92 }, r = 85, flicker = 0.91 },
    { x = 800, y = 38, col = { 0.50, 0.90, 0.92 }, r = 77, flicker = 1.04 },
  },
  mapPos = { x = 0, y = 1, w = 3, h = 1 },
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##........................1...............................##
##......................=======...........................##
##........................................................##
##........................................................##
AA...............f......................f.................BB
AA....z.....................b.............................BB
##############~~~~~~~~~#############~~~~~~~~~~~#############
##############~~~~~~~~~#############~~~~~~~~~~~#############
##############~~~~~~~~~#############~~~~~~~~~~~#############
############################################################
############################################################
]],
  key = {
    ["z"] = "checkpoint",
    ["f"] = "finfish",
    ["b"] = "bubbler",
    ["1"] = "sign:sign_flood",
  },
  links = {
    A = { "moss_boss", "B" },
    B = { "flood_2", "A" },
  },
}
