-- generated by scripts/genrooms.py
return {
  zone = "flooded", music = "flooded",
  arena = "tideengine",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 352, col = "deepsea", a = 0.1, a2 = 0.4, py = 0.04 },
    { kind = "girder", x = -16, y = 70, w = 992, h = 13, col = "black", a = 0.36, py = 0.28, step = 26 },
    { kind = "girder", x = -16, y = 154, w = 992, h = 13, col = "black", a = 0.28, py = 0.2, step = 33 },
    { kind = "girder", x = -16, y = 239, w = 992, h = 13, col = "black", a = 0.2, py = 0.13, step = 33 },
    { kind = "column", x = -12, y = 70, w = 20, h = 281, col = "navy", a = 0.26, py = 0.17, step = 27, acc = "teal" },
    { kind = "column", x = 100, y = 70, w = 24, h = 281, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 189, y = 70, w = 16, h = 281, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 298, y = 70, w = 25, h = 281, col = "navy", a = 0.26, py = 0.17, step = 34, acc = "teal" },
    { kind = "column", x = 386, y = 70, w = 15, h = 281, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 441, y = 70, w = 21, h = 281, col = "navy", a = 0.26, py = 0.17, step = 39, acc = "teal" },
    { kind = "column", x = 522, y = 70, w = 12, h = 281, col = "navy", a = 0.26, py = 0.17, step = 39, acc = "teal" },
    { kind = "column", x = 592, y = 70, w = 17, h = 281, col = "navy", a = 0.26, py = 0.17, step = 28, acc = "teal" },
    { kind = "column", x = 669, y = 70, w = 16, h = 281, col = "navy", a = 0.26, py = 0.17, step = 37, acc = "teal" },
    { kind = "column", x = 728, y = 70, w = 25, h = 281, col = "navy", a = 0.26, py = 0.17, step = 38, acc = "teal" },
    { kind = "column", x = 822, y = 70, w = 23, h = 281, col = "navy", a = 0.26, py = 0.17, step = 24, acc = "teal" },
    { kind = "column", x = 891, y = 70, w = 17, h = 281, col = "navy", a = 0.26, py = 0.17, step = 25, acc = "teal" },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 780, y = 271, w = 1, h = 32, col = "sky", a = 0.3, lw = 1, sway = 3, rate = 1, bob = true },
    { kind = "hang", x = 275, y = 306, w = 1, h = 57, col = "sky", a = 0.24, lw = 1, sway = 3, rate = 0.58, bob = true },
    { kind = "hang", x = 160, y = 125, w = 1, h = 45, col = "sky", a = 0.24, lw = 1, sway = 4, rate = 0.52, bob = true },
    { kind = "hang", x = 926, y = 191, w = 1, h = 21, col = "sky", a = 0.22, lw = 1, sway = 2, rate = 1.03, bob = true },
    { kind = "hang", x = 823, y = 209, w = 1, h = 21, col = "sky", a = 0.36, lw = 1, sway = 3, rate = 0.68, bob = true },
    { kind = "hang", x = 578, y = 266, w = 1, h = 32, col = "sky", a = 0.32, lw = 1, sway = 3, rate = 1.04, bob = true },
    { kind = "hang", x = 636, y = 268, w = 1, h = 58, col = "sky", a = 0.25, lw = 1, sway = 4, rate = 0.92, bob = true },
    { kind = "hang", x = 408, y = 174, w = 1, h = 39, col = "sky", a = 0.28, lw = 1, sway = 5, rate = 0.63, bob = true },
    { kind = "hang", x = 43, y = 169, w = 1, h = 49, col = "sky", a = 0.39, lw = 1, sway = 3, rate = 0.88, bob = true },
    { kind = "hang", x = 50, y = 285, w = 1, h = 39, col = "sky", a = 0.32, lw = 1, sway = 3, rate = 0.78, bob = true },
    { kind = "hang", x = 815, y = 221, w = 1, h = 34, col = "sky", a = 0.23, lw = 1, sway = 5, rate = 0.6, bob = true },
    { kind = "hang", x = 622, y = 154, w = 1, h = 39, col = "sky", a = 0.34, lw = 1, sway = 3, rate = 0.77, bob = true },
    { kind = "hang", x = 945, y = 115, w = 1, h = 39, col = "sky", a = 0.22, lw = 1, sway = 2, rate = 0.56, bob = true },
    { kind = "hang", x = 916, y = 211, w = 1, h = 45, col = "sky", a = 0.35, lw = 1, sway = 3, rate = 0.84, bob = true },
    { kind = "hang", x = 93, y = 173, w = 1, h = 25, col = "sky", a = 0.3, lw = 1, sway = 4, rate = 0.83, bob = true },
    { kind = "hang", x = 22, y = 109, w = 1, h = 31, col = "sky", a = 0.25, lw = 1, sway = 4, rate = 0.72, bob = true },
    { kind = "rect", x = 677, y = 70, w = 11, h = 4, col = "teal", a = 0.37 },
    { kind = "rect", x = 775, y = 140, w = 9, h = 3, col = "teal", a = 0.42 },
    { kind = "rect", x = 363, y = 102, w = 11, h = 3, col = "rust", a = 0.44 },
    { kind = "rect", x = 243, y = 56, w = 15, h = 4, col = "teal", a = 0.34 },
    { kind = "rect", x = 135, y = 168, w = 12, h = 2, col = "teal", a = 0.45 },
    { kind = "rect", x = 341, y = 75, w = 11, h = 3, col = "rust", a = 0.25 },
    { kind = "rect", x = 265, y = 196, w = 6, h = 4, col = "teal", a = 0.38 },
    { kind = "rect", x = 827, y = 167, w = 12, h = 4, col = "teal", a = 0.44 },
    { kind = "rect", x = 257, y = 157, w = 15, h = 3, col = "rust", a = 0.28 },
    { kind = "rect", x = 277, y = 70, w = 5, h = 4, col = "teal", a = 0.29 },
    { kind = "rect", x = 361, y = 273, w = 13, h = 4, col = "teal", a = 0.21 },
    { kind = "rect", x = 322, y = 244, w = 9, h = 3, col = "teal", a = 0.23 },
    { kind = "rect", x = 926, y = 55, w = 14, h = 2, col = "rust", a = 0.45 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 1008, h = 16, col = "black", a = 0.86, py = -0.12, step = 34 },
    { kind = "band", x = 0, y = 0, w = 26, h = 352, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 352, col = "navy", a = 0.45, a2 = 0.45, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 49, col = { 0.50, 0.90, 0.92 }, r = 84, flicker = 1.61 },
    { x = 480, y = 49, col = { 0.50, 0.90, 0.92 }, r = 96, flicker = 0.98 },
    { x = 800, y = 49, col = { 0.50, 0.90, 0.92 }, r = 87, flicker = 1.91 },
  },
  mapPos = { x = 17, y = 1, w = 3, h = 1 },
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##........................................................##
####......................................................##
##........................................................##
##........................................................##
##..........=======......................=======..........##
##.......................................................###
##........................................................##
##.....===........................................===.....##
AA.......................#................................##
AA............#.....t....#.......F..#.....................##
#################################F#######.########.#########
############################################################
############################################################
############################################################
############################################################
]],
  key = {
    ["t"] = "boss:tideengine",
  },
  links = {
    F = { "deep_stair_2", "D", req = "boss_tideengine" },
    A = { "flood_5", "B" },
  },
}
