-- generated by scripts/genrooms.py
return {
  zone = "furnace", music = "furnace",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "maroon", a = 0.1, a2 = 0.42, py = 0.05 },
    { kind = "rect", x = -18, y = 89, w = 59, h = 183, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 84, y = 125, w = 48, h = 147, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 183, y = 136, w = 43, h = 136, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 266, y = 173, w = 47, h = 99, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 356, y = 111, w = 58, h = 161, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 460, y = 165, w = 41, h = 107, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 539, y = 106, w = 42, h = 166, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 627, y = 147, w = 36, h = 125, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 706, y = 182, w = 31, h = 90, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 760, y = 121, w = 55, h = 151, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 853, y = 153, w = 31, h = 119, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 939, y = 83, w = 48, h = 189, col = "black", a = 0.4, py = 0.22 },
    { kind = "girder", x = -16, y = 43, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 34 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 26 },
    { kind = "shaft", x = 559, y = 95, w = 47, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -10, ph = 1.77 },
    { kind = "shaft", x = 699, y = 95, w = 36, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -9, ph = 5.96 },
    { kind = "shaft", x = 155, y = 95, w = 31, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 14, ph = 3.67 },
    { kind = "shaft", x = 777, y = 95, w = 53, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -2, ph = 2.09 },
    { kind = "shaft", x = 616, y = 95, w = 28, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -8, ph = 4.56 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 408, y = 80, w = 7, h = 29, col = "rust", a = 0.44 },
    { kind = "rect", x = 653, y = 175, w = 3, h = 17, col = "rust", a = 0.25 },
    { kind = "rect", x = 349, y = 141, w = 5, h = 15, col = "rust", a = 0.48 },
    { kind = "rect", x = 499, y = 89, w = 4, h = 27, col = "rust", a = 0.32 },
    { kind = "rect", x = 350, y = 166, w = 6, h = 25, col = "rust", a = 0.28 },
    { kind = "rect", x = 396, y = 58, w = 3, h = 16, col = "rust", a = 0.28 },
    { kind = "rect", x = 240, y = 199, w = 4, h = 14, col = "rust", a = 0.34 },
    { kind = "rect", x = 660, y = 151, w = 3, h = 28, col = "rust", a = 0.35 },
    { kind = "rect", x = 499, y = 105, w = 4, h = 27, col = "rust", a = 0.33 },
    { kind = "rect", x = 106, y = 94, w = 6, h = 34, col = "rust", a = 0.41 },
    { kind = "rect", x = 382, y = 216, w = 5, h = 10, col = "rust", a = 0.31 },
    { kind = "rect", x = 126, y = 192, w = 4, h = 28, col = "rust", a = 0.4 },
    { kind = "rect", x = 249, y = 217, w = 4, h = 29, col = "rust", a = 0.27 },
    { kind = "rect", x = 831, y = 82, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 833, y = 84, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 381, y = 95, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 383, y = 97, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 720, y = 100, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 722, y = 102, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 685, y = 104, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 687, y = 106, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 288, y = 88, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 290, y = 90, w = 4, h = 6, col = "magma", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 13, w = 1008, h = 16, col = "black", a = 0.9, py = -0.13, step = 32 },
    { kind = "hang", x = 213, y = 29, w = 2, h = 54, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 561, y = 29, w = 2, h = 31, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 241, y = 29, w = 2, h = 40, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 712, y = 29, w = 2, h = 37, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 480, y = 29, w = 2, h = 31, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 255, y = 29, w = 2, h = 26, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 835, y = 87, col = { 1.00, 0.52, 0.20 }, r = 54, flicker = 6.87 },
    { x = 385, y = 100, col = { 1.00, 0.52, 0.20 }, r = 62, flicker = 4.42 },
    { x = 724, y = 105, col = { 1.00, 0.52, 0.20 }, r = 70, flicker = 5 },
    { x = 689, y = 109, col = { 1.00, 0.52, 0.20 }, r = 47, flicker = 6.99 },
    { x = 292, y = 93, col = { 1.00, 0.52, 0.20 }, r = 47, flicker = 5.97 },
    { x = 617, y = 239, col = { 1.00, 0.40, 0.14 }, r = 91, flicker = 3.29 },
  },
  mapPos = { x = 11, y = 2, w = 3, h = 1 },
  hot = true,
  gates = { G = "plate_furn5" },
  map = [[
############################################################
############################################################
##........................V................#.....#........##
##.........................................#..5..#........##
##..........................................GGGGG.........##
##....................=====...............................##
##..............a................q......w.................##
##............................#####.........=====.........##
##........................................................##
##.........................................=====..a.......##
AA........................................................BB
AA..........ccc...ccc...ccc...ccc...ccc...ccc...ccc..w.x..BB
##########LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL#########
##########LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL#########
##########LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL#########
############################################################
############################################################
]],
  key = {
    ["V"] = "vent:d:3.4",
    ["5"] = "capsule:cap_furn",
    ["x"] = "plate:plate_furn5:latch",
    ["q"] = "chest:ch_cryo:module:cryocoils",
    ["a"] = "cinderbat",
    ["w"] = "welder",
  },
  links = {
    A = { "furn_4", "B" },
    B = { "furn_6", "A" },
  },
}
