-- generated by scripts/genrooms.py
return {
  zone = "furnace", music = "furnace",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "maroon", a = 0.1, a2 = 0.42, py = 0.05 },
    { kind = "rect", x = -18, y = 143, w = 60, h = 129, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 89, y = 169, w = 56, h = 103, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 163, y = 152, w = 38, h = 120, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 227, y = 164, w = 50, h = 108, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 297, y = 154, w = 49, h = 118, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 375, y = 135, w = 53, h = 137, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 477, y = 82, w = 41, h = 190, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 548, y = 143, w = 55, h = 129, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 636, y = 171, w = 57, h = 101, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 744, y = 114, w = 55, h = 158, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 819, y = 96, w = 46, h = 176, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 921, y = 144, w = 60, h = 128, col = "black", a = 0.4, py = 0.22 },
    { kind = "girder", x = -16, y = 43, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 35 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 31 },
    { kind = "shaft", x = 45, y = 95, w = 32, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 1, ph = 2.63 },
    { kind = "shaft", x = 67, y = 95, w = 39, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 4, ph = 6.03 },
    { kind = "shaft", x = 656, y = 95, w = 54, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 1, ph = 5.22 },
    { kind = "shaft", x = 551, y = 95, w = 44, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 14, ph = 2.86 },
    { kind = "shaft", x = 813, y = 95, w = 32, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -7, ph = 2.84 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 873, y = 230, w = 5, h = 26, col = "rust", a = 0.28 },
    { kind = "rect", x = 560, y = 157, w = 3, h = 26, col = "rust", a = 0.33 },
    { kind = "rect", x = 461, y = 154, w = 4, h = 29, col = "rust", a = 0.39 },
    { kind = "rect", x = 473, y = 153, w = 5, h = 30, col = "rust", a = 0.39 },
    { kind = "rect", x = 30, y = 100, w = 3, h = 18, col = "rust", a = 0.35 },
    { kind = "rect", x = 876, y = 62, w = 6, h = 31, col = "rust", a = 0.34 },
    { kind = "rect", x = 84, y = 115, w = 3, h = 11, col = "rust", a = 0.25 },
    { kind = "rect", x = 735, y = 56, w = 5, h = 33, col = "rust", a = 0.3 },
    { kind = "rect", x = 666, y = 165, w = 6, h = 15, col = "rust", a = 0.41 },
    { kind = "rect", x = 20, y = 227, w = 4, h = 10, col = "rust", a = 0.4 },
    { kind = "rect", x = 381, y = 96, w = 6, h = 17, col = "rust", a = 0.49 },
    { kind = "rect", x = 877, y = 243, w = 7, h = 18, col = "rust", a = 0.28 },
    { kind = "rect", x = 610, y = 215, w = 7, h = 15, col = "rust", a = 0.41 },
    { kind = "rect", x = 667, y = 120, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 669, y = 122, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 361, y = 159, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 363, y = 161, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 200, y = 76, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 202, y = 78, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 846, y = 81, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 848, y = 83, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 905, y = 127, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 907, y = 129, w = 4, h = 6, col = "magma", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 13, w = 1008, h = 16, col = "black", a = 0.9, py = -0.13, step = 32 },
    { kind = "hang", x = 900, y = 29, w = 2, h = 45, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 56, y = 29, w = 2, h = 37, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 144, y = 29, w = 2, h = 47, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 863, y = 29, w = 2, h = 44, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 329, y = 29, w = 2, h = 46, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 203, y = 29, w = 2, h = 52, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 671, y = 125, col = { 1.00, 0.52, 0.20 }, r = 54, flicker = 6.05 },
    { x = 365, y = 164, col = { 1.00, 0.52, 0.20 }, r = 46, flicker = 5.47 },
    { x = 204, y = 81, col = { 1.00, 0.52, 0.20 }, r = 48, flicker = 4.93 },
    { x = 850, y = 86, col = { 1.00, 0.52, 0.20 }, r = 61, flicker = 4.04 },
    { x = 909, y = 132, col = { 1.00, 0.52, 0.20 }, r = 68, flicker = 4.27 },
    { x = 45, y = 239, col = { 1.00, 0.40, 0.14 }, r = 86, flicker = 2.51 },
  },
  mapPos = { x = 0, y = 2, w = 3, h = 1 },
  gates = { G = "boss_vessel8" },
  map = [[
######AAA###################################################
######AAA###################################################
##EEG.....................................................##
####===...................................................##
##........................................................CC
##........................................................CC
##......====................................==============##
##........................................................##
##..............4.a......=======......o...................##
##.======.......#####................#####................##
DD........................................................BB
DD..........................z.....................o.......BB
##############LLLLLLLLL###########LLLLLLLLLLL###############
##############LLLLLLLLL###########LLLLLLLLLLL###############
##############LLLLLLLLL###########LLLLLLLLLLL###############
############################################################
############################################################
]],
  key = {
    ["4"] = "chest:ch_ap3:module:arcplate3",
    ["a"] = "cinderbat",
    ["o"] = "slagblob",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "furn_1", "B" },
    B = { "furn_3", "A" },
    C = { "furn_cache", "A" },
    D = { "scrap_1", "A" },
    E = { "scrap_boss", "E" },
  },
}
