-- generated by scripts/genrooms.py
return {
  zone = "furnace", music = "furnace",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "maroon", a = 0.1, a2 = 0.42, py = 0.05 },
    { kind = "rect", x = -18, y = 137, w = 53, h = 135, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 74, y = 180, w = 43, h = 92, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 154, y = 149, w = 38, h = 123, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 248, y = 191, w = 45, h = 81, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 335, y = 145, w = 55, h = 127, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 413, y = 145, w = 53, h = 127, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 497, y = 165, w = 59, h = 107, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 609, y = 131, w = 32, h = 141, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 670, y = 77, w = 50, h = 195, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 746, y = 99, w = 31, h = 173, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 804, y = 94, w = 60, h = 178, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 883, y = 99, w = 54, h = 173, col = "black", a = 0.4, py = 0.22 },
    { kind = "girder", x = -16, y = 43, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 34 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.42, py = 0.28, step = 29 },
    { kind = "shaft", x = 495, y = 95, w = 44, h = 163, col = "magma", a = 0.2, py = 0.14, skew = 13, ph = 4.38 },
    { kind = "shaft", x = 698, y = 95, w = 33, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -7, ph = 1.78 },
    { kind = "shaft", x = 525, y = 95, w = 40, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -5, ph = 5.48 },
    { kind = "shaft", x = 731, y = 95, w = 33, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -14, ph = 4.42 },
    { kind = "shaft", x = 860, y = 95, w = 40, h = 163, col = "magma", a = 0.2, py = 0.14, skew = -3, ph = 3.91 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 842, y = 127, w = 3, h = 28, col = "rust", a = 0.35 },
    { kind = "rect", x = 715, y = 106, w = 5, h = 26, col = "rust", a = 0.31 },
    { kind = "rect", x = 203, y = 74, w = 5, h = 12, col = "rust", a = 0.27 },
    { kind = "rect", x = 451, y = 57, w = 6, h = 34, col = "rust", a = 0.37 },
    { kind = "rect", x = 60, y = 137, w = 7, h = 27, col = "rust", a = 0.25 },
    { kind = "rect", x = 838, y = 80, w = 5, h = 10, col = "rust", a = 0.28 },
    { kind = "rect", x = 422, y = 99, w = 6, h = 19, col = "rust", a = 0.47 },
    { kind = "rect", x = 252, y = 217, w = 4, h = 23, col = "rust", a = 0.49 },
    { kind = "rect", x = 16, y = 54, w = 4, h = 24, col = "rust", a = 0.38 },
    { kind = "rect", x = 220, y = 136, w = 5, h = 16, col = "rust", a = 0.46 },
    { kind = "rect", x = 233, y = 218, w = 6, h = 12, col = "rust", a = 0.38 },
    { kind = "rect", x = 604, y = 103, w = 3, h = 10, col = "rust", a = 0.27 },
    { kind = "rect", x = 695, y = 55, w = 6, h = 11, col = "rust", a = 0.27 },
    { kind = "rect", x = 708, y = 54, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 710, y = 56, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 515, y = 151, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 517, y = 153, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 180, y = 156, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 182, y = 158, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 827, y = 130, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 829, y = 132, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 854, y = 70, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 856, y = 72, w = 4, h = 6, col = "magma", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 13, w = 1008, h = 16, col = "black", a = 0.9, py = -0.13, step = 32 },
    { kind = "hang", x = 188, y = 29, w = 2, h = 39, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 158, y = 29, w = 2, h = 30, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 56, y = 29, w = 2, h = 44, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 231, y = 29, w = 2, h = 57, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 578, y = 29, w = 2, h = 42, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 635, y = 29, w = 2, h = 44, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "band", x = 0, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
    { kind = "band", x = 936, y = 0, w = 24, h = 272, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 712, y = 59, col = { 1.00, 0.52, 0.20 }, r = 56, flicker = 5.7 },
    { x = 519, y = 156, col = { 1.00, 0.52, 0.20 }, r = 62, flicker = 5.23 },
    { x = 184, y = 161, col = { 1.00, 0.52, 0.20 }, r = 56, flicker = 6.08 },
    { x = 831, y = 135, col = { 1.00, 0.52, 0.20 }, r = 58, flicker = 4.4 },
    { x = 858, y = 75, col = { 1.00, 0.52, 0.20 }, r = 54, flicker = 6.91 },
    { x = 870, y = 239, col = { 1.00, 0.40, 0.14 }, r = 112, flicker = 2.41 },
  },
  mapPos = { x = 3, y = 2, w = 3, h = 1 },
  hasTeleporter = true,
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##......................=======...........................##
##........................................................##
##........................................................##
AA........................................................BB
AA....1...s.....t.............w.......w.....e.............BB
############################################%###############
##########################################.....#############
##########################################..8..#############
############################################################
############################################################
]],
  key = {
    ["8"] = "chest:chest_furn3b:scrap:25",

    ["s"] = "checkpoint",
    ["t"] = "teleporter:furnace",
    ["1"] = "sign:sign_depths",
    ["w"] = "welder",
    ["e"] = "shieldbug",
  },
  links = {
    A = { "furn_2", "B" },
    B = { "furn_golem", "A" },
  },
}
