-- generated by scripts/genrooms.py
return {
  zone = "furnace", music = "furnace",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 512, col = "maroon", a = 0.1, a2 = 0.42, py = 0.05 },
    { kind = "rect", x = -18, y = 238, w = 48, h = 274, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 70, y = 259, w = 38, h = 253, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 144, y = 212, w = 51, h = 300, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 245, y = 325, w = 54, h = 187, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 354, y = 275, w = 42, h = 237, col = "black", a = 0.4, py = 0.22 },
    { kind = "rect", x = 419, y = 357, w = 43, h = 155, col = "black", a = 0.4, py = 0.22 },
    { kind = "girder", x = -16, y = 81, w = 512, h = 14, col = "black", a = 0.42, py = 0.28, step = 26 },
    { kind = "girder", x = -16, y = 204, w = 512, h = 14, col = "black", a = 0.42, py = 0.28, step = 31 },
    { kind = "shaft", x = 96, y = 179, w = 49, h = 307, col = "magma", a = 0.2, py = 0.14, skew = 4, ph = 0.01 },
    { kind = "shaft", x = 39, y = 179, w = 45, h = 307, col = "magma", a = 0.2, py = 0.14, skew = 10, ph = 4.1 },
    { kind = "shaft", x = 24, y = 179, w = 54, h = 307, col = "magma", a = 0.2, py = 0.14, skew = 8, ph = 4.36 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 36, y = 431, w = 6, h = 10, col = "rust", a = 0.27 },
    { kind = "rect", x = 193, y = 278, w = 6, h = 11, col = "rust", a = 0.44 },
    { kind = "rect", x = 406, y = 153, w = 7, h = 23, col = "rust", a = 0.43 },
    { kind = "rect", x = 20, y = 451, w = 7, h = 23, col = "rust", a = 0.47 },
    { kind = "rect", x = 53, y = 207, w = 5, h = 28, col = "rust", a = 0.31 },
    { kind = "rect", x = 458, y = 243, w = 6, h = 17, col = "rust", a = 0.32 },
    { kind = "rect", x = 139, y = 200, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 141, y = 202, w = 4, h = 6, col = "magma", a = 1 },
    { kind = "rect", x = 311, y = 252, w = 8, h = 10, col = "rust", a = 0.9 },
    { kind = "rect", x = 313, y = 254, w = 4, h = 6, col = "magma", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 25, w = 528, h = 16, col = "black", a = 0.9, py = -0.13, step = 32 },
    { kind = "hang", x = 42, y = 41, w = 2, h = 35, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 91, y = 41, w = 2, h = 43, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 50, y = 41, w = 2, h = 39, col = "black", a = 0.85, py = -0.13, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "band", x = 0, y = 0, w = 24, h = 512, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
    { kind = "band", x = 456, y = 0, w = 24, h = 512, col = "black", a = 0.5, a2 = 0.5, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 143, y = 205, col = { 1.00, 0.52, 0.20 }, r = 51, flicker = 5.5 },
    { x = 315, y = 257, col = { 1.00, 0.52, 0.20 }, r = 49, flicker = 5.7 },
    { x = 202, y = 450, col = { 1.00, 0.40, 0.14 }, r = 89, flicker = 2.78 },
  },
  mapPos = { x = 14, y = 1, w = 1, h = 2 },
  hot = true,
  gates = { G = "plate_furn6" },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##..........................##
AA..........................##
AA..........................##
#########...................##
##.......===................##
##..........................##
##............x.............##
##..........#######.........##
##.................===......##
##..........................##
##..........................##
##..................##########
##...............===........##
##..........................##
##........a.................##
##......#########...........##
##..===.....................##
##..........................##
##..........................##
#######.....................##
##.................G##########
##........z..b.a...G........##
##....########...##G..4.....##
##LLLLLLLLLLL#...#LL##########
##LLLLLLLLLLL#...#LL##########
##############BBB#############
##############BBB#############
]],
  key = {
    ["b"] = "cell",
    ["x"] = "plate:plate_furn6:latch",
    ["4"] = "tank:tank_furn",
    ["z"] = "checkpoint",
    ["a"] = "cinderbat",
  },
  links = {
    A = { "furn_5", "B" },
    B = { "furn_boss", "A" },
  },
}
