-- generated by scripts/genrooms.py
return {
  zone = "furnace", music = "furnace",
  -- ------------------------------------------------------------------
  -- THE FURNACE MOUTH -- the line is still running.
  --
  -- Three layers, and the only difference between them is where in the
  -- draw order they sit: backdrop is BEHIND the rock, scenery is over
  -- the rock but behind the bots, foreground is in front of everything.
  -- py < 0 is nearer than the world; py > 0 is further away.
  -- ------------------------------------------------------------------
  backdrop = {
    -- Furnace mouths still burning behind the wall, on a slow cycle.
    -- The Crucible made ten thousand perfect parts and the line never
    -- got the message; the light back there is the line still running.
    { kind = "rect", x = 60, y = 150, w = 90, h = 60, col = "maroon", a = 0.85, py = 0.28 },
    { kind = "band", x = 63, y = 153, w = 84, h = 54, col = "magma", a = 0.5, a2 = 0.12, py = 0.28 },
    { kind = "rect", x = 300, y = 300, w = 110, h = 70, col = "maroon", a = 0.85, py = 0.28 },
    { kind = "band", x = 303, y = 303, w = 104, h = 64, col = "magma", a = 0.5, a2 = 0.12, py = 0.28 },
    -- gantry behind everything
    { kind = "girder", x = -20, y = 60, w = 520, h = 15, col = "black", a = 0.55, py = 0.34, step = 32 },
    { kind = "girder", x = -20, y = 210, w = 520, h = 15, col = "black", a = 0.55, py = 0.34, step = 32 },
    { kind = "girder", x = -20, y = 360, w = 520, h = 15, col = "black", a = 0.55, py = 0.34, step = 32 },
    { kind = "column", x = 105, y = 20, w = 13, h = 472, col = "black", a = 0.5, py = 0.4, acc = "rust" },
    { kind = "column", x = 355, y = 20, w = 13, h = 472, col = "black", a = 0.5, py = 0.4, acc = "rust" },
  },
  scenery = {
    -- heat haze rising off the floor
    { kind = "band", x = 0, y = 362, w = 480, h = 150, col = "magma", a = 0, a2 = 0.13 },
  },
  foreground = {
    -- chains and a near gantry: the works, passing in front
    { kind = "girder", x = -20, y = 26, w = 520, h = 18, col = "black", a = 0.94, py = -0.14, step = 36 },
    { kind = "hang", x = 150, y = 44, w = 2, h = 70, col = "black", a = 0.9, py = -0.14, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 340, y = 44, w = 2, h = 52, col = "black", a = 0.9, py = -0.14, lw = 2, sway = 4, rate = 0.45, bob = true },
    { kind = "hang", x = 250, y = 300, w = 2, h = 58, col = "black", a = 0.9, py = -0.14, lw = 2, sway = 4, rate = 0.45, bob = true },
  },
  lights = {
    { x = 70, y = 470, r = 60, col = { 1.00, 0.55, 0.22 }, flicker = 6.5 },
    { x = 400, y = 250, r = 52, col = { 1.00, 0.55, 0.22 }, flicker = 5.2 },
    { x = 210, y = 140, r = 44, col = { 1.00, 0.55, 0.22 }, flicker = 7.3 },
  },
  mapPos = { x = 0, y = 0, w = 1, h = 2 },
  gates = {},
  map = [[
##############################
##############################
##..........................##
##..a..a....................##
##....a.....................##
##..b.......................##
#########...................##
##........===...............##
##..........................##
##..................=====...##
##..........##..............##
##.a........##....n.........##
####........##..............##
##.....n....##..............##
##..........##..........n...##
##..........##..............##
##.........a##..............##
##.........###............a.##
##.........###...a..........##
##.........###..............##
##..........##......n...a...##
##..n.......#...............##
##.........=#=..............##
##..........##..............##
##..........##...a..........##
AA..........#...............##
AA...1......##..............##
##======....##..............##
##LLLLLLLLLLL#LLLLLL#...#LLL##
##LLLLL..dLLL#...LLL#...#LLL##
#####################BBB######
#####################BdB######
]],
  key = {
    ["n"] = "anchor",
    ["a"] = "cinderbat",
    ["1"] = "sign:sign_furnace",
    ["b"] = "cell",
    ["d"] = "updraft:23",
  },
  links = {
    A = { "deep_stair_1", "C" },
    B = { "furn_2", "A" },
  },
}
