-- generated by scripts/genvanes.py (The Drift Vanes)
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 544, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 119, w = 181, h = 25, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 253, y = 119, w = 209, h = 27, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 239, w = 179, h = 23, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 195, y = 239, w = 100, h = 15, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 381, y = 239, w = 130, h = 19, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 337, w = 90, h = 22, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 130, y = 337, w = 124, h = 27, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 295, y = 337, w = 132, h = 19, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 480, y = 337, w = 99, h = 26, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 42, acc = "pine" },
    { kind = "column", x = 138, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 44, acc = "pine" },
    { kind = "column", x = 311, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 51, acc = "pine" },
    { kind = "column", x = 450, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 39, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 45, acc = "pine" },
    { kind = "column", x = 130, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 45, acc = "pine" },
    { kind = "column", x = 283, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 42, acc = "pine" },
    { kind = "column", x = 450, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 43, acc = "pine" },
    { kind = "girder", x = -16, y = 163, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 35 },
    { kind = "girder", x = -16, y = 315, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 33 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 330, y = 81, w = 2, h = 51, col = "pine", a = 0.37, lw = 2, sway = 4, rate = 0.37, bob = true },
    { kind = "hang", x = 364, y = 165, w = 2, h = 19, col = "pine", a = 0.51, lw = 2, sway = 3, rate = 0.44, bob = true },
    { kind = "hang", x = 360, y = 20, w = 2, h = 34, col = "pine", a = 0.53, lw = 2, sway = 4, rate = 0.57, bob = true },
    { kind = "hang", x = 103, y = 172, w = 2, h = 23, col = "pine", a = 0.43, lw = 2, sway = 4, rate = 0.56, bob = true },
    { kind = "hang", x = 455, y = 189, w = 2, h = 18, col = "pine", a = 0.55, lw = 2, sway = 3, rate = 0.28, bob = true },
    { kind = "hang", x = 22, y = 101, w = 2, h = 25, col = "pine", a = 0.47, lw = 2, sway = 5, rate = 0.47, bob = true },
    { kind = "hang", x = 311, y = 244, w = 2, h = 16, col = "pine", a = 0.57, lw = 2, sway = 6, rate = 0.48, bob = true },
    { kind = "hang", x = 377, y = 177, w = 2, h = 41, col = "pine", a = 0.56, lw = 2, sway = 3, rate = 0.38, bob = true },
    { kind = "rect", x = 135, y = 338, w = 4, h = 3, col = "leaf", a = 0.36 },
    { kind = "rect", x = 289, y = 209, w = 8, h = 3, col = "leaf", a = 0.33 },
    { kind = "rect", x = 451, y = 65, w = 8, h = 4, col = "leaf", a = 0.32 },
    { kind = "rect", x = 215, y = 195, w = 4, h = 4, col = "leaf", a = 0.22 },
    { kind = "rect", x = 457, y = 162, w = 3, h = 2, col = "leaf", a = 0.25 },
    { kind = "rect", x = 437, y = 185, w = 4, h = 2, col = "leaf", a = 0.18 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 21, w = 528, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 472, y = 36, w = 2, h = 49, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 7, rate = 0.49, bob = true },
    { kind = "hang", x = 69, y = 36, w = 2, h = 66, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.68, bob = true },
    { kind = "hang", x = 364, y = 36, w = 2, h = 50, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 11, rate = 0.46, bob = true },
    { kind = "hang", x = 310, y = 36, w = 2, h = 45, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.46, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 544, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 460, y = 0, w = 20, h = 544, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 65, col = { 0.72, 0.86, 1.00 }, r = 109, flicker = 0.78 },
  },
  mapPos = { x = 1, y = 0, w = 1, h = 2 },
  map = [[
##############################
##############################
##############################
##.........###################
####................##########
##.........................###
##.........................###
###........................###
###.........................##
###.......................####
###.......................##BB
###..................q.q....BB
##...................#########
####......................####
###........................###
####.......................###
####.......................###
###.......................####
###.......................####
####......................####
###......q..y...yl..u...l...##
####.....################...##
##..........................##
####......................####
##..........................##
####.......................###
##........................####
####........................##
##........................####
##.........................###
AA........................####
AA#.....U.................####
##############################
##############################
]],
  key = {
    ["l"] = "cinderbat",
    ["U"] = "updraft:12",
    ["u"] = "updraft:10",
    ["y"] = "windray",
    ["q"] = "stormvane",
  },
  links = {
    A = { "gal_1", "B" },
    B = { "gal_3", "A" },
  },
}
