-- generated by scripts/genvanes.py (The Drift Vanes)
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 59, w = 128, h = 18, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 189, y = 59, w = 220, h = 16, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 506, y = 59, w = 93, h = 23, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 119, w = 146, h = 26, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 140, y = 119, w = 130, h = 19, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 356, y = 119, w = 156, h = 28, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 168, w = 166, h = 19, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 170, y = 168, w = 110, h = 23, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 392, y = 168, w = 137, h = 22, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 47, acc = "pine" },
    { kind = "column", x = 148, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 51, acc = "pine" },
    { kind = "column", x = 285, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 31, acc = "pine" },
    { kind = "column", x = 442, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 36, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 36, acc = "pine" },
    { kind = "column", x = 203, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 43, acc = "pine" },
    { kind = "column", x = 339, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 44, acc = "pine" },
    { kind = "column", x = 467, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 52, acc = "pine" },
    { kind = "girder", x = -16, y = 81, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 33 },
    { kind = "girder", x = -16, y = 157, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 36 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 265, y = 16, w = 2, h = 21, col = "pine", a = 0.56, lw = 2, sway = 3, rate = 0.49, bob = true },
    { kind = "hang", x = 246, y = 117, w = 2, h = 22, col = "pine", a = 0.55, lw = 2, sway = 7, rate = 0.59, bob = true },
    { kind = "hang", x = 408, y = 73, w = 2, h = 29, col = "pine", a = 0.56, lw = 2, sway = 8, rate = 0.56, bob = true },
    { kind = "hang", x = 460, y = 73, w = 2, h = 45, col = "pine", a = 0.53, lw = 2, sway = 5, rate = 0.52, bob = true },
    { kind = "hang", x = 360, y = 126, w = 2, h = 17, col = "pine", a = 0.44, lw = 2, sway = 7, rate = 0.46, bob = true },
    { kind = "hang", x = 19, y = 81, w = 2, h = 31, col = "pine", a = 0.51, lw = 2, sway = 3, rate = 0.47, bob = true },
    { kind = "hang", x = 32, y = 101, w = 2, h = 44, col = "pine", a = 0.49, lw = 2, sway = 8, rate = 0.29, bob = true },
    { kind = "hang", x = 160, y = 38, w = 2, h = 50, col = "pine", a = 0.63, lw = 2, sway = 4, rate = 0.47, bob = true },
    { kind = "rect", x = 299, y = 206, w = 4, h = 2, col = "leaf", a = 0.38 },
    { kind = "rect", x = 312, y = 46, w = 3, h = 4, col = "leaf", a = 0.26 },
    { kind = "rect", x = 100, y = 189, w = 7, h = 3, col = "leaf", a = 0.2 },
    { kind = "rect", x = 6, y = 138, w = 5, h = 3, col = "leaf", a = 0.22 },
    { kind = "rect", x = 130, y = 54, w = 8, h = 4, col = "leaf", a = 0.4 },
    { kind = "rect", x = 219, y = 197, w = 7, h = 4, col = "leaf", a = 0.32 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 528, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 173, y = 25, w = 2, h = 51, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 9, rate = 0.5, bob = true },
    { kind = "hang", x = 76, y = 25, w = 2, h = 45, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.43, bob = true },
    { kind = "hang", x = 30, y = 25, w = 2, h = 45, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 7, rate = 0.43, bob = true },
    { kind = "hang", x = 353, y = 25, w = 2, h = 71, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 11, rate = 0.47, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 460, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 32, col = { 0.72, 0.86, 1.00 }, r = 104, flicker = 1.05 },
  },
  mapPos = { x = 0, y = 1, w = 1, h = 1 },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##..........................##
##.AA.......................BB
##qAA...............q......pBB
#########...........##########
##.......p..................##
##.......===................##
##......................1...##
##############################
##############################
##############################
##############################
##############################
]],
  key = {
    ["p"] = "sporefly",
    ["q"] = "roostfang",
    ["1"] = "sign:sign_span",
  },
  links = {
    A = { "sky_2", "C" },
    B = { "gal_2", "A" },
  },
}
