-- generated by scripts/genvanes.py (The Drift Vanes)
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 59, w = 164, h = 19, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 226, y = 59, w = 182, h = 27, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 509, y = 59, w = 134, h = 19, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 712, y = 59, w = 156, h = 30, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 924, y = 59, w = 119, h = 23, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 119, w = 153, h = 26, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 225, y = 119, w = 113, h = 18, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 455, y = 119, w = 203, h = 14, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 773, y = 119, w = 169, h = 27, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 976, y = 119, w = 118, h = 28, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 168, w = 207, h = 26, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 211, y = 168, w = 178, h = 29, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 492, y = 168, w = 191, h = 23, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 719, y = 168, w = 176, h = 17, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 967, y = 168, w = 204, h = 21, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 32, acc = "pine" },
    { kind = "column", x = 72, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 35, acc = "pine" },
    { kind = "column", x = 227, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 46, acc = "pine" },
    { kind = "column", x = 337, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 41, acc = "pine" },
    { kind = "column", x = 431, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 48, acc = "pine" },
    { kind = "column", x = 536, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 48, acc = "pine" },
    { kind = "column", x = 696, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 50, acc = "pine" },
    { kind = "column", x = 800, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 36, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 38, acc = "pine" },
    { kind = "column", x = 180, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 43, acc = "pine" },
    { kind = "column", x = 333, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 34, acc = "pine" },
    { kind = "column", x = 438, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 32, acc = "pine" },
    { kind = "column", x = 567, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 42, acc = "pine" },
    { kind = "column", x = 740, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 33, acc = "pine" },
    { kind = "column", x = 910, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 31, acc = "pine" },
    { kind = "girder", x = -16, y = 81, w = 992, h = 12, col = "black", a = 0.3, py = 0.22, step = 32 },
    { kind = "girder", x = -16, y = 157, w = 992, h = 12, col = "black", a = 0.3, py = 0.22, step = 42 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 96, y = 60, w = 2, h = 41, col = "pine", a = 0.63, lw = 2, sway = 8, rate = 0.33, bob = true },
    { kind = "hang", x = 355, y = 118, w = 2, h = 38, col = "pine", a = 0.48, lw = 2, sway = 6, rate = 0.37, bob = true },
    { kind = "hang", x = 655, y = 40, w = 2, h = 19, col = "pine", a = 0.42, lw = 2, sway = 5, rate = 0.34, bob = true },
    { kind = "hang", x = 176, y = 130, w = 2, h = 42, col = "pine", a = 0.36, lw = 2, sway = 8, rate = 0.47, bob = true },
    { kind = "hang", x = 450, y = 67, w = 2, h = 38, col = "pine", a = 0.64, lw = 2, sway = 6, rate = 0.59, bob = true },
    { kind = "hang", x = 837, y = 13, w = 2, h = 31, col = "pine", a = 0.38, lw = 2, sway = 6, rate = 0.56, bob = true },
    { kind = "hang", x = 823, y = 19, w = 2, h = 49, col = "pine", a = 0.43, lw = 2, sway = 7, rate = 0.36, bob = true },
    { kind = "hang", x = 664, y = 18, w = 2, h = 26, col = "pine", a = 0.37, lw = 2, sway = 4, rate = 0.53, bob = true },
    { kind = "hang", x = 780, y = 64, w = 2, h = 36, col = "pine", a = 0.49, lw = 2, sway = 5, rate = 0.53, bob = true },
    { kind = "hang", x = 740, y = 1, w = 2, h = 38, col = "pine", a = 0.38, lw = 2, sway = 5, rate = 0.54, bob = true },
    { kind = "hang", x = 398, y = 12, w = 2, h = 33, col = "pine", a = 0.52, lw = 2, sway = 5, rate = 0.45, bob = true },
    { kind = "hang", x = 410, y = 103, w = 2, h = 44, col = "pine", a = 0.4, lw = 2, sway = 3, rate = 0.5, bob = true },
    { kind = "hang", x = 574, y = 72, w = 2, h = 51, col = "pine", a = 0.35, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 930, y = 62, w = 2, h = 54, col = "pine", a = 0.49, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 633, y = 112, w = 2, h = 36, col = "pine", a = 0.64, lw = 2, sway = 4, rate = 0.53, bob = true },
    { kind = "hang", x = 135, y = 85, w = 2, h = 48, col = "pine", a = 0.37, lw = 2, sway = 6, rate = 0.51, bob = true },
    { kind = "hang", x = 179, y = 40, w = 2, h = 52, col = "pine", a = 0.59, lw = 2, sway = 5, rate = 0.55, bob = true },
    { kind = "rect", x = 601, y = 96, w = 4, h = 2, col = "leaf", a = 0.27 },
    { kind = "rect", x = 337, y = 154, w = 8, h = 2, col = "leaf", a = 0.29 },
    { kind = "rect", x = 43, y = 86, w = 3, h = 4, col = "leaf", a = 0.29 },
    { kind = "rect", x = 913, y = 118, w = 5, h = 4, col = "leaf", a = 0.29 },
    { kind = "rect", x = 633, y = 207, w = 7, h = 4, col = "leaf", a = 0.19 },
    { kind = "rect", x = 801, y = 193, w = 8, h = 3, col = "leaf", a = 0.25 },
    { kind = "rect", x = 794, y = 43, w = 7, h = 2, col = "leaf", a = 0.38 },
    { kind = "rect", x = 92, y = 183, w = 7, h = 2, col = "leaf", a = 0.26 },
    { kind = "rect", x = 112, y = 75, w = 8, h = 3, col = "leaf", a = 0.25 },
    { kind = "rect", x = 90, y = 222, w = 5, h = 2, col = "leaf", a = 0.32 },
    { kind = "rect", x = 762, y = 162, w = 8, h = 2, col = "leaf", a = 0.19 },
    { kind = "rect", x = 444, y = 142, w = 4, h = 4, col = "leaf", a = 0.21 },
    { kind = "rect", x = 762, y = 157, w = 8, h = 4, col = "leaf", a = 0.37 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 1008, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 871, y = 25, w = 2, h = 51, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 9, rate = 0.67, bob = true },
    { kind = "hang", x = 768, y = 25, w = 2, h = 38, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 6, rate = 0.63, bob = true },
    { kind = "hang", x = 669, y = 25, w = 2, h = 43, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 7, rate = 0.77, bob = true },
    { kind = "hang", x = 196, y = 25, w = 2, h = 65, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 7, rate = 0.5, bob = true },
    { kind = "hang", x = 950, y = 25, w = 2, h = 56, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 7, rate = 0.43, bob = true },
    { kind = "hang", x = 308, y = 25, w = 2, h = 34, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.62, bob = true },
    { kind = "hang", x = 634, y = 25, w = 2, h = 53, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 6, rate = 0.67, bob = true },
    { kind = "hang", x = 240, y = 25, w = 2, h = 34, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 9, rate = 0.47, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 940, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 32, col = { 0.72, 0.86, 1.00 }, r = 91, flicker = 0.91 },
    { x = 480, y = 32, col = { 0.72, 0.86, 1.00 }, r = 84, flicker = 0.5 },
    { x = 800, y = 32, col = { 0.72, 0.86, 1.00 }, r = 93, flicker = 1.02 },
  },
  mapPos = { x = 2, y = 0, w = 3, h = 1 },
  map = [[
############################################################
############################################################
##........................................................##
##........................................................##
##........................................................##
##........................................................##
##............................q...........................##
##........q...................=======.....................##
##........======............................p.z...........##
##..........................................======........##
AA........................................................##
AAp.....1....l......2.............3...............4.......##
############################################################
############################################################
############################################################
############################################################
############################################################
]],
  key = {
    ["l"] = "cinderbat",
    ["p"] = "sporefly",
    ["q"] = "roostfang",
    ["1"] = "sign:sign_roster1",
    ["2"] = "sign:sign_roster2",
    ["3"] = "sign:sign_roster3",
    ["4"] = "tank:tank_gallery",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "gal_2", "B" },
  },
}
