-- generated by scripts/genrooms.py
return {
  zone = "mosswood", music = "mosswood",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "pine", a = 0.3, a2 = 0.07, py = 0.05 },
    { kind = "column", x = -16, y = 0, w = 27, h = 272, col = "black", a = 0.31, py = 0.18, step = 36, acc = "moss" },
    { kind = "column", x = 49, y = 0, w = 26, h = 272, col = "black", a = 0.26, py = 0.25, step = 41, acc = "moss" },
    { kind = "column", x = 144, y = 0, w = 40, h = 272, col = "black", a = 0.25, py = 0.23, step = 37, acc = "moss" },
    { kind = "column", x = 250, y = 0, w = 26, h = 272, col = "black", a = 0.27, py = 0.18, step = 30, acc = "moss" },
    { kind = "column", x = 344, y = 0, w = 37, h = 272, col = "black", a = 0.35, py = 0.15, step = 28, acc = "moss" },
    { kind = "column", x = 420, y = 0, w = 24, h = 272, col = "black", a = 0.25, py = 0.16, step = 32, acc = "moss" },
    { kind = "column", x = 481, y = 0, w = 27, h = 272, col = "black", a = 0.24, py = 0.18, step = 33, acc = "moss" },
    { kind = "column", x = 544, y = 0, w = 32, h = 272, col = "black", a = 0.33, py = 0.16, step = 31, acc = "moss" },
    { kind = "column", x = 634, y = 0, w = 34, h = 272, col = "black", a = 0.28, py = 0.17, step = 37, acc = "moss" },
    { kind = "column", x = 692, y = 0, w = 38, h = 272, col = "black", a = 0.39, py = 0.25, step = 34, acc = "moss" },
    { kind = "column", x = 793, y = 0, w = 29, h = 272, col = "black", a = 0.35, py = 0.22, step = 42, acc = "moss" },
    { kind = "column", x = 859, y = 0, w = 36, h = 272, col = "black", a = 0.38, py = 0.18, step = 37, acc = "moss" },
    { kind = "column", x = 942, y = 0, w = 27, h = 272, col = "black", a = 0.26, py = 0.18, step = 36, acc = "moss" },
    { kind = "shaft", x = 485, y = 0, w = 64, h = 231, col = "lime", a = 0.15, py = 0.18, skew = 5, ph = 3.97 },
    { kind = "shaft", x = 392, y = 0, w = 61, h = 231, col = "lime", a = 0.15, py = 0.18, skew = 12, ph = 2.04 },
    { kind = "shaft", x = 519, y = 0, w = 47, h = 231, col = "lime", a = 0.15, py = 0.18, skew = 21, ph = 0.06 },
    { kind = "shaft", x = 342, y = 0, w = 41, h = 231, col = "lime", a = 0.15, py = 0.18, skew = 6, ph = 1.49 },
    { kind = "shaft", x = 591, y = 0, w = 55, h = 231, col = "lime", a = 0.15, py = 0.18, skew = 0, ph = 0.67 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 386, y = 61, w = 2, h = 16, col = "moss", a = 0.46, lw = 2, sway = 2, rate = 0.35, bob = true },
    { kind = "hang", x = 61, y = 71, w = 2, h = 20, col = "moss", a = 0.59, lw = 2, sway = 3, rate = 0.36, bob = true },
    { kind = "hang", x = 232, y = 45, w = 2, h = 13, col = "moss", a = 0.62, lw = 2, sway = 5, rate = 0.22, bob = true },
    { kind = "hang", x = 729, y = 26, w = 2, h = 15, col = "moss", a = 0.51, lw = 2, sway = 5, rate = 0.38, bob = true },
    { kind = "hang", x = 682, y = 114, w = 2, h = 11, col = "moss", a = 0.64, lw = 2, sway = 3, rate = 0.44, bob = true },
    { kind = "hang", x = 596, y = 62, w = 2, h = 31, col = "moss", a = 0.64, lw = 2, sway = 3, rate = 0.21, bob = true },
    { kind = "hang", x = 111, y = 106, w = 2, h = 25, col = "moss", a = 0.65, lw = 2, sway = 5, rate = 0.34, bob = true },
    { kind = "hang", x = 651, y = 108, w = 2, h = 16, col = "moss", a = 0.68, lw = 2, sway = 6, rate = 0.39, bob = true },
    { kind = "hang", x = 170, y = 24, w = 2, h = 21, col = "moss", a = 0.59, lw = 2, sway = 5, rate = 0.46, bob = true },
    { kind = "hang", x = 683, y = 54, w = 2, h = 37, col = "moss", a = 0.46, lw = 2, sway = 4, rate = 0.41, bob = true },
    { kind = "hang", x = 864, y = 20, w = 2, h = 40, col = "moss", a = 0.6, lw = 2, sway = 3, rate = 0.39, bob = true },
    { kind = "hang", x = 184, y = 32, w = 2, h = 10, col = "moss", a = 0.61, lw = 2, sway = 4, rate = 0.23, bob = true },
    { kind = "hang", x = 784, y = 91, w = 2, h = 13, col = "moss", a = 0.73, lw = 2, sway = 2, rate = 0.48, bob = true },
    { kind = "hang", x = 255, y = 76, w = 2, h = 13, col = "moss", a = 0.72, lw = 2, sway = 5, rate = 0.49, bob = true },
    { kind = "hang", x = 245, y = 69, w = 2, h = 10, col = "moss", a = 0.44, lw = 2, sway = 3, rate = 0.34, bob = true },
    { kind = "hang", x = 607, y = 110, w = 2, h = 14, col = "moss", a = 0.55, lw = 2, sway = 3, rate = 0.29, bob = true },
    { kind = "hang", x = 929, y = 6, w = 2, h = 16, col = "moss", a = 0.48, lw = 2, sway = 4, rate = 0.26, bob = true },
    { kind = "hang", x = 58, y = 43, w = 2, h = 20, col = "moss", a = 0.66, lw = 2, sway = 2, rate = 0.33, bob = true },
    { kind = "hang", x = 587, y = 66, w = 2, h = 35, col = "moss", a = 0.68, lw = 2, sway = 4, rate = 0.29, bob = true },
    { kind = "hang", x = 387, y = 5, w = 2, h = 14, col = "moss", a = 0.49, lw = 2, sway = 3, rate = 0.25, bob = true },
    { kind = "hang", x = 336, y = 79, w = 2, h = 33, col = "moss", a = 0.51, lw = 2, sway = 3, rate = 0.27, bob = true },
    { kind = "rect", x = 601, y = 58, w = 9, h = 2, col = "moss", a = 0.4 },
    { kind = "rect", x = 313, y = 46, w = 13, h = 4, col = "fern", a = 0.44 },
    { kind = "rect", x = 46, y = 202, w = 10, h = 3, col = "moss", a = 0.35 },
    { kind = "rect", x = 939, y = 202, w = 8, h = 5, col = "fern", a = 0.43 },
    { kind = "rect", x = 104, y = 73, w = 13, h = 2, col = "fern", a = 0.33 },
    { kind = "rect", x = 950, y = 210, w = 17, h = 3, col = "fern", a = 0.32 },
    { kind = "rect", x = 701, y = 58, w = 9, h = 2, col = "lime", a = 0.34 },
    { kind = "rect", x = 564, y = 214, w = 12, h = 5, col = "lime", a = 0.44 },
    { kind = "rect", x = 685, y = 233, w = 18, h = 4, col = "fern", a = 0.38 },
    { kind = "rect", x = 937, y = 59, w = 18, h = 2, col = "fern", a = 0.44 },
    { kind = "rect", x = 388, y = 187, w = 10, h = 4, col = "moss", a = 0.45 },
    { kind = "rect", x = 128, y = 117, w = 12, h = 4, col = "fern", a = 0.31 },
    { kind = "rect", x = 190, y = 228, w = 10, h = 3, col = "fern", a = 0.42 },
    { kind = "rect", x = 934, y = 222, w = 17, h = 3, col = "lime", a = 0.32 },
    { kind = "rect", x = 663, y = 201, w = 10, h = 4, col = "lime", a = 0.24 },
    { kind = "rect", x = 383, y = 159, w = 6, h = 5, col = "lime", a = 0.22 },
    { kind = "rect", x = 273, y = 106, w = 17, h = 5, col = "moss", a = 0.34 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 13, w = 1008, h = 13, col = "black", a = 0.82, py = -0.12, step = 44 },
    { kind = "hang", x = 45, y = 26, w = 2, h = 44, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 8, rate = 0.56, bob = true },
    { kind = "hang", x = 646, y = 26, w = 2, h = 27, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 5, rate = 0.43, bob = true },
    { kind = "hang", x = 928, y = 26, w = 2, h = 63, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 4, rate = 0.42, bob = true },
    { kind = "hang", x = 59, y = 26, w = 2, h = 61, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 7, rate = 0.42, bob = true },
    { kind = "hang", x = 463, y = 26, w = 2, h = 64, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 8, rate = 0.62, bob = true },
    { kind = "hang", x = 905, y = 26, w = 2, h = 61, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 7, rate = 0.62, bob = true },
    { kind = "hang", x = 297, y = 26, w = 2, h = 61, col = "black", a = 0.78, py = -0.12, lw = 3, sway = 5, rate = 0.38, bob = true },
    { kind = "band", x = 0, y = 0, w = 22, h = 272, col = "black", a = 0.4, a2 = 0.4, py = -0.05 },
    { kind = "band", x = 938, y = 0, w = 22, h = 272, col = "black", a = 0.4, a2 = 0.4, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 160, y = 43, col = { 0.80, 1.00, 0.66 }, r = 94, flicker = 1.14 },
    { x = 480, y = 43, col = { 0.80, 1.00, 0.66 }, r = 77, flicker = 1.48 },
    { x = 800, y = 43, col = { 0.80, 1.00, 0.66 }, r = 81, flicker = 2.34 },
  },
  mapPos = { x = 4, y = 0, w = 2, h = 1 },
  gates = { G = "plate_m4a", H = "plate_m4b" },
  map = [[
############################################################
############################################################
##.......##...................#######..####.....####.##...##
##...#####.........................######.........###.######
########............................................########
######....=====........p......................g...........##
####..................#####.....#...........=====.........##
##....................#####...####...#...................%##
##.....................###...###########................%%##
##...........................G...####..H................%.##
AA...........................G....%%...H...............%%.BB
AA....1..........r....r..x.2.G...3%%...H...y........r.%%..BB
########.......#############################################
#########.....##############################################
##########...########.######################################
##########...#######.....###################################
############################################################
]],
  key = {
    ["1"] = "sign:sign_plates",
    ["2"] = "sign:sign_vaultjump",
    ["3"] = "chest:chest_sparkjump:module:sparkjump",
    ["x"] = "plate:plate_m4a:latch",
    ["y"] = "plate:plate_m4b:latch",
    ["p"] = "spitter",
    ["g"] = "gnat",
    ["r"] = "rollpede",
  },
  links = {
    A = { "moss_3", "A" },
    B = { "moss_5", "A" },
  },
}
