-- generated by scripts/genscrap.py (The Bulwark Line)
return {
  zone = "scrapyard", music = "scrapyard",
  arena = "scrapyard",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "umber", a = 0.3, a2 = 0.06, py = 0.05 },
    { kind = "rect", x = -20, y = 144, w = 85, h = 105, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 88, y = 216, w = 77, h = 48, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 178, y = 181, w = 65, h = 84, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 268, y = 197, w = 81, h = 64, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 360, y = 171, w = 91, h = 79, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 478, y = 207, w = 85, h = 62, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 587, y = 151, w = 69, h = 103, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 672, y = 220, w = 52, h = 48, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 740, y = 214, w = 80, h = 48, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 849, y = 197, w = 50, h = 75, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 917, y = 197, w = 46, h = 73, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = -30, y = 133, w = 74, h = 139, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 99, y = 153, w = 113, h = 119, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 239, y = 170, w = 110, h = 102, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 375, y = 161, w = 110, h = 111, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 531, y = 195, w = 87, h = 77, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 645, y = 155, w = 75, h = 117, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 761, y = 162, w = 78, h = 110, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 894, y = 145, w = 117, h = 127, col = "black", a = 0.26, py = 0.12 },
    { kind = "girder", x = -16, y = 48, w = 992, h = 14, col = "black", a = 0.42, py = 0.3, step = 34 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.34, py = 0.24, step = 34 },
    { kind = "hang", x = 209, y = 62, w = 2, h = 58, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 117, y = 62, w = 2, h = 53, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 345, y = 62, w = 2, h = 50, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 698, y = 62, w = 2, h = 48, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 774, y = 102, w = 3, h = 21, col = "rust", a = 0.3 },
    { kind = "rect", x = 385, y = 121, w = 5, h = 24, col = "rust", a = 0.3 },
    { kind = "rect", x = 222, y = 180, w = 3, h = 27, col = "rust", a = 0.3 },
    { kind = "rect", x = 217, y = 159, w = 4, h = 20, col = "rust", a = 0.3 },
    { kind = "rect", x = 729, y = 104, w = 3, h = 41, col = "rust", a = 0.3 },
    { kind = "rect", x = 749, y = 154, w = 4, h = 21, col = "rust", a = 0.3 },
    { kind = "rect", x = 750, y = 85, w = 5, h = 36, col = "rust", a = 0.3 },
    { kind = "rect", x = 664, y = 117, w = 2, h = 25, col = "rust", a = 0.3 },
    { kind = "rect", x = 834, y = 156, w = 2, h = 14, col = "rust", a = 0.3 },
    { kind = "rect", x = 644, y = 95, w = 4, h = 31, col = "rust", a = 0.3 },
    { kind = "rect", x = 871, y = 136, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 873, y = 138, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 248, y = 69, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 250, y = 71, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 246, y = 140, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 248, y = 142, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 918, y = 71, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 920, y = 73, w = 3, h = 5, col = "ember", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 16, w = 1008, h = 16, col = "black", a = 0.9, py = -0.12, step = 34 },
    { kind = "hang", x = 926, y = 32, w = 2, h = 63, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 395, y = 32, w = 2, h = 43, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 840, y = 32, w = 2, h = 50, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 36, y = 32, w = 2, h = 57, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 72, y = 32, w = 2, h = 46, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 327, y = 32, w = 2, h = 40, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 874, y = 140, col = { 1.00, 0.62, 0.28 }, r = 46, flicker = 6 },
    { x = 251, y = 73, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 7.07 },
    { x = 249, y = 144, col = { 1.00, 0.62, 0.28 }, r = 49, flicker = 7.17 },
    { x = 921, y = 75, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 6.41 },
    { x = 720, y = 159, col = { 1.00, 0.86, 0.55 }, r = 55, flicker = 13.71 },
  },
  mapPos = { x = 2, y = 1, w = 3, h = 1 },
  map = [[
############################################################
############################################################
####........############################..############....##
##............####################....#.###########.......##
##.............#......V.######..........##V########.......##
##...........h.............#..............................##
##..........=========............f........................##
##..........................==========....................##
##...................h.......................h............##
##..............==========...............=========........##
##......DD.........................................f......CC
##......DD................%%%%%%....k..............#..d...CC
##...########.===========.....===========.......############
##############...........===...............===..#########.##
##############..................................#########.##
##############..^^^^^^^....f....^^^^^^^.........############
############################################################
]],
  key = {
    ["d"] = "shieldbug",
    ["k"] = "rollpede",
    ["V"] = "vent:d:3.4",
    ["f"] = "plateframe",
    ["h"] = "scraphusk",
  },
  links = {
    C = { "scrap_bay", "B" },
    D = { "scrap_6", "D" },
  },
}
