-- generated by scripts/genscrap.py (The Bulwark Line)
return {
  zone = "scrapyard", music = "scrapyard",
  arena = "scrapyard",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "umber", a = 0.3, a2 = 0.06, py = 0.05 },
    { kind = "rect", x = -20, y = 198, w = 64, h = 52, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 65, y = 163, w = 69, h = 99, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 163, y = 147, w = 95, h = 110, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 272, y = 173, w = 56, h = 91, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 344, y = 200, w = 67, h = 60, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 431, y = 187, w = 63, h = 84, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 514, y = 186, w = 69, h = 80, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 606, y = 159, w = 85, h = 91, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 707, y = 208, w = 61, h = 54, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 787, y = 188, w = 79, h = 71, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 892, y = 175, w = 54, h = 75, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 954, y = 152, w = 88, h = 102, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = -30, y = 189, w = 102, h = 83, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 112, y = 169, w = 115, h = 103, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 281, y = 159, w = 125, h = 113, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 450, y = 196, w = 124, h = 76, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 624, y = 189, w = 116, h = 83, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 783, y = 137, w = 105, h = 135, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 913, y = 177, w = 61, h = 95, col = "black", a = 0.26, py = 0.12 },
    { kind = "girder", x = -16, y = 48, w = 992, h = 14, col = "black", a = 0.42, py = 0.3, step = 34 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.34, py = 0.24, step = 26 },
    { kind = "hang", x = 430, y = 62, w = 2, h = 38, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 34, y = 62, w = 2, h = 32, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 319, y = 62, w = 2, h = 52, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 568, y = 62, w = 2, h = 36, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 783, y = 72, w = 5, h = 28, col = "rust", a = 0.3 },
    { kind = "rect", x = 812, y = 64, w = 4, h = 23, col = "rust", a = 0.3 },
    { kind = "rect", x = 662, y = 134, w = 5, h = 17, col = "rust", a = 0.3 },
    { kind = "rect", x = 601, y = 64, w = 2, h = 34, col = "rust", a = 0.3 },
    { kind = "rect", x = 877, y = 172, w = 4, h = 43, col = "rust", a = 0.3 },
    { kind = "rect", x = 871, y = 51, w = 3, h = 33, col = "rust", a = 0.3 },
    { kind = "rect", x = 419, y = 102, w = 4, h = 18, col = "rust", a = 0.3 },
    { kind = "rect", x = 319, y = 122, w = 2, h = 26, col = "rust", a = 0.3 },
    { kind = "rect", x = 428, y = 115, w = 2, h = 44, col = "rust", a = 0.3 },
    { kind = "rect", x = 351, y = 115, w = 5, h = 40, col = "rust", a = 0.3 },
    { kind = "rect", x = 220, y = 107, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 222, y = 109, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 273, y = 121, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 275, y = 123, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 30, y = 73, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 32, y = 75, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 350, y = 86, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 352, y = 88, w = 3, h = 5, col = "ember", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 16, w = 1008, h = 16, col = "black", a = 0.9, py = -0.12, step = 34 },
    { kind = "hang", x = 581, y = 32, w = 2, h = 55, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 702, y = 32, w = 2, h = 64, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 877, y = 32, w = 2, h = 39, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 866, y = 32, w = 2, h = 44, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 822, y = 32, w = 2, h = 46, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 268, y = 32, w = 2, h = 54, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 223, y = 111, col = { 1.00, 0.62, 0.28 }, r = 48, flicker = 5.75 },
    { x = 276, y = 125, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 5.65 },
    { x = 33, y = 77, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 5.6 },
    { x = 353, y = 90, col = { 1.00, 0.62, 0.28 }, r = 40, flicker = 5.02 },
    { x = 539, y = 147, col = { 1.00, 0.86, 0.55 }, r = 54, flicker = 11.56 },
  },
  mapPos = { x = 0, y = 4, w = 3, h = 1 },
  map = [[
############################################################
############################################################
############################################################
############################################################
##......####################################################
##....................#...n..#..n.....n..#..f.#.......#...##
##...........................h..........=========.........##
##......................==========........................##
##................h.......................................##
##............==========......................h...........##
##....DD....................................========......BB
##....DD........%%%%%%........................##...#......BB
###########.....................===========...##===#########
########................f#######..%%%%%%%.....##..........##
###########.d..##....###########..............##.k.##4....##
################################.....k.....##############.##
############################################################
]],
  key = {
    ["d"] = "shieldbug",
    ["k"] = "rollpede",
    ["f"] = "plateframe",
    ["h"] = "scraphusk",
    ["4"] = "deadvess:4",
    ["n"] = "anchor",
  },
  links = {
    D = { "scrap_2", "D" },
    B = { "scrap_4", "A" },
  },
}
