-- generated by scripts/genscrap.py (The Bulwark Line)
return {
  zone = "scrapyard", music = "scrapyard",
  arena = "scrapyard",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "umber", a = 0.3, a2 = 0.06, py = 0.05 },
    { kind = "rect", x = -20, y = 205, w = 46, h = 55, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 38, y = 212, w = 46, h = 52, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 102, y = 174, w = 87, h = 87, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 218, y = 183, w = 52, h = 67, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 292, y = 160, w = 53, h = 97, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 365, y = 215, w = 89, h = 52, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 472, y = 222, w = 82, h = 49, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 572, y = 177, w = 71, h = 87, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 652, y = 211, w = 86, h = 57, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 766, y = 182, w = 88, h = 74, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 865, y = 217, w = 74, h = 47, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = -30, y = 147, w = 115, h = 125, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 135, y = 140, w = 74, h = 132, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 261, y = 192, w = 73, h = 80, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 368, y = 171, w = 111, h = 101, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 532, y = 140, w = 71, h = 132, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 631, y = 137, w = 123, h = 135, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 809, y = 126, w = 62, h = 146, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 913, y = 160, w = 100, h = 112, col = "black", a = 0.26, py = 0.12 },
    { kind = "girder", x = -16, y = 48, w = 992, h = 14, col = "black", a = 0.42, py = 0.3, step = 30 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.34, py = 0.24, step = 30 },
    { kind = "hang", x = 454, y = 62, w = 2, h = 43, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 755, y = 62, w = 2, h = 27, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 59, y = 62, w = 2, h = 38, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 148, y = 62, w = 2, h = 32, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 657, y = 77, w = 4, h = 37, col = "rust", a = 0.3 },
    { kind = "rect", x = 848, y = 130, w = 5, h = 14, col = "rust", a = 0.3 },
    { kind = "rect", x = 218, y = 162, w = 4, h = 26, col = "rust", a = 0.3 },
    { kind = "rect", x = 289, y = 115, w = 5, h = 41, col = "rust", a = 0.3 },
    { kind = "rect", x = 565, y = 127, w = 4, h = 24, col = "rust", a = 0.3 },
    { kind = "rect", x = 493, y = 163, w = 3, h = 41, col = "rust", a = 0.3 },
    { kind = "rect", x = 671, y = 96, w = 3, h = 26, col = "rust", a = 0.3 },
    { kind = "rect", x = 259, y = 40, w = 4, h = 44, col = "rust", a = 0.3 },
    { kind = "rect", x = 848, y = 145, w = 2, h = 19, col = "rust", a = 0.3 },
    { kind = "rect", x = 54, y = 142, w = 5, h = 34, col = "rust", a = 0.3 },
    { kind = "rect", x = 88, y = 69, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 90, y = 71, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 263, y = 59, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 265, y = 61, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 202, y = 55, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 204, y = 57, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 300, y = 60, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 302, y = 62, w = 3, h = 5, col = "ember", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 16, w = 1008, h = 16, col = "black", a = 0.9, py = -0.12, step = 34 },
    { kind = "hang", x = 198, y = 32, w = 2, h = 61, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 64, y = 32, w = 2, h = 40, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 497, y = 32, w = 2, h = 30, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 40, y = 32, w = 2, h = 30, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 580, y = 32, w = 2, h = 48, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 331, y = 32, w = 2, h = 37, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 91, y = 73, col = { 1.00, 0.62, 0.28 }, r = 50, flicker = 8.01 },
    { x = 266, y = 63, col = { 1.00, 0.62, 0.28 }, r = 54, flicker = 5.81 },
    { x = 205, y = 59, col = { 1.00, 0.62, 0.28 }, r = 60, flicker = 8 },
    { x = 303, y = 64, col = { 1.00, 0.62, 0.28 }, r = 48, flicker = 5.25 },
    { x = 805, y = 133, col = { 1.00, 0.86, 0.55 }, r = 61, flicker = 15.76 },
  },
  mapPos = { x = 0, y = 2, w = 3, h = 1 },
  gates = { G = "bulwark" },
  map = [[
############################################################
############################################################
####......###....#####G###########...#....#...............##
##....................G.......###########.................##
##....................G.......###########.................##
##....................G.........................r.........##
##....................G........r............=========.....##
##....................G...==========......................##
##.........h..........G.................w.................##
##....==========......G...................=========..###..##
##...DD...............G...........................##......BB
##...DD.%%%%%%........G......................k.#####.d....BB
##########............G...===========.##....################
##....................G...............##....############..##
##........z...........G.....%%%%%%%...##....############..##
##.....#####...6...s..G.##....k......#######################
############################################################
]],
  key = {
    ["d"] = "shieldbug",
    ["w"] = "welder",
    ["k"] = "rollpede",
    ["h"] = "scraphusk",
    ["z"] = "checkpoint",
    ["6"] = "deadvess:6",
    ["s"] = "sign:sign_scrap_gate",
    ["r"] = "rammer",
  },
  links = {
    D = { "scrap_5", "D" },
    B = { "scrap_boss", "A" },
  },
}
