-- generated by scripts/genscrap.py (The Bulwark Line)
return {
  zone = "scrapyard", music = "scrapyard",
  arena = "scrapyard",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "umber", a = 0.3, a2 = 0.06, py = 0.05 },
    { kind = "rect", x = -20, y = 151, w = 76, h = 99, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 74, y = 196, w = 74, h = 58, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 177, y = 166, w = 53, h = 102, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 242, y = 195, w = 82, h = 60, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 341, y = 154, w = 94, h = 105, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 446, y = 196, w = 89, h = 68, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 565, y = 199, w = 70, h = 55, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 644, y = 162, w = 46, h = 109, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 716, y = 165, w = 75, h = 107, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 816, y = 169, w = 60, h = 97, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 893, y = 169, w = 52, h = 82, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = -30, y = 173, w = 130, h = 99, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 140, y = 194, w = 99, h = 78, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 293, y = 133, w = 130, h = 139, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 462, y = 181, w = 129, h = 91, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 613, y = 146, w = 95, h = 126, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 742, y = 172, w = 102, h = 100, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 886, y = 127, w = 108, h = 145, col = "black", a = 0.26, py = 0.12 },
    { kind = "girder", x = -16, y = 48, w = 992, h = 14, col = "black", a = 0.42, py = 0.3, step = 30 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.34, py = 0.24, step = 26 },
    { kind = "hang", x = 454, y = 62, w = 2, h = 30, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 613, y = 62, w = 2, h = 42, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 408, y = 62, w = 2, h = 36, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 106, y = 62, w = 2, h = 28, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 467, y = 53, w = 3, h = 18, col = "rust", a = 0.3 },
    { kind = "rect", x = 173, y = 109, w = 5, h = 18, col = "rust", a = 0.3 },
    { kind = "rect", x = 780, y = 155, w = 5, h = 26, col = "rust", a = 0.3 },
    { kind = "rect", x = 496, y = 148, w = 5, h = 26, col = "rust", a = 0.3 },
    { kind = "rect", x = 578, y = 57, w = 3, h = 28, col = "rust", a = 0.3 },
    { kind = "rect", x = 516, y = 60, w = 4, h = 43, col = "rust", a = 0.3 },
    { kind = "rect", x = 825, y = 137, w = 2, h = 32, col = "rust", a = 0.3 },
    { kind = "rect", x = 272, y = 136, w = 5, h = 39, col = "rust", a = 0.3 },
    { kind = "rect", x = 166, y = 96, w = 4, h = 34, col = "rust", a = 0.3 },
    { kind = "rect", x = 623, y = 113, w = 2, h = 17, col = "rust", a = 0.3 },
    { kind = "rect", x = 435, y = 100, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 437, y = 102, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 269, y = 83, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 271, y = 85, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 373, y = 111, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 375, y = 113, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 722, y = 115, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 724, y = 117, w = 3, h = 5, col = "ember", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 16, w = 1008, h = 16, col = "black", a = 0.9, py = -0.12, step = 34 },
    { kind = "hang", x = 453, y = 32, w = 2, h = 60, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 928, y = 32, w = 2, h = 56, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 427, y = 32, w = 2, h = 48, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 759, y = 32, w = 2, h = 40, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 389, y = 32, w = 2, h = 48, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 444, y = 32, w = 2, h = 40, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 438, y = 104, col = { 1.00, 0.62, 0.28 }, r = 54, flicker = 8.07 },
    { x = 272, y = 87, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 7.64 },
    { x = 376, y = 115, col = { 1.00, 0.62, 0.28 }, r = 43, flicker = 5.06 },
    { x = 725, y = 119, col = { 1.00, 0.62, 0.28 }, r = 50, flicker = 6.82 },
    { x = 428, y = 151, col = { 1.00, 0.86, 0.55 }, r = 69, flicker = 12.7 },
  },
  mapPos = { x = 3, y = 0, w = 3, h = 1 },
  map = [[
############################################################
############################################################
##......##....#####.....###########...#......#......########
##.................##########...........................#.##
##.................##########.............................##
##.............h..........................................##
##..........========..............w.......................##
##............................==========..................##
##.....................h........................h.........##
##................==========................=========###..##
##..........DD......................##............##......CC
##..........DD..................%%%%%%%.......r#####3.....CC
##.......########...===========.....##......################
##.............................#######......############..##
##....................%%%%%%%..#########.k..############..##
####...z...#########......k....#############################
############################################################
]],
  key = {
    ["r"] = "rammer",
    ["k"] = "rollpede",
    ["w"] = "welder",
    ["h"] = "scraphusk",
    ["3"] = "deadvess:3",
    ["z"] = "checkpoint",
  },
  links = {
    C = { "scrap_1", "B" },
    D = { "scrap_3", "D" },
  },
}
