-- generated by scripts/genscrap.py (The Bulwark Line)
return {
  zone = "scrapyard", music = "scrapyard",
  arena = "scrapyard",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 960, h = 272, col = "umber", a = 0.3, a2 = 0.06, py = 0.05 },
    { kind = "rect", x = -20, y = 211, w = 94, h = 55, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 98, y = 176, w = 76, h = 81, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 185, y = 168, w = 88, h = 92, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 294, y = 215, w = 60, h = 50, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 363, y = 202, w = 70, h = 69, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 442, y = 202, w = 57, h = 54, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 524, y = 169, w = 71, h = 89, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 625, y = 214, w = 79, h = 45, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 729, y = 160, w = 79, h = 106, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 832, y = 204, w = 77, h = 48, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = 917, y = 203, w = 46, h = 46, col = "black", a = 0.42, py = 0.22 },
    { kind = "rect", x = -30, y = 161, w = 111, h = 111, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 137, y = 123, w = 69, h = 149, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 251, y = 151, w = 99, h = 121, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 408, y = 185, w = 103, h = 87, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 561, y = 184, w = 123, h = 88, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 728, y = 186, w = 130, h = 86, col = "black", a = 0.26, py = 0.12 },
    { kind = "rect", x = 909, y = 190, w = 93, h = 82, col = "black", a = 0.26, py = 0.12 },
    { kind = "girder", x = -16, y = 48, w = 992, h = 14, col = "black", a = 0.42, py = 0.3, step = 26 },
    { kind = "girder", x = -16, y = 108, w = 992, h = 14, col = "black", a = 0.34, py = 0.24, step = 30 },
    { kind = "hang", x = 556, y = 62, w = 2, h = 29, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 399, y = 62, w = 2, h = 40, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 778, y = 62, w = 2, h = 37, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
    { kind = "hang", x = 697, y = 62, w = 2, h = 54, col = "black", a = 0.5, py = 0.3, lw = 2, sway = 4, rate = 0.4, bob = true },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "rect", x = 225, y = 141, w = 2, h = 39, col = "rust", a = 0.3 },
    { kind = "rect", x = 299, y = 136, w = 2, h = 16, col = "rust", a = 0.3 },
    { kind = "rect", x = 374, y = 190, w = 4, h = 34, col = "rust", a = 0.3 },
    { kind = "rect", x = 140, y = 119, w = 3, h = 31, col = "rust", a = 0.3 },
    { kind = "rect", x = 520, y = 84, w = 2, h = 15, col = "rust", a = 0.3 },
    { kind = "rect", x = 234, y = 181, w = 5, h = 20, col = "rust", a = 0.3 },
    { kind = "rect", x = 490, y = 140, w = 4, h = 23, col = "rust", a = 0.3 },
    { kind = "rect", x = 284, y = 63, w = 5, h = 23, col = "rust", a = 0.3 },
    { kind = "rect", x = 455, y = 164, w = 3, h = 31, col = "rust", a = 0.3 },
    { kind = "rect", x = 744, y = 72, w = 5, h = 24, col = "rust", a = 0.3 },
    { kind = "rect", x = 48, y = 64, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 50, y = 66, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 142, y = 125, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 144, y = 127, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 115, y = 103, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 117, y = 105, w = 3, h = 5, col = "ember", a = 1 },
    { kind = "rect", x = 454, y = 56, w = 7, h = 9, col = "rust", a = 0.9 },
    { kind = "rect", x = 456, y = 58, w = 3, h = 5, col = "ember", a = 1 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 16, w = 1008, h = 16, col = "black", a = 0.9, py = -0.12, step = 34 },
    { kind = "hang", x = 747, y = 32, w = 2, h = 54, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 180, y = 32, w = 2, h = 30, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 412, y = 32, w = 2, h = 36, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 270, y = 32, w = 2, h = 68, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 775, y = 32, w = 2, h = 64, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "hang", x = 199, y = 32, w = 2, h = 51, col = "black", a = 0.85, py = -0.12, lw = 2, sway = 5, rate = 0.5, bob = true },
    { kind = "band", x = 0, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
    { kind = "band", x = 934, y = 0, w = 26, h = 272, col = "black", a = 0.55, a2 = 0.55, py = -0.06 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 51, y = 68, col = { 1.00, 0.62, 0.28 }, r = 58, flicker = 6.36 },
    { x = 145, y = 129, col = { 1.00, 0.62, 0.28 }, r = 58, flicker = 6.88 },
    { x = 118, y = 107, col = { 1.00, 0.62, 0.28 }, r = 52, flicker = 7.12 },
    { x = 457, y = 60, col = { 1.00, 0.62, 0.28 }, r = 42, flicker = 8.1 },
    { x = 893, y = 142, col = { 1.00, 0.86, 0.55 }, r = 51, flicker = 15.33 },
  },
  mapPos = { x = 3, y = 4, w = 3, h = 1 },
  map = [[
############################################################
############################################################
#################.........#.....#......##.........##########
########...#............................#..........#....####
#############...................................############
#############...................................############
##.......................h...........f....................##
##..................==========...=========................##
##..........h..................................w.h........##
##......=========............................=========....##
AA..........................DD%%%%%%......................CC
AA..........................DD............................CC
########......f.=========########.....=========.....########
##.....z.....###..........................................##
##..############..%%%%%%.#####..##.###..............f.....##
################....k....#############....k.........########
############################################################
]],
  key = {
    ["w"] = "welder",
    ["k"] = "rollpede",
    ["f"] = "plateframe",
    ["h"] = "scraphusk",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "scrap_3", "B" },
    C = { "scrap_secret", "A" },
    D = { "scrap_bay", "D" },
  },
}
