-- generated by scripts/genrooms.py
return {
  zone = "skyroot", music = "skyroot",
  -- ------------------------------------------------------------------
  -- THE CLIMB -- three depths of root and a long way up.
  --
  -- Three layers, and the only difference between them is where in the
  -- draw order they sit: backdrop is BEHIND the rock, scenery is over
  -- the rock but behind the bots, foreground is in front of everything.
  -- py < 0 is nearer than the world; py > 0 is further away.
  -- ------------------------------------------------------------------
  backdrop = {
    -- Three depths of root, each drifting at its own rate. Skyroot is
    -- the one place in the deep with real vertical travel, so depth
    -- here is bought with PARALLAX rather than with haze.
    { kind = "stack", x = -30, y = 120, w = 540, h = 220, col = "navy", a = 0.5, py = 0.42, step = 34, seed = 13 },
    { kind = "stack", x = -30, y = 260, w = 540, h = 220, col = "navy", a = 0.65, py = 0.28, step = 45, seed = 20 },
    { kind = "stack", x = -30, y = 400, w = 540, h = 180, col = "navy", a = 0.8, py = 0.14, step = 56, seed = 27 },
    -- cold light from somewhere far above
    { kind = "shaft", x = 144, y = 0, w = 70, h = 326, col = "sky", a = 0.13, py = 0.15, skew = 30 },
  },
  scenery = {
    -- motes, hanging in the column of air
    { kind = "rect", x = 90, y = 200, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 220, y = 120, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 330, y = 300, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 160, y = 420, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 400, y = 240, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 260, y = 470, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "band", x = 0, y = 0, w = 480, h = 244, col = "navy", a = 0.16, a2 = 0, py = 0.1 },
  },
  foreground = {
    -- near roots crossing the shaft
    { kind = "hang", x = 76, y = 0, w = 3, h = 184, col = "black", a = 0.9, py = -0.16, lw = 3, sway = 7, rate = 0.4 },
    { kind = "hang", x = 398, y = 0, w = 3, h = 152, col = "black", a = 0.9, py = -0.16, lw = 3, sway = 6, rate = 0.33 },
    { kind = "band", x = 0, y = 0, w = 26, h = 544, col = "black", a = 0.7, a2 = 0.7, py = -0.08 },
    { kind = "band", x = 454, y = 0, w = 26, h = 544, col = "black", a = 0.7, a2 = 0.7, py = -0.08 },
  },
  lights = {
    { x = 240, y = 80, r = 80, col = { 0.60, 0.82, 1.00 } },
    { x = 120, y = 330, r = 52, col = { 0.60, 0.82, 1.00 } },
    { x = 360, y = 470, r = 44, col = { 0.60, 0.82, 1.00 } },
  },
  mapPos = { x = 2, y = 3, w = 1, h = 3 },
  map = [[
##############BBB#############
##############BBB#############
##..........................##
##..........................##
##..........=====.=======...##
##..........................##
#########...................##
##..........................##
##..........l...............##
##........=======...........##
##..........................##
##......................y...##
##................#########.##
##........======............##
##....y.....................##
##=====.....................##
##..........................##
##..........................##
##......#############.......##
##..........................##
##..........................##
##....................======##
##..........................##
##..........................##
##............#######.......##
##..........................##
##..........................##
##...######.................##
##..........................##
##..z.......................##
##############...#############
##############...#############
##############AAA#############
##############AAA#############
]],
  key = {
    ["y"] = "windray",
    ["l"] = "sporeballoon",
    ["z"] = "checkpoint",
  },
  links = {
    A = { "moss_3", "C" },
    B = { "sky_2", "A" },
  },
}
