-- generated by scripts/genrooms.py
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 544, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 119, w = 120, h = 29, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 151, y = 119, w = 110, h = 17, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 339, y = 119, w = 203, h = 27, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 239, w = 121, h = 26, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 146, y = 239, w = 122, h = 18, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 374, y = 239, w = 190, h = 19, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 337, w = 168, h = 27, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 236, y = 337, w = 195, h = 30, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 498, y = 337, w = 140, h = 30, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 50, acc = "pine" },
    { kind = "column", x = 92, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 43, acc = "pine" },
    { kind = "column", x = 238, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 38, acc = "pine" },
    { kind = "column", x = 382, y = 0, w = 26, h = 544, col = "black", a = 0.42, py = 0.26, step = 39, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 36, acc = "pine" },
    { kind = "column", x = 117, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 52, acc = "pine" },
    { kind = "column", x = 241, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 36, acc = "pine" },
    { kind = "column", x = 428, y = 0, w = 40, h = 544, col = "black", a = 0.24, py = 0.15, step = 33, acc = "pine" },
    { kind = "girder", x = -16, y = 163, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 34 },
    { kind = "girder", x = -16, y = 315, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 40 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 331, y = 216, w = 2, h = 19, col = "pine", a = 0.36, lw = 2, sway = 5, rate = 0.53, bob = true },
    { kind = "hang", x = 246, y = 85, w = 2, h = 52, col = "pine", a = 0.38, lw = 2, sway = 3, rate = 0.57, bob = true },
    { kind = "hang", x = 306, y = 95, w = 2, h = 17, col = "pine", a = 0.61, lw = 2, sway = 3, rate = 0.57, bob = true },
    { kind = "hang", x = 159, y = 170, w = 2, h = 21, col = "pine", a = 0.58, lw = 2, sway = 8, rate = 0.3, bob = true },
    { kind = "hang", x = 362, y = 181, w = 2, h = 16, col = "pine", a = 0.39, lw = 2, sway = 6, rate = 0.39, bob = true },
    { kind = "hang", x = 302, y = 86, w = 2, h = 35, col = "pine", a = 0.45, lw = 2, sway = 6, rate = 0.37, bob = true },
    { kind = "hang", x = 265, y = 226, w = 2, h = 38, col = "pine", a = 0.43, lw = 2, sway = 4, rate = 0.32, bob = true },
    { kind = "hang", x = 92, y = 161, w = 2, h = 46, col = "pine", a = 0.45, lw = 2, sway = 6, rate = 0.35, bob = true },
    { kind = "rect", x = 300, y = 162, w = 4, h = 3, col = "leaf", a = 0.28 },
    { kind = "rect", x = 323, y = 387, w = 3, h = 4, col = "leaf", a = 0.2 },
    { kind = "rect", x = 291, y = 351, w = 6, h = 3, col = "leaf", a = 0.38 },
    { kind = "rect", x = 328, y = 447, w = 3, h = 2, col = "leaf", a = 0.2 },
    { kind = "rect", x = 437, y = 160, w = 6, h = 3, col = "leaf", a = 0.32 },
    { kind = "rect", x = 43, y = 137, w = 8, h = 3, col = "leaf", a = 0.39 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 21, w = 528, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 315, y = 36, w = 2, h = 63, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.73, bob = true },
    { kind = "hang", x = 312, y = 36, w = 2, h = 34, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 8, rate = 0.64, bob = true },
    { kind = "hang", x = 383, y = 36, w = 2, h = 58, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.53, bob = true },
    { kind = "hang", x = 257, y = 36, w = 2, h = 32, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 5, rate = 0.79, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 544, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 460, y = 0, w = 20, h = 544, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 65, col = { 0.72, 0.86, 1.00 }, r = 115, flicker = 0.8 },
  },
  mapPos = { x = 6, y = 2, w = 1, h = 2 },
  map = [[
##############BBB#############
##############BBB#############
##..........................##
##..........................##
##..........................CC
##......................z...CC
##....................########
##..................q.......##
##..........................##
##...............===........##
##....................b.....##
##..5.....k......y..........##
##..#####...........y.......##
##.........cccc..........y..##
##..............y...........##
##.................cccc.....##
##.....................y....##
##....b.......y.............##
##..........ccc.............##
##..........................##
##....l.....................##
#########...===.............##
##..........................##
##...................q......##
##................=======...##
##..........................##
##........b.................##
##......=======.............##
AA..........................##
AA.............U............##
##############################
##############################
##############################
##############################
]],
  key = {
    ["U"] = "updraft:30",
    ["l"] = "sporeballoon",
    ["y"] = "windray",
    ["k"] = "skylancer",
    ["z"] = "checkpoint",
    ["5"] = "capsule:cap_sky",
    ["q"] = "stormvane",
    ["b"] = "roostfang",
  },
  links = {
    A = { "sky_3", "B" },
    B = { "sky_boss", "A" },
    C = { "sky_nest", "A" },
  },
}
