-- generated by scripts/genrooms.py
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 59, w = 113, h = 14, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 106, y = 59, w = 172, h = 17, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 380, y = 59, w = 151, h = 19, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 119, w = 135, h = 22, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 213, y = 119, w = 185, h = 26, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 501, y = 119, w = 165, h = 28, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 168, w = 136, h = 19, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 168, y = 168, w = 205, h = 23, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 414, y = 168, w = 123, h = 23, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 45, acc = "pine" },
    { kind = "column", x = 91, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 32, acc = "pine" },
    { kind = "column", x = 219, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 32, acc = "pine" },
    { kind = "column", x = 317, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 50, acc = "pine" },
    { kind = "column", x = 438, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 43, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 46, acc = "pine" },
    { kind = "column", x = 203, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 34, acc = "pine" },
    { kind = "column", x = 365, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 33, acc = "pine" },
    { kind = "girder", x = -16, y = 81, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 43 },
    { kind = "girder", x = -16, y = 157, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 44 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 20, y = 37, w = 2, h = 39, col = "pine", a = 0.53, lw = 2, sway = 3, rate = 0.37, bob = true },
    { kind = "hang", x = 162, y = 131, w = 2, h = 16, col = "pine", a = 0.5, lw = 2, sway = 8, rate = 0.32, bob = true },
    { kind = "hang", x = 311, y = 0, w = 2, h = 18, col = "pine", a = 0.35, lw = 2, sway = 8, rate = 0.53, bob = true },
    { kind = "hang", x = 239, y = 109, w = 2, h = 24, col = "pine", a = 0.37, lw = 2, sway = 6, rate = 0.36, bob = true },
    { kind = "hang", x = 462, y = 112, w = 2, h = 54, col = "pine", a = 0.38, lw = 2, sway = 7, rate = 0.26, bob = true },
    { kind = "hang", x = 242, y = 30, w = 2, h = 43, col = "pine", a = 0.36, lw = 2, sway = 8, rate = 0.52, bob = true },
    { kind = "hang", x = 245, y = 51, w = 2, h = 48, col = "pine", a = 0.42, lw = 2, sway = 3, rate = 0.55, bob = true },
    { kind = "hang", x = 237, y = 21, w = 2, h = 50, col = "pine", a = 0.59, lw = 2, sway = 8, rate = 0.25, bob = true },
    { kind = "rect", x = 105, y = 43, w = 6, h = 2, col = "leaf", a = 0.22 },
    { kind = "rect", x = 112, y = 142, w = 4, h = 2, col = "leaf", a = 0.32 },
    { kind = "rect", x = 50, y = 148, w = 5, h = 3, col = "leaf", a = 0.32 },
    { kind = "rect", x = 144, y = 45, w = 5, h = 2, col = "leaf", a = 0.24 },
    { kind = "rect", x = 261, y = 208, w = 3, h = 3, col = "leaf", a = 0.3 },
    { kind = "rect", x = 316, y = 137, w = 5, h = 3, col = "leaf", a = 0.34 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 528, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 13, y = 25, w = 2, h = 42, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 8, rate = 0.43, bob = true },
    { kind = "hang", x = 436, y = 25, w = 2, h = 44, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.65, bob = true },
    { kind = "hang", x = 309, y = 25, w = 2, h = 66, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 10, rate = 0.43, bob = true },
    { kind = "hang", x = 384, y = 25, w = 2, h = 64, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 6, rate = 0.6, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 460, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 32, col = { 0.72, 0.86, 1.00 }, r = 116, flicker = 0.43 },
  },
  mapPos = { x = 1, y = 4, w = 1, h = 1 },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..........................##
##..AA......................##
##p.AA...p1.......2.........##
##############################
##############################
##############################
##############################
##############################
]],
  key = {
    ["p"] = "sporefly",
    ["1"] = "chest:chest_sky1:scrap:15",
    ["2"] = "chest:chest_sky2:bigshard:5",
  },
  links = {
    A = { "sky_2", "E" },
  },
}
