-- generated by scripts/genrooms.py
return {
  zone = "skyroot", music = "skyroot",
  -- ------------------------------------------------------------------
  -- THE AERIE -- sky watch, day 36,512. No relief.
  --
  -- Three layers, and the only difference between them is where in the
  -- draw order they sit: backdrop is BEHIND the rock, scenery is over
  -- the rock but behind the bots, foreground is in front of everything.
  -- py < 0 is nearer than the world; py > 0 is further away.
  -- ------------------------------------------------------------------
  backdrop = {
    -- Three depths of root, each drifting at its own rate. Skyroot is
    -- the one place in the deep with real vertical travel, so depth
    -- here is bought with PARALLAX rather than with haze.
    { kind = "stack", x = -30, y = 90, w = 1020, h = 180, col = "navy", a = 0.5, py = 0.42, step = 34, seed = 13 },
    { kind = "stack", x = -30, y = 170, w = 1020, h = 180, col = "navy", a = 0.65, py = 0.28, step = 45, seed = 20 },
    { kind = "stack", x = -30, y = 250, w = 1020, h = 150, col = "navy", a = 0.8, py = 0.14, step = 56, seed = 27 },
    -- cold light from somewhere far above
    { kind = "shaft", x = 288, y = 0, w = 70, h = 201, col = "sky", a = 0.13, py = 0.15, skew = 30 },
  },
  scenery = {
    -- motes, hanging in the column of air
    { kind = "rect", x = 160, y = 120, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 420, y = 90, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 700, y = 160, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "rect", x = 880, y = 220, w = 2, h = 2, col = "sky", a = 0.35, py = 0.55 },
    { kind = "band", x = 0, y = 0, w = 960, h = 151, col = "navy", a = 0.16, a2 = 0, py = 0.1 },
  },
  foreground = {
    -- near roots crossing the shaft
    { kind = "hang", x = 153, y = 0, w = 3, h = 114, col = "black", a = 0.9, py = -0.16, lw = 3, sway = 7, rate = 0.4 },
    { kind = "hang", x = 796, y = 0, w = 3, h = 94, col = "black", a = 0.9, py = -0.16, lw = 3, sway = 6, rate = 0.33 },
    { kind = "band", x = 0, y = 0, w = 26, h = 336, col = "black", a = 0.7, a2 = 0.7, py = -0.08 },
    { kind = "band", x = 934, y = 0, w = 26, h = 336, col = "black", a = 0.7, a2 = 0.7, py = -0.08 },
  },
  lights = {
    { x = 480, y = 70, r = 90, col = { 0.60, 0.82, 1.00 } },
    { x = 180, y = 240, r = 50, col = { 0.60, 0.82, 1.00 } },
    { x = 820, y = 240, r = 50, col = { 0.60, 0.82, 1.00 } },
  },
  arena = "aeriesentinel",
  mapPos = { x = 4, y = 1, w = 3, h = 1 },
  map = [[
############################################################
############################################################
####....................................................####
###......................................................###
##>......................................................<##
##>......................................................<##
##>......................................................<##
##>......................................................<##
##>......................................................<##
##>......................................................<##
##>....=========............................=========....<##
##>......................................................<##
##>.................####################.................<##
##>..........t......####################.................<##
##>...............#######################................<##
##>...............#######################................<##
##>...............#######################................<##
##>......====....##########################..............<##
###===...^^^^^^^^##########################^^^^^^...^^^^^###
######AAA########################################BBB########
######AAA########################################BBB########
]],
  key = {
    ["t"] = "boss:aeriesentinel",
  },
  links = {
    A = { "sky_4", "B" },
    -- The way home. Sealed until the Sentinel is down, so the shaft is a
    -- reward for the fight rather than a way around it.
    B = { "upper_stair", "A", req = "boss_aeriesentinel" },
  },
}
