-- generated by scripts/genvanes.py (The Drift Vanes)
return {
  zone = "skyroot", music = "skyroot",
  -- BEHIND the rock: stacked wrecks, gantries, haze
  backdrop = {
    { kind = "band", x = 0, y = 0, w = 480, h = 272, col = "navy", a = 0.05, a2 = 0.34, py = 0.03 },
    { kind = "band", x = -40, y = 59, w = 201, h = 17, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 255, y = 59, w = 128, h = 23, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = 495, y = 59, w = 214, h = 16, col = "sky", a = 0.2, a2 = 0, py = 0.06 },
    { kind = "band", x = -40, y = 119, w = 114, h = 25, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 166, y = 119, w = 171, h = 21, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = 449, y = 119, w = 121, h = 25, col = "sky", a = 0.15, a2 = 0, py = 0.11 },
    { kind = "band", x = -40, y = 168, w = 123, h = 21, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 177, y = 168, w = 143, h = 17, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "band", x = 369, y = 168, w = 116, h = 17, col = "sky", a = 0.11, a2 = 0, py = 0.16 },
    { kind = "column", x = -20, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 45, acc = "pine" },
    { kind = "column", x = 137, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 37, acc = "pine" },
    { kind = "column", x = 279, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 32, acc = "pine" },
    { kind = "column", x = 424, y = 0, w = 26, h = 272, col = "black", a = 0.42, py = 0.26, step = 39, acc = "pine" },
    { kind = "column", x = 13, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 43, acc = "pine" },
    { kind = "column", x = 133, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 34, acc = "pine" },
    { kind = "column", x = 248, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 50, acc = "pine" },
    { kind = "column", x = 388, y = 0, w = 40, h = 272, col = "black", a = 0.24, py = 0.15, step = 48, acc = "pine" },
    { kind = "girder", x = -16, y = 81, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 37 },
    { kind = "girder", x = -16, y = 157, w = 512, h = 12, col = "black", a = 0.3, py = 0.22, step = 35 },
  },
  -- welded to the world: rust runs and lamps
  scenery = {
    { kind = "hang", x = 283, y = 2, w = 2, h = 43, col = "pine", a = 0.37, lw = 2, sway = 6, rate = 0.53, bob = true },
    { kind = "hang", x = 442, y = 32, w = 2, h = 25, col = "pine", a = 0.57, lw = 2, sway = 8, rate = 0.35, bob = true },
    { kind = "hang", x = 11, y = 13, w = 2, h = 17, col = "pine", a = 0.39, lw = 2, sway = 5, rate = 0.37, bob = true },
    { kind = "hang", x = 416, y = 27, w = 2, h = 49, col = "pine", a = 0.43, lw = 2, sway = 4, rate = 0.46, bob = true },
    { kind = "hang", x = 124, y = 59, w = 2, h = 54, col = "pine", a = 0.52, lw = 2, sway = 3, rate = 0.31, bob = true },
    { kind = "hang", x = 84, y = 104, w = 2, h = 53, col = "pine", a = 0.6, lw = 2, sway = 7, rate = 0.29, bob = true },
    { kind = "hang", x = 124, y = 17, w = 2, h = 40, col = "pine", a = 0.52, lw = 2, sway = 7, rate = 0.41, bob = true },
    { kind = "hang", x = 11, y = 102, w = 2, h = 16, col = "pine", a = 0.44, lw = 2, sway = 3, rate = 0.47, bob = true },
    { kind = "rect", x = 315, y = 75, w = 6, h = 2, col = "leaf", a = 0.33 },
    { kind = "rect", x = 67, y = 127, w = 6, h = 4, col = "leaf", a = 0.2 },
    { kind = "rect", x = 90, y = 94, w = 4, h = 2, col = "leaf", a = 0.19 },
    { kind = "rect", x = 340, y = 39, w = 5, h = 2, col = "leaf", a = 0.36 },
    { kind = "rect", x = 14, y = 146, w = 5, h = 4, col = "leaf", a = 0.26 },
    { kind = "rect", x = 9, y = 140, w = 3, h = 4, col = "leaf", a = 0.36 },
  },
  -- NEARER than the world -- it overtakes you
  foreground = {
    { kind = "girder", x = -24, y = 10, w = 528, h = 15, col = "black", a = 0.88, py = -0.13, step = 40 },
    { kind = "hang", x = 22, y = 25, w = 2, h = 39, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 8, rate = 0.62, bob = true },
    { kind = "hang", x = 417, y = 25, w = 2, h = 34, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 5, rate = 0.54, bob = true },
    { kind = "hang", x = 346, y = 25, w = 2, h = 46, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 11, rate = 0.69, bob = true },
    { kind = "hang", x = 376, y = 25, w = 2, h = 69, col = "black", a = 0.8, py = -0.13, lw = 2, sway = 6, rate = 0.41, bob = true },
    { kind = "band", x = 0, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
    { kind = "band", x = 460, y = 0, w = 20, h = 272, col = "black", a = 0.42, a2 = 0.42, py = -0.05 },
  },
  -- additive; the lamps and one welding arc
  lights = {
    { x = 240, y = 32, col = { 0.72, 0.86, 1.00 }, r = 114, flicker = 0.48 },
  },
  mapPos = { x = 7, y = 2, w = 1, h = 1 },
  map = [[
##############################
##############################
##..........................##
##..........................##
##..........................##
##................p.........##
##................======....##
##....p.....................##
##....=====.................##
##..........................##
AA..........................##
AAp......1.....N.3..........##
##############################
##############################
##############################
##############################
##############################
]],
  key = {
    ["p"] = "sporefly",
    ["1"] = "sign:sign_perch2",
    ["N"] = "nest",
    ["3"] = "chest:chest_driftvanes:module:driftvanes",
  },
  links = {
    A = { "sky_4", "C" },
  },
}
