#!/usr/bin/env python3
"""One-shot generator for the Coldstore + Cradle rooms (v4.0 Phase B).
Builds exact-width ASCII maps with assertions, then writes the .lua files.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "game", "src", "data", "rooms")


def grid(w, h, floor_row):
    """Bordered room: rows 0-1 solid, interior, floor_row..h-1 solid."""
    rows = []
    for y in range(h):
        if y < 2 or y >= floor_row:
            rows.append(["#"] * w)
        else:
            rows.append(["#", "#"] + ["."] * (w - 4) + ["#", "#"])
    return rows


def put(rows, y, x0, s):
    for i, ch in enumerate(s):
        rows[y][x0 + i] = ch


def hspan(rows, y, x0, x1, ch):
    for x in range(x0, x1 + 1):
        rows[y][x] = ch


def vspan(rows, y0, y1, x, ch):
    for y in range(y0, y1 + 1):
        rows[y][x] = ch


def door_side(rows, y0, x, ch):
    for y in (y0, y0 + 1):
        rows[y][x] = ch
        rows[y][x + 1] = ch


def render(rows, w):
    out = []
    for r in rows:
        s = "".join(r)
        assert len(s) == w, f"row width {len(s)} != {w}: {s}"
        out.append(s)
    return "\n".join(out)


def write_room(name, zone, music, mappos, rows, w, key, links, extra=""):
    body = render(rows, w)
    keys = "\n".join(f'    ["{k}"] = "{v}",' for k, v in key.items())
    lks = "\n".join(f'    {k} = {{ "{a}", "{b}" }},' for k, (a, b) in links.items())
    src = f"""-- generated by scripts/gen_coldstore.py (v4.0 Phase B)
return {{
  zone = "{zone}", music = "{music}",
  mapPos = {{ x = {mappos[0]}, y = {mappos[1]}, w = {mappos[2]}, h = {mappos[3]} }},
{extra}  map = [[
{body}
]],
  key = {{
{keys}
  }},
  links = {{
{lks}
  }},
}}
"""
    path = os.path.join(OUT, name + ".lua")
    open(path, "w").write(src)
    print("wrote", path)


W, H, FLOOR = 60, 17, 12

# ---------------------------------------------------------------- cold_1
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
door_side(r, 10, 58, "B")
vspan(r, 2, 11, 30, "G")
hspan(r, 8, 14, 19, "=")
hspan(r, 7, 36, 41, "=")
put(r, 11, 8, "1")
put(r, 11, 24, "z")
put(r, 6, 40, "f")
put(r, 11, 48, "m")
write_room("cold_1", "coldstore", "coldstore", (0, 0, 3, 1), r, W,
           {"1": "sign:sign_coldstore", "z": "checkpoint",
            "f": "frostwisp", "m": "icemaw"},
           {"A": ("crys_4", "C"), "B": ("cold_2", "A")},
           extra='  gates = { G = "cryocoils" },\n')

# ---------------------------------------------------------------- cold_2
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
door_side(r, 10, 58, "B")
door_side(r, 4, 58, "E")
hspan(r, 6, 52, 57, "#")   # ledge up to the secret door
hspan(r, 8, 30, 36, "=")
hspan(r, 8, 44, 50, "=")   # step toward the ledge
put(r, 11, 8, "t")
put(r, 11, 12, "s")
put(r, 11, 16, "1")
put(r, 11, 30, "h")
put(r, 11, 44, "h")
put(r, 4, 48, "f")
write_room("cold_2", "coldstore", "coldstore", (3, 0, 3, 1), r, W,
           {"t": "teleporter:coldstore", "s": "save", "1": "sign:sign_stacks",
            "h": "shelverbot", "f": "frostwisp"},
           {"A": ("cold_1", "B"), "B": ("cold_3", "A"), "E": ("cold_secret", "A")},
           extra="  cold = true, ice = true,\n  hasSave = true,\n  hasTeleporter = true,\n")

# ---------------------------------------------------------------- cold_3
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
door_side(r, 10, 58, "B")
hspan(r, 8, 24, 30, "#")   # thawplate stand
vspan(r, 2, 11, 40, "G")
hspan(r, 8, 46, 50, "=")
put(r, 7, 26, "w")
put(r, 7, 48, "5")
put(r, 11, 20, "2")
put(r, 11, 14, "m")
put(r, 11, 34, "m")
put(r, 5, 50, "f")
write_room("cold_3", "coldstore", "coldstore", (6, 0, 3, 1), r, W,
           {"w": "thawplate:thaw_cold3", "5": "capsule:cap_cold",
            "2": "sign:sign_thaw", "m": "icemaw", "f": "frostwisp"},
           {"A": ("cold_2", "B"), "B": ("cold_4", "A")},
           extra='  cold = true, ice = true,\n  gates = { G = "thaw_cold3" },\n')

# ---------------------------------------------------------------- cold_4
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
door_side(r, 10, 58, "B")
hspan(r, 8, 8, 13, "=")
put(r, 11, 18, "1")
put(r, 11, 24, "k")
put(r, 11, 30, "s")
put(r, 11, 46, "h")
write_room("cold_4", "coldstore", "coldstore", (9, 0, 3, 1), r, W,
           {"1": "sign:sign_office", "k": "npc:lock", "s": "save",
            "h": "shelverbot"},
           {"A": ("cold_3", "B"), "B": ("cold_5", "A")},
           extra="  hasSave = true,\n")

# ---------------------------------------------------------------- cold_5
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
door_side(r, 10, 58, "B")
hspan(r, 8, 14, 20, "=")
hspan(r, 7, 26, 31, "=")
vspan(r, 2, 11, 40, "G")
vspan(r, 2, 11, 52, "H")
put(r, 11, 36, "w")
put(r, 11, 44, "T")
put(r, 11, 32, "2")
put(r, 11, 12, "m")
put(r, 11, 24, "m")
put(r, 11, 18, "h")
put(r, 4, 46, "f")
write_room("cold_5", "coldstore", "coldstore", (12, 0, 3, 1), r, W,
           {"w": "thawplate:thaw_cold5", "T": "tank:tank_cold",
            "2": "sign:sign_falsewall", "m": "icemaw", "h": "shelverbot",
            "f": "frostwisp"},
           {"A": ("cold_4", "B"), "B": ("cold_boss", "A")},
           extra='  cold = true, ice = true,\n  gates = { G = "thaw_cold5", H = "cradle_found" },\n')

# ---------------------------------------------------------------- cold_boss
BH, BFLOOR = 22, 17
r = grid(W, BH, BFLOOR)
door_side(r, 15, 0, "A")
door_side(r, 15, 58, "B")
vspan(r, 2, 16, 54, "G")
hspan(r, 13, 12, 18, "=")
hspan(r, 13, 42, 48, "=")
hspan(r, 10, 26, 34, "=")
put(r, 16, 6, "z")
put(r, 16, 30, "a")
write_room("cold_boss", "coldstore", "coldstore", (15, 0, 3, 1), r, W,
           {"z": "checkpoint", "a": "boss:archivist"},
           {"A": ("cold_5", "B"), "B": ("cradle_1", "A")},
           extra='  gates = { G = "boss_archivist" },\n')

# ---------------------------------------------------------------- cradle_1
r = grid(W, H, FLOOR)
door_side(r, 10, 0, "A")
hspan(r, 7, 12, 50, "=")
put(r, 11, 5, "s")
for x in (10, 14, 18, 22, 26, 34, 38, 42, 46, 50):
    put(r, 11, x, "p")
for x in (16, 24, 32, 40, 48):
    put(r, 6, x, "p")
put(r, 11, 30, "r")
write_room("cradle_1", "cradle", "cradle", (0, 0, 3, 1), r, W,
           {"s": "save", "p": "pod", "r": "sign:cradle_record"},
           {"A": ("cold_boss", "B")},
           extra="  dark = 0.55,\n  hasSave = true,\n")

# ---------------------------------------------------------------- cold_secret
SW = 30
r = grid(SW, H, FLOOR)
door_side(r, 10, 0, "A")
put(r, 11, 10, "3")
put(r, 11, 16, "4")
put(r, 11, 22, "1")
put(r, 5, 20, "f")
write_room("cold_secret", "coldstore", "coldstore", (3, 1, 1, 1), r, SW,
           {"3": "chest:ch_cold1:scrap:30", "4": "chest:ch_cold2:bigshard:6",
            "1": "sign:sign_coldsecret", "f": "frostwisp"},
           {"A": ("cold_2", "E")},
           extra="  cold = true,\n")

print("done")
