#!/usr/bin/env python3
"""Generate the remaining Emberdeep rooms with exact-placement geometry."""
import os

OUT = "src/data/rooms"

class Room:
    def __init__(self, w, h):
        self.w, self.h = w, h
        self.g = [["#"] * w for _ in range(h)]

    def open_box(self, x0, y0, x1, y1, ch="."):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.g[y][x] = ch

    def interior(self, wall=2, top=2, bottom=None):
        """Open the standard interior: walls of `wall` thickness, floor row."""
        bottom = bottom if bottom is not None else self.h - 5
        self.open_box(wall, top, self.w - wall - 1, bottom)

    def put(self, x, y, s):
        for i, ch in enumerate(s):
            self.g[y][x + i] = ch

    def vput(self, x, y, s):
        for i, ch in enumerate(s):
            self.g[y + i][x] = ch

    def hline(self, x0, x1, y, ch="#"):
        for x in range(x0, x1 + 1):
            self.g[y][x] = ch

    def platform(self, x0, x1, y):
        self.hline(x0, x1, y, "#")

    def oneway(self, x0, x1, y):
        self.hline(x0, x1, y, "=")

    def door_left(self, ch, y0, y1):
        for y in range(y0, y1 + 1):
            self.g[y][0] = ch
            self.g[y][1] = ch

    def door_right(self, ch, y0, y1):
        for y in range(y0, y1 + 1):
            self.g[y][self.w - 1] = ch
            self.g[y][self.w - 2] = ch

    def door_top(self, ch, x0, x1):
        for x in range(x0, x1 + 1):
            self.g[0][x] = ch
            self.g[1][x] = ch

    def door_bottom(self, ch, x0, x1):
        for x in range(x0, x1 + 1):
            self.g[self.h - 1][x] = ch
            self.g[self.h - 2][x] = ch

    def text(self):
        return "\n".join("".join(r) for r in self.g)

def emit(name, room, zone, music, key, links, extra=""):
    key_lines = "\n".join(
        f'    ["{k}"] = "{v}",' for k, v in key.items())
    link_lines = "\n".join(
        f'    {k} = {{ "{v[0]}", "{v[1]}" }},' for k, v in links.items())
    src = f"""-- generated by scripts/genrooms.py
return {{
  zone = "{zone}", music = "{music}",
{extra}  map = [[
{room.text()}
]],
  key = {{
{key_lines}
  }},
  links = {{
{link_lines}
  }},
}}
"""
    with open(os.path.join(OUT, name + ".lua"), "w") as f:
        f.write(src)
    print("wrote", name)

# ==================================================================
# MOSS_4: twin latch-plate vault -> Spark Jump module
# ==================================================================
r = Room(60, 17)
r.interior(2, 2, 11)
# floor is rows 12+; doors rows 10-11
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# vault walls at cols 29 and 39, roof row 8
r.hline(29, 39, 8)
r.vput(29, 9, ".")   # will become gate below
r.vput(39, 9, ".")
for y in (9, 10, 11):
    r.g[y][29] = "G"
    r.g[y][39] = "H"
r.put(33, 11, "3")           # chest inside vault
r.put(20, 11, "x")           # plate 1
r.put(50, 11, "y")           # plate 2
r.put(4, 11, "z")            # checkpoint
r.put(6, 11, "1")            # sign
r.oneway(10, 14, 5)
r.platform(22, 26, 6)
r.put(23, 5, "p")
r.oneway(44, 48, 6)
r.put(46, 5, "g")
r.put(24, 11, "r")
emit("moss_4", r, "mosswood", "mosswood", {
    "1": "sign:sign_plates",
    "3": "chest:chest_sparkjump:module:sparkjump",
    "x": "plate:plate_m4a:latch",
    "y": "plate:plate_m4b:latch",
    "z": "checkpoint",
    "p": "spitter", "g": "gnat", "r": "rollpede",
}, {
    "A": ("moss_3", "A"),
    "B": ("moss_5", "A"),
}, extra='  mapPos = { x = 7, y = 0, w = 2, h = 1 },\n'
   '  gates = { G = "plate_m4a", H = "plate_m4b" },\n')

# ==================================================================
# FLOODED WORKS
# ==================================================================
# flood_1: shallow pools intro
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# two water pools sunk into the floor
for x0, x1 in ((14, 22), (36, 46)):
    r.open_box(x0, 12, x1, 14, "~")
r.put(6, 11, "z")
r.put(17, 10, "f")
r.put(40, 10, "f")
r.put(28, 11, "b")
r.oneway(24, 30, 7)
r.put(26, 6, "1")
emit("flood_1", r, "flooded", "flooded", {
    "z": "checkpoint", "f": "finfish", "b": "bubbler",
    "1": "sign:sign_flood",
}, {
    "A": ("moss_boss", "B"),
    "B": ("flood_2", "A"),
}, extra='  mapPos = { x = 0, y = 0, w = 3, h = 1 },\n')

# flood_2: half-submerged hall, crabs on the docks
r = Room(60, 26)
r.interior(2, 2, 20)
r.door_left("A", 19, 20)
r.door_right("B", 8, 9)
# water fills lower half
r.open_box(2, 14, 57, 20, "~")
# docks (oneways) above water
r.oneway(6, 14, 13)
r.oneway(20, 28, 10)
r.oneway(34, 42, 13)
r.oneway(46, 54, 10)
# upper ledge to door B
r.platform(48, 57, 10)
r.put(50, 9, "c")
r.put(24, 9, "c")
r.put(10, 19, "f")
r.put(30, 19, "f")
r.put(40, 19, "m")
r.put(8, 12, "b")
# deep passage down-right gated by hydroseals
r.door_bottom("D", 50, 52)
for y in (21, 22, 23):
    for x in (50, 51, 52):
        r.g[y][x] = "G"
r.open_box(50, 21, 52, 23, "G")
emit("flood_2", r, "flooded", "flooded", {
    "z": "checkpoint", "f": "finfish", "b": "bubbler", "c": "crab",
    "m": "depthmine",
}, {
    "A": ("flood_1", "B"),
    "B": ("flood_3", "A"),
    "D": ("flood_deep1", "A"),
}, extra='  mapPos = { x = 3, y = 0, w = 3, h = 2 },\n'
   '  gates = { G = "hydroseals" },\n')

# flood_3: warden approach with save
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.open_box(24, 12, 34, 14, "~")
r.put(8, 11, "s")
r.put(12, 11, "1")
r.put(28, 10, "m")
r.put(44, 11, "c")
r.oneway(18, 23, 8)
r.oneway(36, 41, 8)
r.put(20, 7, "b")
emit("flood_3", r, "flooded", "flooded", {
    "s": "save", "1": "sign:sign_warden", "m": "depthmine",
    "c": "crab", "b": "bubbler",
}, {
    "A": ("flood_2", "B"),
    "B": ("flood_warden", "A"),
}, extra='  mapPos = { x = 6, y = 0, w = 3, h = 1 },\n  hasSave = true,\n')

# flood_warden: miniboss arena
r = Room(40, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.put(10, 11, "t")
r.oneway(8, 12, 7)
r.oneway(27, 31, 7)
emit("flood_warden", r, "flooded", "flooded", {
    "t": "boss:rustwarden",
}, {
    "A": ("flood_3", "B"),
    "B": ("flood_4", "A"),
}, extra='  mapPos = { x = 9, y = 0, w = 2, h = 1 },\n')

# flood_4: diving halls (hydroseals now); hammer + grapple vault
r = Room(60, 26)
r.interior(2, 2, 20)
r.door_left("A", 8, 9)
r.door_right("B", 8, 9)
# entry ledges high and dry
r.platform(2, 12, 10)
r.platform(47, 57, 10)
r.oneway(20, 26, 10)
r.oneway(32, 38, 10)
# deep water below
r.open_box(2, 11, 57, 20, "~")
# sunken structure maze
r.platform(10, 20, 15)
r.platform(30, 40, 14)
r.platform(18, 26, 18)
r.vput(30, 15, "#")
r.vput(30, 16, "#")
# hammer chest in mid pocket
r.put(34, 13, "2")
# grapple vault: sealed floor pocket, breakable entrance
r.open_box(44, 17, 52, 19, ".")
r.hline(44, 52, 16)
r.g[16][48] = "%"
r.put(47, 19, "3")
r.put(14, 19, "f")
r.put(24, 13, "m")
r.put(52, 13, "f")
r.put(8, 9, "z")
# top passage to hub
r.door_top("C", 28, 30)
emit("flood_4", r, "flooded", "flooded", {
    "2": "chest:brassa_hammer:scrap:5",
    "3": "chest:chest_grapple:module:grapple",
    "f": "finfish", "m": "depthmine", "z": "checkpoint",
}, {
    "A": ("flood_warden", "B"),
    "B": ("flood_5", "A"),
    "C": ("flood_hub", "A"),
}, extra='  mapPos = { x = 11, y = 0, w = 3, h = 2 },\n')

# flood_hub: dry deck with teleporter
r = Room(30, 17)
r.interior(2, 2, 11)
r.door_bottom("A", 14, 16)
r.put(8, 11, "t")
r.put(20, 11, "s")
r.put(4, 11, "1")
emit("flood_hub", r, "flooded", "flooded", {
    "t": "teleporter:flooded", "s": "save", "1": "sign:sign_hub",
}, {
    "A": ("flood_4", "C"),
}, extra='  mapPos = { x = 12, y = -1, w = 1, h = 1 },\n'
   '  hasSave = true,\n  hasTeleporter = true,\n')

# flood_5: pump approach, energy tank behind plates
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.open_box(14, 12, 20, 14, "~")
r.open_box(38, 12, 44, 14, "~")
r.put(16, 10, "b")
r.put(41, 10, "b")
r.put(30, 11, "c")
r.put(52, 11, "c")
# tank vault on high shelf, gate opens by latch plate across the room
r.platform(24, 32, 6)
r.g[5][28] = "4"
for y in (3, 4, 5):
    r.g[y][24] = "G"
r.hline(24, 32, 2)
r.vput(32, 3, "#")
r.vput(32, 4, "#")
r.vput(32, 5, "#")
r.put(6, 11, "x")
r.oneway(18, 22, 7)
r.oneway(10, 14, 4)
emit("flood_5", r, "flooded", "flooded", {
    "4": "tank:tank_flood", "b": "bubbler", "c": "crab",
    "x": "plate:plate_f5:latch",
}, {
    "A": ("flood_4", "B"),
    "B": ("flood_boss", "A"),
}, extra='  mapPos = { x = 14, y = 0, w = 3, h = 1 },\n'
   '  gates = { G = "plate_f5" },\n')

# flood_boss: the Tide Engine
r = Room(60, 22)
r.interior(2, 2, 16)
r.door_left("A", 15, 16)
r.door_right("B", 15, 16)
r.oneway(10, 16, 12)
r.oneway(43, 49, 12)
r.oneway(26, 33, 9)
r.put(20, 16, "t")
emit("flood_boss", r, "flooded", "flooded", {
    "t": "boss:tideengine",
}, {
    "A": ("flood_5", "B"),
    "B": ("furn_1", "A"),
}, extra='  mapPos = { x = 17, y = 0, w = 3, h = 1 },\n')

# flood_deep1: hydroseal depths -> crystal
r = Room(60, 26)
r.interior(2, 2, 20)
r.door_top("A", 8, 10)
r.door_bottom("B", 50, 52)
r.open_box(2, 6, 57, 20, "~")
r.platform(12, 22, 12)
r.platform(30, 42, 16)
r.platform(8, 16, 19)
r.put(14, 11, "m")
r.put(34, 15, "m")
r.put(20, 19, "f")
r.put(44, 19, "f")
r.put(52, 19, "f")
r.put(36, 15, "5")
r.put(4, 19, "z")
emit("flood_deep1", r, "flooded", "flooded", {
    "m": "depthmine", "f": "finfish", "z": "checkpoint",
    "5": "capsule:cap_flood",
}, {
    "A": ("flood_2", "D"),
    "B": ("crys_1", "A"),
}, extra='  mapPos = { x = 4, y = 2, w = 2, h = 2 },\n')

# ==================================================================
# FURNACE DEPTHS
# ==================================================================
# furn_1: grapple shaft descent
r = Room(30, 32)
r.interior(2, 2, 27)
r.door_left("A", 4, 5)
r.door_bottom("B", 14, 16)
r.platform(2, 8, 6)
# gate right after entry requires grapple
for y in (3, 4, 5):
    r.g[y][9] = "G"
# anchors zig-zag down over lava
r.open_box(2, 28, 27, 29, "L")
r.put(14, 8, "n")
r.put(20, 13, "n")
r.put(8, 18, "n")
r.put(16, 23, "n")
r.platform(12, 18, 26)   # safe island above lava, over the exit
r.put(4, 11, "1")
r.platform(2, 6, 12)
r.put(24, 20, "a")
emit("furn_1", r, "furnace", "furnace", {
    "n": "anchor", "a": "cinderbat", "1": "sign:sign_furnace",
}, {
    "A": ("flood_boss", "B"),
    "B": ("furn_2", "A"),
}, extra='  mapPos = { x = 1, y = -1, w = 1, h = 2 },\n'
   '  gates = { G = "grapple" },\n')

# furn_2: lava flats
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_top("A", 6, 8)
r.door_right("B", 10, 11)
r.open_box(14, 12, 22, 14, "L")
r.open_box(34, 12, 44, 14, "L")
r.platform(16, 20, 9)
r.platform(37, 41, 9)
r.oneway(25, 31, 8)
r.put(18, 8, "a")
r.put(38, 8, "o")
r.put(28, 11, "z")
r.put(50, 11, "o")
emit("furn_2", r, "furnace", "furnace", {
    "a": "cinderbat", "o": "slagblob", "z": "checkpoint",
}, {
    "A": ("furn_1", "B"),
    "B": ("furn_3", "A"),
}, extra='  mapPos = { x = 0, y = 1, w = 3, h = 1 },\n')

# furn_3: cooling station (save + teleporter)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.put(10, 11, "s")
r.put(16, 11, "t")
r.put(6, 11, "1")
r.put(30, 11, "w")
r.put(44, 11, "e")
r.oneway(24, 30, 7)
emit("furn_3", r, "furnace", "furnace", {
    "s": "save", "t": "teleporter:furnace", "1": "sign:sign_depths",
    "w": "welder", "e": "shieldbug",
}, {
    "A": ("furn_2", "B"),
    "B": ("furn_golem", "A"),
    "C": ("furn_3", "A"),
}, extra='  mapPos = { x = 3, y = 1, w = 3, h = 1 },\n'
   '  hasSave = true,\n  hasTeleporter = true,\n')

# furn_golem: slag golem arena
r = Room(40, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.put(12, 11, "t")
emit("furn_golem", r, "furnace", "furnace", {
    "t": "boss:slaggolem",
}, {
    "A": ("furn_3", "B"),
    "B": ("furn_4", "A"),
}, extra='  mapPos = { x = 6, y = 1, w = 2, h = 1 },\n')

# furn_4: the vault of heat plating (Lu energize opens it)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# vault chamber right of center
r.hline(36, 46, 7)
for y in (8, 9, 10, 11):
    r.g[y][36] = "G"
    r.g[y][46] = "#"
r.put(40, 11, "3")
r.put(30, 11, "M")
r.put(10, 11, "e")
r.put(20, 11, "e")
r.oneway(12, 18, 7)
r.put(14, 6, "w")
# heat gate to furn_5 right before door B
for y in (9, 10, 11):
    r.g[y][54] = "H"
emit("furn_4", r, "furnace", "furnace", {
    "3": "chest:chest_heatplate:module:heatplating",
    "M": "machine:furnvault:Vault_seals_release",
    "e": "shieldbug", "w": "welder",
}, {
    "A": ("furn_golem", "B"),
    "B": ("furn_5", "A"),
}, extra='  mapPos = { x = 8, y = 1, w = 3, h = 1 },\n'
   '  gates = { G = "furnvault", H = "heatplating" },\n')

# furn_5: the deep heat (hot room)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.open_box(10, 12, 50, 14, "L")
# crumble hop chain over lava
for x0 in (12, 20, 28, 36, 44):
    r.hline(x0, x0 + 2, 11, "c")
r.platform(30, 34, 7)
r.put(31, 6, "5")
r.put(16, 6, "a")
r.put(40, 6, "w")
r.oneway(22, 26, 5)
emit("furn_5", r, "furnace", "furnace", {
    "5": "capsule:cap_furn", "a": "cinderbat", "w": "welder",
}, {
    "A": ("furn_4", "B"),
    "B": ("furn_6", "A"),
}, extra='  mapPos = { x = 11, y = 1, w = 3, h = 1 },\n  hot = true,\n')

# furn_6: descent to the crucible (hot)
r = Room(30, 32)
r.interior(2, 2, 27)
r.door_left("A", 6, 7)
r.door_bottom("B", 14, 16)
r.platform(2, 8, 8)
r.platform(12, 18, 12)
r.platform(20, 27, 16)
r.platform(8, 16, 20)
r.platform(2, 6, 24)
r.platform(12, 18, 27)
r.put(14, 11, "x")
for y in (25, 26, 27):
    r.g[y][19] = "G"
r.put(22, 27, "4")
r.put(24, 27, "z")
r.put(10, 19, "a")
r.put(15, 26, "a")
r.open_box(2, 28, 27, 29, "L")
emit("furn_6", r, "furnace", "furnace", {
    "x": "plate:plate_furn6:latch", "4": "tank:tank_furn",
    "z": "checkpoint", "a": "cinderbat",
}, {
    "A": ("furn_5", "B"),
    "B": ("furn_boss", "A"),
}, extra='  mapPos = { x = 14, y = 0, w = 1, h = 2 },\n'
   '  hot = true,\n  gates = { G = "plate_furn6" },\n')

# furn_boss: the Crucible
r = Room(60, 22)
r.interior(2, 2, 16)
r.door_top("A", 6, 8)
r.oneway(10, 18, 12)
r.oneway(41, 49, 12)
r.oneway(25, 34, 8)
r.put(20, 16, "t")
r.put(6, 16, "1")
emit("furn_boss", r, "furnace", "furnace", {
    "t": "boss:crucible", "1": "sign:sign_link2",
}, {
    "A": ("furn_6", "B"),
}, extra='  mapPos = { x = 13, y = 2, w = 3, h = 1 },\n')

# ==================================================================
# CRYSTAL HOLLOWS
# ==================================================================
# crys_1: drowned gate into the hollows
r = Room(60, 26)
r.interior(2, 2, 20)
r.door_top("A", 8, 10)
r.door_right("B", 19, 20)
r.open_box(2, 4, 30, 12, "~")
r.platform(2, 34, 13)
r.open_box(31, 4, 34, 12, ".")
r.put(10, 12, "f")
r.put(22, 12, "m")
r.put(6, 19, "z")
r.put(18, 19, "d")
r.put(40, 19, "d")
r.oneway(36, 42, 15)
r.put(50, 19, "1")
emit("crys_1", r, "crystal", "crystal", {
    "f": "finfish", "m": "depthmine", "z": "checkpoint",
    "d": "shardling", "1": "sign:sign_crystal",
}, {
    "A": ("flood_deep1", "B"),
    "B": ("crys_2", "A"),
}, extra='  mapPos = { x = 0, y = 0, w = 3, h = 2 },\n')

# crys_2: song chamber (save + teleporter + secret)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.put(8, 11, "s")
r.put(14, 11, "t")
r.put(30, 11, "w")
r.put(44, 11, "u")
r.oneway(22, 28, 7)
r.put(24, 6, "w")
# secret behind breakable in right wall
for y in (9, 10, 11):
    r.g[y][52] = "%"
r.g[10][53] = "E"
r.g[11][53] = "E"
r.g[10][54] = "E"
r.g[11][54] = "E"
emit("crys_2", r, "crystal", "crystal", {
    "s": "save", "t": "teleporter:crystal", "w": "prismwisp",
    "u": "cryoturret",
}, {
    "A": ("crys_1", "B"),
    "B": ("crys_3", "A"),
    "C": ("crys_2", "A"),
    "E": ("crys_secret", "A"),
}, extra='  mapPos = { x = 3, y = 1, w = 3, h = 1 },\n'
   '  hasSave = true,\n  hasTeleporter = true,\n')

# crys_secret: glittering hoard
r = Room(30, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.put(10, 11, "1")
r.put(16, 11, "2")
emit("crys_secret", r, "crystal", "crystal", {
    "1": "chest:chest_crys1:scrap:20",
    "2": "chest:chest_crys2:bigshard:6",
}, {
    "A": ("crys_2", "E"),
}, extra='  mapPos = { x = 6, y = 2, w = 1, h = 1 },\n')

# crys_3: the light bridges (timed plates!)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# chasm floor of spikes between two plate pedestals
r.open_box(14, 12, 45, 14, ".")
r.hline(14, 45, 15, "^")
# bridge of gate tiles across the chasm at row 11
for x in range(14, 46):
    r.g[11][x] = "G"
r.put(8, 11, "x")
r.put(50, 11, "y")
r.put(4, 11, "1")
r.put(24, 6, "w")
r.put(36, 6, "w")
r.put(52, 11, "4")
emit("crys_3", r, "crystal", "crystal", {
    "x": "plate:plate_c3a", "y": "plate:plate_c3b",
    "1": "sign:sign_bridge", "w": "prismwisp",
    "4": "tank:tank_crys",
}, {
    "A": ("crys_2", "B"),
    "B": ("crys_4", "A"),
}, extra='  mapPos = { x = 6, y = 1, w = 3, h = 1 },\n'
   '  gates = { G = "plate_c3a" },\n')

# crys_4: crystal shaft ascent
r = Room(30, 32)
r.interior(2, 2, 27)
r.door_left("A", 26, 27)
r.door_top("B", 14, 16)
r.platform(20, 26, 24)
r.platform(8, 14, 20)
r.put(10, 16, "n")
r.platform(18, 24, 14)
r.put(20, 10, "n")
r.platform(4, 10, 8)
r.platform(14, 20, 4)
r.put(6, 7, "u")
r.put(22, 13, "w")
r.put(12, 19, "d")
r.put(24, 23, "z")
emit("crys_4", r, "crystal", "crystal", {
    "n": "anchor", "u": "cryoturret", "w": "prismwisp",
    "d": "shardling", "z": "checkpoint",
}, {
    "A": ("crys_3", "B"),
    "B": ("crys_5", "A"),
}, extra='  mapPos = { x = 9, y = 0, w = 1, h = 2 },\n')

# crys_5: the resonant gauntlet
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_bottom("A", 6, 8)
r.door_right("B", 10, 11)
r.put(12, 11, "d")
r.put(20, 11, "d")
r.put(28, 6, "u")
r.put(36, 11, "w")
r.put(44, 6, "u")
r.oneway(24, 30, 8)
r.oneway(40, 46, 8)
# capsule behind breakables high left
r.platform(6, 12, 5)
r.g[4][8] = "%"
r.g[4][9] = "%"
r.g[3][8] = "5"
emit("crys_5", r, "crystal", "crystal", {
    "d": "shardling", "u": "cryoturret", "w": "prismwisp",
    "5": "capsule:cap_crys",
}, {
    "A": ("crys_4", "B"),
    "B": ("crys_boss", "A"),
}, extra='  mapPos = { x = 10, y = 0, w = 3, h = 1 },\n')

# crys_boss: Prism Tyrant
r = Room(60, 22)
r.interior(2, 2, 16)
r.door_left("A", 15, 16)
r.oneway(12, 20, 12)
r.oneway(39, 47, 12)
r.oneway(25, 34, 8)
r.put(30, 16, "t")
emit("crys_boss", r, "crystal", "crystal", {
    "t": "boss:prismtyrant",
}, {
    "A": ("crys_5", "B"),
}, extra='  mapPos = { x = 13, y = 0, w = 3, h = 1 },\n')

# ==================================================================
# SKYROOT SPIRE
# ==================================================================
# sky_1: the climb from the mosswood canopy
r = Room(30, 34)
r.interior(2, 2, 29)
r.door_bottom("A", 14, 16)
r.door_top("B", 14, 16)
r.platform(4, 10, 27)
r.platform(14, 20, 24)
r.oneway(22, 27, 21)
r.platform(8, 16, 18)
r.oneway(2, 6, 15)
r.platform(18, 26, 12)
r.oneway(10, 16, 9)
r.platform(2, 8, 6)
r.oneway(18, 24, 4)
r.put(24, 11, "y")
r.put(6, 14, "y")
r.put(12, 8, "l")
r.put(4, 27, "z")
emit("sky_1", r, "skyroot", "skyroot", {
    "y": "windray", "l": "sporeballoon", "z": "checkpoint",
}, {
    "A": ("moss_3", "C"),
    "B": ("sky_2", "A"),
}, extra='  mapPos = { x = 0, y = 3, w = 1, h = 3 },\n')

# sky_2: branch landing (save + teleporter + secret)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_bottom("A", 6, 8)
r.door_right("B", 10, 11)
r.put(14, 11, "s")
r.put(20, 11, "t")
r.put(32, 11, "k")
r.put(44, 6, "l")
r.oneway(40, 48, 7)
for y in (9, 10, 11):
    r.g[y][52] = "%"
r.g[10][53] = "E"
r.g[11][53] = "E"
r.g[10][54] = "E"
r.g[11][54] = "E"
emit("sky_2", r, "skyroot", "skyroot", {
    "s": "save", "t": "teleporter:skyroot", "k": "skylancer",
    "l": "sporeballoon",
}, {
    "A": ("sky_1", "B"),
    "B": ("sky_3", "A"),
    "C": ("sky_2", "A"),
    "E": ("sky_secret", "A"),
}, extra='  mapPos = { x = 0, y = 2, w = 3, h = 1 },\n'
   '  hasSave = true,\n  hasTeleporter = true,\n')

# sky_secret: nest of scrap
r = Room(30, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.put(10, 11, "1")
r.put(18, 11, "2")
emit("sky_secret", r, "skyroot", "skyroot", {
    "1": "chest:chest_sky1:scrap:15",
    "2": "chest:chest_sky2:bigshard:5",
}, {
    "A": ("sky_2", "E"),
}, extra='  mapPos = { x = 3, y = 3, w = 1, h = 1 },\n')

# sky_3: wind-swept anchors + tank vault
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# spike chasm with anchor crossings
r.open_box(12, 12, 47, 14, ".")
r.hline(12, 47, 15, "^")
r.put(18, 6, "n")
r.put(28, 4, "n")
r.put(38, 6, "n")
r.put(24, 9, "y")
r.put(36, 9, "y")
# tank vault above door B, plate on left side
r.platform(48, 56, 6)
r.g[5][50] = "4"
for y in (3, 4, 5):
    r.g[y][48] = "G"
r.hline(48, 56, 2)
r.put(6, 11, "x")
emit("sky_3", r, "skyroot", "skyroot", {
    "n": "anchor", "y": "windray", "4": "tank:tank_sky",
    "x": "plate:plate_s3:latch",
}, {
    "A": ("sky_2", "B"),
    "B": ("sky_4", "A"),
}, extra='  mapPos = { x = 3, y = 2, w = 3, h = 1 },\n'
   '  gates = { G = "plate_s3" },\n')

# sky_4: the great climb
r = Room(30, 34)
r.interior(2, 2, 29)
r.door_left("A", 28, 29)
r.door_top("B", 14, 16)
r.platform(8, 14, 27)
r.oneway(18, 24, 24)
r.platform(2, 8, 21)
r.hline(12, 14, 18, "c")
r.hline(20, 22, 15, "c")
r.platform(4, 10, 12)
r.oneway(14, 20, 9)
r.platform(22, 27, 6)
r.put(6, 20, "l")
r.put(16, 14, "y")
r.put(10, 11, "k")
r.put(24, 5, "z")
r.put(4, 11, "5")
emit("sky_4", r, "skyroot", "skyroot", {
    "l": "sporeballoon", "y": "windray", "k": "skylancer",
    "z": "checkpoint", "5": "capsule:cap_sky",
}, {
    "A": ("sky_3", "B"),
    "B": ("sky_boss", "A"),
}, extra='  mapPos = { x = 6, y = 1, w = 1, h = 2 },\n')

# sky_boss: Aerie Sentinel
r = Room(60, 22)
r.interior(2, 2, 16)
r.door_bottom("A", 6, 8)
r.oneway(12, 20, 12)
r.oneway(39, 47, 12)
r.put(4, 16, "n")
r.put(54, 16, "n")
r.put(30, 16, "t")
# spike walls (the gust threat)
for y in range(4, 16):
    r.g[y][2] = ">"
    r.g[y][57] = "<"
emit("sky_boss", r, "skyroot", "skyroot", {
    "n": "anchor", "t": "boss:aeriesentinel",
}, {
    "A": ("sky_4", "B"),
}, extra='  mapPos = { x = 6, y = 0, w = 3, h = 1 },\n')

# ==================================================================
# THE CORE
# ==================================================================
# core_1: the sealed threshold
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# the three-key gate right at the entry
for y in (8, 9, 10, 11):
    r.g[y][10] = "G"
r.put(6, 11, "1")
r.put(16, 11, "z")
r.put(24, 11, "v")
r.put(38, 8, "v")
r.oneway(34, 42, 9)
r.put(50, 11, "q")
emit("core_1", r, "core", "core", {
    "1": "sign:sign_core", "z": "checkpoint", "v": "sentinel",
    "q": "eliteguard",
}, {
    "A": ("camp_main", "C"),
    "B": ("core_2", "A"),
}, extra='  mapPos = { x = 0, y = 0, w = 3, h = 1 },\n'
   '  gates = { G = "coredoor" },\n')

# core_2: antechamber (final save + teleporter)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
r.put(10, 11, "s")
r.put(16, 11, "t")
r.put(30, 11, "m")
r.put(40, 11, "q")
r.put(46, 6, "v")
r.oneway(42, 50, 7)
r.put(6, 11, "1")
emit("core_2", r, "core", "core", {
    "s": "save", "t": "teleporter:core", "m": "screamer",
    "q": "eliteguard", "v": "sentinel", "1": "sign:sign_core2",
}, {
    "A": ("core_1", "B"),
    "B": ("core_3", "A"),
    "C": ("core_2", "A"),
}, extra='  mapPos = { x = 3, y = 0, w = 3, h = 1 },\n'
   '  hasSave = true,\n  hasTeleporter = true,\n')

# core_3: the defense grid (timed plates under fire)
r = Room(60, 17)
r.interior(2, 2, 11)
r.door_left("A", 10, 11)
r.door_right("B", 10, 11)
# two successive gate walls, each opened by a timed plate behind the party
for y in (8, 9, 10, 11):
    r.g[y][22] = "G"
    r.g[y][40] = "H"
r.put(12, 11, "x")
r.put(30, 11, "y")
r.put(16, 11, "q")
r.put(34, 11, "m")
r.put(28, 6, "v")
r.oneway(24, 32, 7)
r.put(48, 11, "5")
emit("core_3", r, "core", "core", {
    "x": "plate:plate_core3a", "y": "plate:plate_core3b",
    "q": "eliteguard", "m": "screamer", "v": "sentinel",
    "5": "capsule:cap_core",
}, {
    "A": ("core_2", "B"),
    "B": ("core_4", "A"),
}, extra='  mapPos = { x = 6, y = 0, w = 3, h = 1 },\n'
   '  gates = { G = "plate_core3a", H = "plate_core3b" },\n')

# core_4: the long descent
r = Room(30, 32)
r.interior(2, 2, 27)
r.door_left("A", 6, 7)
r.door_bottom("B", 14, 16)
r.platform(2, 8, 8)
r.platform(12, 18, 12)
r.platform(20, 27, 16)
r.platform(8, 16, 20)
r.platform(2, 6, 24)
r.platform(12, 18, 27)
r.put(14, 11, "v")
r.put(10, 19, "q")
r.put(15, 26, "z")
r.put(22, 15, "m")
emit("core_4", r, "core", "core", {
    "v": "sentinel", "q": "eliteguard", "m": "screamer",
    "z": "checkpoint",
}, {
    "A": ("core_3", "B"),
    "B": ("core_boss", "A"),
}, extra='  mapPos = { x = 9, y = 0, w = 1, h = 2 },\n')

# core_boss: the Mother Engine
r = Room(80, 22)
r.interior(2, 2, 16)
r.door_top("A", 6, 8)
r.oneway(14, 24, 12)
r.oneway(55, 65, 12)
r.oneway(33, 46, 8)
r.put(30, 16, "t")
emit("core_boss", r, "core", "core", {
    "t": "boss:motherengine",
}, {
    "A": ("core_4", "B"),
}, extra='  mapPos = { x = 10, y = 1, w = 4, h = 1 },\n')

print("done")
