#!/usr/bin/env python3
"""Build the nine Scrapyard rooms. Grid-stamped rather than hand-typed so
every row width, door side and wall is checked as it is written."""
import os

import os as _os
import sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import roommodel as _RM
TILE = _RM.TILES          # from world.lua; never typed here
DOORS = set("ABCDEF")
GATES = set("GHIJ")

class R:
    def __init__(self, name, w, h, floor):
        self.name, self.W, self.H, self.floor = name, w, h, floor
        # solid slab, then carve the play area
        self.g = [["#"] * w for _ in range(h)]
        for y in range(2, floor):
            for x in range(2, w - 2):
                self.g[y][x] = "."
    def put(self, x, y, s):
        for i, c in enumerate(s):
            assert 0 <= x + i < self.W and 0 <= y < self.H, (self.name, x, y, s)
            self.g[y][x + i] = c
    def col(self, x, y0, y1, c):
        for y in range(y0, y1 + 1):
            self.g[y][x] = c
    def doorL(self, ch, y0=None):
        y0 = y0 if y0 is not None else self.floor - 2
        for y in (y0, y0 + 1):
            self.g[y][0] = ch; self.g[y][1] = ch
    def doorR(self, ch, y0=None):
        y0 = y0 if y0 is not None else self.floor - 2
        for y in (y0, y0 + 1):
            self.g[y][self.W - 2] = ch; self.g[y][self.W - 1] = ch
    def portal(self, ch, x, y0=None):
        y0 = y0 if y0 is not None else self.floor - 2
        for y in (y0, y0 + 1):
            self.g[y][x] = ch; self.g[y][x + 1] = ch
    def rows(self):
        return ["".join(r) for r in self.g]

def side_of(rows, ch):
    W, H = len(rows[0]), len(rows)
    xs = [x for y in range(H) for x in range(W) if rows[y][x] == ch]
    ys = [y for y in range(H) for x in range(W) if rows[y][x] == ch]
    if not xs: return None
    if min(xs) == 0: return "left"
    if max(xs) == W - 1: return "right"
    if min(ys) == 0: return "top"
    if max(ys) == H - 1: return "bottom"
    return "portal"

ROOMS = {}
def emit(r, *, mapPos, links, key=None, gates=None, arena=None, music="scrapyard",
         zone="scrapyard", extra=""):
    rows = r.rows()
    w = len(rows[0])
    for i, row in enumerate(rows):
        assert len(row) == w, (r.name, i, len(row))
    ROOMS[r.name] = (rows, links, side_of)
    out = ["-- generated by scripts/genscrap.py (The Bulwark Line)", "return {"]
    out.append('  zone = "%s", music = "%s",' % (zone, music))
    if arena: out.append('  arena = "%s",' % arena)
    out.append("  mapPos = { x = %d, y = %d, w = %d, h = %d }," % mapPos)
    if extra: out.append(extra)
    if gates:
        out.append("  gates = { " + ", ".join('%s = "%s"' % kv for kv in gates.items()) + " },")
    out.append("  map = [[")
    out += rows
    out.append("]],")
    if key:
        out.append("  key = {")
        for k, v in key.items():
            out.append('    ["%s"] = "%s",' % (k, v))
        out.append("  },")
    out.append("  links = {")
    for k, v in links.items():
        out.append('    %s = { "%s", "%s" },' % (k, v[0], v[1]))
    out.append("  },")
    out.append("}")
    open("/home/claude/rooms/%s.lua" % r.name, "w").write("\n".join(out) + "\n")
    return rows

# ==================================================================
# 1. scrap_1 -- THE CHUTE. Arrival. Silence, then the first frames.
# ==================================================================
r = R("scrap_1", 30, 17, 12)
r.doorR("A"); r.doorL("B")
r.put(5, 4, "====")
r.put(17, 6, "====")
r.put(8, 8, "=====")
r.put(5, 11, "s")          # SORTING YARD 7 notice
r.put(12, 11, "1")         # VESSEL-3
r.put(20, 11, "2")         # VESSEL-5
emit(r, mapPos=(6, 0, 1, 1), arena="scrapyard",
     key={"s": "sign:sign_scrapyard", "1": "deadvess:1", "2": "deadvess:2"},
     links={"A": ("furn_2", "D"), "B": ("scrap_2", "C")})

# ==================================================================
# 2. scrap_2 -- SORTING LINE. First husks, conveyor ledges.
# ==================================================================
r = R("scrap_2", 60, 17, 12)
r.doorR("C")
r.portal("D", 12)
r.put(20, 5, "========")
r.put(34, 7, "======")
r.put(44, 4, "=======")
r.put(8, 8, "=====")
r.put(24, 9, "====")
r.put(26, 11, "h"); r.put(40, 11, "h"); r.put(50, 11, "h")
r.put(35, 6, "h")
r.put(46, 11, "3")         # VESSEL-6
r.put(18, 11, "z")
emit(r, mapPos=(3, 0, 3, 1), arena="scrapyard",
     key={"h": "scraphusk", "3": "deadvess:3", "z": "checkpoint"},
     links={"C": ("scrap_1", "B"), "D": ("scrap_3", "D")})

# ==================================================================
# 3. scrap_3 -- THE ROWS. Climbed on frame-stacks. First plateframe,
#    placed where you can simply walk around it.
# ==================================================================
r = R("scrap_3", 60, 17, 12)
r.doorR("B")
r.portal("D", 6)
r.put(12, 9, "======")
r.put(22, 7, "======")
r.put(32, 5, "=======")
r.put(44, 7, "======")
r.put(50, 9, "======")
r.put(34, 4, "f")          # on a ledge, facing the climb -- walk around it
r.put(16, 11, "h"); r.put(46, 11, "h")
r.put(24, 6, "h")
r.put(52, 11, "4")         # VESSEL-7
emit(r, mapPos=(3, 1, 3, 1), arena="scrapyard",
     key={"f": "plateframe", "h": "scraphusk", "4": "deadvess:4"},
     links={"D": ("scrap_2", "D"), "B": ("scrap_4", "A")})

# ==================================================================
# 4. scrap_4 -- PRESSING FLOOR. Three plateframes in a line, all facing
#    the door you came in by. This is the lesson.
# ==================================================================
r = R("scrap_4", 60, 17, 12)
r.doorL("A"); r.doorR("C")
r.portal("D", 28)
r.put(14, 8, "=====")
r.put(24, 6, "=====")
r.put(38, 8, "=====")
r.put(46, 6, "======")
r.put(16, 11, "f"); r.put(33, 11, "f"); r.put(48, 11, "f")
r.put(25, 5, "h"); r.put(40, 7, "h")
r.put(10, 11, "z")
emit(r, mapPos=(6, 1, 3, 1), arena="scrapyard",
     key={"f": "plateframe", "h": "scraphusk", "z": "checkpoint"},
     links={"A": ("scrap_3", "B"), "C": ("scrap_secret", "A"),
            "D": ("scrap_bay", "D")})

# ==================================================================
# 5. scrap_secret -- THE FILING OFFICE. The zone's most damning log.
# ==================================================================
r = R("scrap_secret", 30, 17, 12)
r.doorL("A")
r.put(20, 6, "=====")
r.put(9, 11, "s")
r.put(15, 11, "k")
r.put(22, 11, "9")
emit(r, mapPos=(9, 1, 1, 1), arena="scrapyard",
     key={"s": "sign:sign_scrap_bay", "k": "capsule:cap_scrap",
          "9": "chest:ch_scrap1:scrap:30"},
     links={"A": ("scrap_4", "C")})

# ==================================================================
# 6. scrap_bay -- RECLAMATION BAY. No enemies. Racks 1 through 8, and
#    the BULWARK PLATE on VESSEL-4.
# ==================================================================
r = R("scrap_bay", 30, 17, 12)
r.doorL("B")
r.portal("D", 24)
r.put(6, 6, "=======")
r.put(8, 11, "5")          # VESSEL-4: "left in place. He'd have wanted it kept."
r.put(11, 11, "b")         # the plate
r.put(17, 11, "s")
emit(r, mapPos=(6, 2, 1, 1), arena="scrapyard",
     key={"5": "deadvess:5", "b": "chest:ch_bulwark:module:bulwark",
          "s": "sign:sign_scrap_bay"},
     links={"D": ("scrap_4", "D"), "B": ("scrap_5", "C")})

# ==================================================================
# 7. scrap_5 -- THE GAUNTLET. Try your new toy: spike beds, vents, and
#    a plateframe wall. Every spike bed is still jumpable without the
#    plate -- the validators model a player who does not have one.
# ==================================================================
r = R("scrap_5", 60, 17, 12)
r.doorR("C")
r.portal("D", 8)
r.put(16, 11, "^^^")
r.put(26, 11, "^^^")
r.put(38, 11, "^^^")   # 3 wide: a 4-wide bed is not jumpable without the plate,
                       # and the validators model a player who has not found one yet
r.put(20, 8, "====")
r.put(31, 8, "====")
r.put(44, 7, "=====")
r.put(23, 4, "V")          # downward vent over the second bed
r.put(41, 4, "V")
r.put(34, 11, "f"); r.put(48, 11, "f")
r.put(45, 6, "h")
emit(r, mapPos=(3, 2, 3, 1), arena="scrapyard",
     key={"V": "vent:d:3.4", "f": "plateframe", "h": "scraphusk"},
     links={"C": ("scrap_bay", "B"), "D": ("scrap_6", "D")})

# ==================================================================
# 8. scrap_6 -- THE LONG ROOM. Gated on the plate. Two rammers, and the
#    frames get larger and more intact toward the far door.
# ==================================================================
r = R("scrap_6", 60, 17, 12)
r.doorR("B")
r.portal("D", 5)
r.col(22, 2, 11, "G")      # full-height: it genuinely separates
r.put(12, 8, "=====")
r.put(30, 8, "======")
r.put(44, 6, "======")
r.put(10, 11, "z")
r.put(16, 11, "6")         # VESSEL-8. Pending.
r.put(18, 11, "s")
r.put(30, 11, "r"); r.put(48, 11, "r")
emit(r, mapPos=(3, 3, 3, 1), arena="scrapyard",
     gates={"G": "bulwark"},
     key={"z": "checkpoint", "6": "deadvess:6", "s": "sign:sign_scrap_gate",
          "r": "rammer"},
     links={"D": ("scrap_5", "D"), "B": ("scrap_boss", "A")})

# ==================================================================
# 9. scrap_boss -- EIGHT. Flat floor, low platforms at the thirds,
#    unbroken walls at both ends (it needs to bounce), and ten clear
#    tiles of headroom so the vault fits.
#    The post-boss shortcut lives here, sealed behind boss_vessel8.
# ==================================================================
r = R("scrap_boss", 60, 17, 12)
r.doorL("A")
r.put(16, 8, "=======")     # two low platforms at the thirds
r.put(38, 8, "=======")
# THE WAY OUT: a racked alcove in the ceiling, sealed behind boss_vessel8.
# The alcove floor is SOLID, not oneway -- a oneway there let the player
# hop up through it from below and skip the gate entirely (GATE BYPASS).
r.put(44, 9, "======")      # climb: stand row 8
r.put(46, 6, "======")      #        stand row 5
r.put(46, 3, "=====")       #        stand row 2, walk right into the gate
r.put(51, 3, "####")        # alcove floor
r.g[2][51] = "H"
for y in (1, 2):
    r.g[y][52] = "E"; r.g[y][53] = "E"
r.g[2][54] = "#"
r.put(30, 11, "t")
emit(r, mapPos=(6, 3, 3, 1), arena="vessel8", music="scrapyard",
     gates={"H": "boss_vessel8"},
     key={"t": "boss:vessel8"},
     links={"A": ("scrap_6", "B"), "E": ("furn_2", "E")})

# ---- report
print("%-14s %-8s %s" % ("room", "size", "doors"))
for n, (rows, links, _) in ROOMS.items():
    ds = " ".join("%s:%s->%s:%s" % (c, side_of(rows, c), links[c][0], links[c][1])
                  for c in sorted(links))
    print("%-14s %dx%-6d %s" % (n, len(rows[0]), len(rows), ds))
