#!/usr/bin/env python3
"""Build THE DRIFT VANES content: the Nest, the Upper Gallery, and the
eight retrofits.

Run from game/ with PYTHONPATH=../scripts.

The retrofits do not use hand-picked coordinates. For each target room the
script asks roommodel which cells are reachable WITH the vanes and not
without, filters to the ones that are standable and free, scores them by
the co-op camera budget, and puts the reward on the best one. If a room
has no legal hover-only cell it says so instead of guessing.
"""
import os
import re
import sys
import roommodel as RM

ROOMS = "src/data/rooms"
VW, VH, T = RM.viewport()  # read out of main.lua, never copied
H_BUDGET, V_BUDGET = 0.75 * VW / T, 0.75 * VH / T


# ==================================================================
# room construction helpers (same shape as genscrap.py)
# ==================================================================
class R:
    def __init__(self, name, w, h, floor):
        self.name, self.W, self.H, self.floor = name, w, h, floor
        self.g = [["#"] * w for _ in range(h)]
        for y in range(2, floor):
            for x in range(2, w - 2):
                self.g[y][x] = "."

    def put(self, x, y, s):
        for i, c in enumerate(s):
            self.g[y][x + i] = c

    def col(self, x, y0, y1, c):
        for y in range(y0, y1 + 1):
            self.g[y][x] = c

    def doorL(self, ch, y0=None):
        y0 = self.floor - 2 if y0 is None else y0
        for y in (y0, y0 + 1):
            self.g[y][0] = ch; self.g[y][1] = ch

    def doorR(self, ch, y0=None):
        y0 = self.floor - 2 if y0 is None else y0
        for y in (y0, y0 + 1):
            self.g[y][self.W - 2] = ch; self.g[y][self.W - 1] = ch

    def portal(self, ch, x, y0=None):
        y0 = self.floor - 2 if y0 is None else y0
        for y in (y0, y0 + 1):
            self.g[y][x] = ch; self.g[y][x + 1] = ch

    def rows(self):
        return ["".join(r) for r in self.g]


def write_room(r, *, mapPos, links, key=None, gates=None, zone="skyroot",
               music="skyroot", extra=None):
    rows = r.rows()
    w = len(rows[0])
    for i, row in enumerate(rows):
        assert len(row) == w, (r.name, i, len(row))
    out = ["-- generated by scripts/genvanes.py (The Drift Vanes)", "return {"]
    out.append('  zone = "%s", music = "%s",' % (zone, music))
    out.append("  mapPos = { x = %d, y = %d, w = %d, h = %d }," % mapPos)
    for e in (extra or []):
        out.append(e)
    if gates:
        out.append("  gates = { " + ", ".join('%s = "%s"' % kv
                                              for kv in gates.items()) + " },")
    out.append("  map = [[")
    out += rows
    out.append("]],")
    if key:
        out.append("  key = {")
        for k, v in key.items():
            out.append('    ["%s"] = "%s",' % (k, v))
        out.append("  },")
    out.append("  links = {")
    for k, v in links.items():
        out.append('    %s = { "%s", "%s" },' % (k, v[0], v[1]))
    out.append("  },")
    out.append("}")
    open(os.path.join(ROOMS, r.name + ".lua"), "w").write("\n".join(out) + "\n")
    print("  wrote %-13s %dx%d" % (r.name, w, len(rows)))


def patch_map(name, fn):
    """Read a room's map, hand the grid to fn, write it back."""
    p = os.path.join(ROOMS, name + ".lua")
    s = open(p).read()
    m = re.search(r"map = \[\[\n(.*?)\]\]", s, re.S)
    g = [list(r) for r in m.group(1).split("\n") if r.strip()]
    W = len(g[0])
    s2 = fn(g, s)
    if s2 is not None:
        s = s2
    rows = ["".join(r) for r in g]
    for r in rows:
        assert len(r) == W, (name, len(r), W)
    m = re.search(r"map = \[\[\n(.*?)\]\]", s, re.S)
    s = s[:m.start(1)] + "\n".join(rows) + "\n" + s[m.end(1):]
    open(p, "w").write(s)


# ==================================================================
# 1. THE NEST -- sky_nest, off sky_4
# ==================================================================
def build_nest():
    r = R("sky_nest", 30, 17, 12)
    r.doorL("A")
    r.put(6, 8, "=====")
    r.put(18, 6, "======")
    r.put(9, 11, "1")          # the Perch 2 notice
    r.put(15, 11, "N")         # the nest itself
    r.put(17, 11, "3")         # the vanes, in it (NOT "v": that is SPIKE_D)
    write_room(r, mapPos=(7, 1, 1, 1),
               key={"1": "sign:sign_perch2", "N": "nest",
                    "3": "chest:chest_driftvanes:module:driftvanes"},
               links={"A": ("sky_4", "C")})

    # sky_4 gets door C on the right edge, rows 4-5: the shelf at row 5 is
    # already standable (the checkpoint sits on it) and row 6 under it is
    # solid, so the door needs no new geometry at all.
    def f(g, s):
        for y in (4, 5):
            assert g[y][28] == "#" and g[y][29] == "#", (y, g[y][26:])
            g[y][28] = g[y][29] = "C"
        assert g[6][28] == "#" and g[6][27] == "#", "shelf under the door"
        return s.replace('    B = { "sky_boss", "A" },',
                         '    B = { "sky_boss", "A" },\n'
                         '    C = { "sky_nest", "A" },', 1)
    patch_map("sky_4", f)
    print("  patched sky_4: door C -> sky_nest")


# ==================================================================
# 2. THE UPPER GALLERY -- gal_1 / gal_2 / gal_3, behind the vanes gate
# ==================================================================
def build_gallery():
    # ---- sky_2: a sealed pocket behind a full-height driftvanes gate.
    # Same shape as scrap_6's gate, which validated: the column genuinely
    # separates, and the pocket contains its own door so it is not a trap.
    def f(g, s):
        for y in range(2, 12):
            assert g[y][4] == ".", (y, g[y][:8])
            g[y][4] = "G"
        for y in (10, 11):
            g[y][2] = g[y][3] = "C"
        s = s.replace('  mapPos = { x = 0, y = 2, w = 3, h = 1 },',
                      '  mapPos = { x = 0, y = 2, w = 3, h = 1 },\n'
                      '  gates = { G = "driftvanes" },', 1)
        return s.replace('    E = { "sky_secret", "A" },',
                         '    E = { "sky_secret", "A" },\n'
                         '    C = { "gal_1", "A" },', 1)
    patch_map("sky_2", f)
    print("  patched sky_2: driftvanes gate + portal C -> gal_1")

    # ---- gal_1 THE SPAN. 30 wide on purpose: exactly one screen, so the
    # camera never scrolls and the pair cannot be split (see the plan, 5.3).
    # An 11-tile gap at the upper level; missing it drops you to the floor
    # and costs a climb, not health.
    r = R("gal_1", 30, 17, 12)
    r.portal("A", 3, y0=6)
    r.doorR("B", y0=6)
    r.put(2, 8, "#######")        # left platform  (stand row 7, cols 2-8)
    r.put(20, 8, "########")      # right platform (stand row 7, cols 20-27)
    r.put(9, 10, "===")           # the climb back out of the pit
    r.put(24, 11, "1")
    write_room(r, mapPos=(0, 1, 1, 1),
               key={"1": "sign:sign_span"},
               links={"A": ("sky_2", "C"), "B": ("gal_2", "A")})

    # ---- gal_2 THE COMBS. Two stacked thermal columns, 12 and 10 tiles,
    # with a shared landing between them. Both are inside the 12.7-tile
    # vertical camera budget, so Vess watches her the whole way up.
    # No anchors in this room: this is the gated wing.
    r = R("gal_2", 30, 34, 32)
    r.doorL("A", y0=30)
    r.doorR("B", y0=10)
    r.put(9, 21, "################")   # mid landing (stand row 20, cols 9-24)
    r.put(21, 12, "#######")           # top landing (stand row 11, cols 21-27)
    r.put(8, 31, "U")                  # column 1: rows 20..31
    r.put(20, 20, "u")                 # column 2: rows 11..20
    r.put(4, 31, "z")
    r.put(12, 20, "y")                 # windray on the mid landing
    r.put(23, 11, "q")                 # stormvane on the top landing
    r.put(16, 20, "y")
    write_room(r, mapPos=(1, 0, 1, 2),
               key={"U": "updraft:12", "u": "updraft:10", "z": "checkpoint",
                    "y": "windray", "q": "stormvane"},
               links={"A": ("gal_1", "B"), "B": ("gal_3", "A")})

    # ---- gal_3 THE LONG ROOM. Lockers, a roster, and the tank.
    r = R("gal_3", 60, 17, 12)
    r.doorL("A")
    r.put(10, 8, "======")
    r.put(30, 7, "=======")
    r.put(44, 9, "======")
    r.put(8, 11, "1")
    r.put(20, 11, "2")
    r.put(34, 11, "3")
    r.put(50, 11, "4")
    r.put(46, 8, "z")
    write_room(r, mapPos=(2, 0, 3, 1),
               key={"1": "sign:sign_roster1", "2": "sign:sign_roster2",
                    "3": "sign:sign_roster3", "4": "tank:tank_gallery",
                    "z": "checkpoint"},
               links={"A": ("gal_2", "B")})


# ==================================================================
# 3. THE RETROFITS -- the model picks the cell, not me
# ==================================================================
RETROFITS = [
    # room,        char, spec,                              preferred side
    ("cradle_1",   "N",  "sign:sign_sleepers",              None),
    ("moss_5",     "9",  "chest:ch_moss_high:scrap:20",     None),
    ("flood_2",    "T",  "tank:tank_flood",                 None),
    ("furn_4",     "9",  "chest:ch_furn_high:bigshard:6",   None),
    ("cold_1",     "9",  "chest:ch_cold_high:bigshard:6",   None),
    ("crys_boss",  "9",  "chest:ch_crys_high:scrap:25",     None),
    ("sky_boss",   "9",  "chest:ch_roost:bigshard:8",       None),
    ("camp_awake", "9",  "chest:ch_shelf:scrap:15",         None),
]


def hover_only_cells(room):
    def reach(with_vanes):
        flags = set(RM.ALL_ABILITIES)
        if not with_vanes:
            flags.discard("driftvanes")
        for ch, f in room.gates.items():
            f = f[1:] if f.startswith("!") else f
            if not with_vanes and f == "driftvanes":
                continue
            flags.add(f)
        nav = RM.Nav(room, flags)
        if not room.doors:
            return set()
        start = set()
        for ch in room.doors:
            start |= set(nav.arrivals(ch)) | set(room.doors[ch])
        return nav.reach_from(start)
    without, withv = reach(False), reach(True)
    return without, withv - without


def do_retrofits():
    for name, ch, spec, _side in RETROFITS:
        room = RM.parse_room(os.path.join(ROOMS, name + ".lua"))
        without, gated = hover_only_cells(room)
        h_scroll = room.W * T > VW
        v_scroll = room.H * T > VH
        occupied = {c for cells in (room.spawns or {}).values() for c in cells}
        best, best_score = None, None
        for (x, y) in sorted(gated):
            if (x, y) in occupied:
                continue
            nav = RM.Nav(room, set(RM.ALL_ABILITIES))
            if not nav.standable(x, y):
                continue
            if ch in room.key:            # char already used for something else
                continue
            # co-op cost: how far from the nearest place Vess can stand
            dh = min(abs(x - ax) for (ax, ay) in without) if without else 0
            dv = min(abs(y - ay) for (ax, ay) in without) if without else 0
            if h_scroll and dh > H_BUDGET:
                continue
            if v_scroll and dv > V_BUDGET:
                continue
            score = (dh + dv, -x)         # prefer the tightest, then leftmost
            if best_score is None or score < best_score:
                best, best_score = (x, y), score
        if not best:
            print("  SKIP %-12s no legal hover-only cell inside the co-op budget"
                  % name)
            continue
        bx, by = best

        def f(g, s, bx=bx, by=by, ch=ch, spec=spec):
            assert g[by][bx] == ".", (name, bx, by, g[by][bx])
            g[by][bx] = ch
            if "key = {" in s:
                return s.replace("  key = {",
                                 '  key = {\n    ["%s"] = "%s",' % (ch, spec), 1)
            return s.replace("  links = {",
                             '  key = {\n    ["%s"] = "%s",\n  },\n  links = {'
                             % (ch, spec), 1)
        patch_map(name, f)
        print("  %-12s '%s' at %-9s  (%d h / %d v tiles from Vess)"
              % (name, ch, str(best), best_score[0] - 0, 0))


def main():
    print("THE NEST")
    build_nest()
    print("THE UPPER GALLERY")
    build_gallery()
    print("RETROFITS")
    do_retrofits()
    print("done")


if __name__ == "__main__":
    main()
